doc/Quick-Start-Guide.rst
=> doc: Verify the documentation steps

be/seg.c
Segment header generation identifier is populated with epoch during mkfs.
Use this epoch to populate btree's generation identifier.
=> EOS-13526 be/seg.c: populate btrees with segment header generation identifier

be/tool/beck.c
Following cases are covered:
1) If source segment header generation identifier is zero then process all the
bnodes.
2) If source segment header generation identifer is non-zero then process only
the bnodes with matching generation identifier.
=> EOS-13526 beck.c: filter bnodes based on generation identifier in beck tool

scripts/install/opt/seagate/cortx/motr/libexec/motr_data_recovery.sh, scripts/install/opt/seagate/cortx/motr/libexec/prov-m0-reset, utils/m0reportbug
Changed prov-m0-reset to support running mkfs on both the nodes so
that LVM snapshot reflects the correct data on both the nodes.
=> EOS-13463: motr data recovery script changes to run mkfs on both nodes.

addb2/sit.c
Fixed an error "m0addb2dump: Cannot initialise iterator: -71: No such file
or directory" during the parsing of rotated ADDB stob file.
There are two reasons of this error:
- incorrect detection that ADDB stob is rotated
- sometimes ADDB stob header is not correct. It is a copy of the header
of the non-last frame while there are newer frames located at the stob.
This patch has improvements of detection that ADDB stob is rotated
and detection of last frame on the stob.
=> EOS-13258: m0addb2dump: fixed an iterator initialization error

motr/setup.c
If a signal is recieved in CS_LEVEL_REQH_STOP_WORKAROUND, m0_module_fini
is called, In m0_module_fini CS_LEVEL_RPC_MACHINES_INIT would assert
because there are active ongoing connection.
ideally connections are closed in cs_ha_fini, because
CS_LEVEL_REQH_STOP_WORKAROUND was not called, cs_ha_fini was never called.
Solution: In cs_level_enter::CS_LEVEL_REQH_STOP_WORKAROUND, it does
nothing, skip the error in CS_LEVEL_REQH_STOP_WORKAROUND which will be handled
in the next state. during fini, cs_ha_fini is called before
CS_LEVEL_RPC_MACHINES_INIT
/lib64/libmotr.so.1(m0_arch_backtrace+0x2f)[0x7f859e446baf]
/lib64/libmotr.so.1(m0_arch_panic+0xf3)[0x7f859e446d93]
/lib64/libmotr.so.1(+0x32a414)[0x7f859e437414]
/lib64/libmotr.so.1(m0_rpc_machine_fini+0x2c5)[0x7f859e4ca5a5] …
=> EOS-10455: Motr crashes observed after data network was down

scripts/install/opt/seagate/cortx/motr/conf/setup.yaml
/etc/sysconfig/motr is added to backup in-case of node replacement
this is restored.
Also added post update conf, which will be called after rpm is updated.
It is needed in case any config parameters are updated in the new
rpm package.
=> EOS-13784 m0provision: backup motr conf file and is restored after node replaced

utils/spiel/m0_filesystem_stats
hostname was used to get the current host endpoints from consul,
in the recent builds, consul sends minion_id instead of hostname
so server and client endpoints were not recieved.
Solution: use minion_id instead of hostname.
=> m0_filesystem_stats: use minion id instead of hostname in consul query

utils/m0reportbug
Updated path of $CORE_DIR from /var/crash to /var/log/crash, CORE_DIR
is a path from where we collected compressed cores files.
=> EOS-13854 m0reportbug: Updated path of compressed core directory

scripts/install/usr/libexec/cortx-motr/motr-server
Currently be seg size MOTR_M0D_IOS_BESEG_SIZE from /etc/sysconfig/motr
not being used and default value of 8GB is used due to a bug in
motr-server script, which checks for "^ios" regex in systemd unit file,
which is no longer used with hare based cluster.
The following crash is observed,
#3  0x00007fca296780b4 in m0_panic (ctx=ctx@entry=0x7fca29a72020 <__pctx.8247>) at lib/assert.c:52
#4  0x00007fca295bdf20 in mem_alloc (zonemask=2, size=<optimized out>, tx=0x7fc84c2266b8, btree=0x40000015f210) at be/btree.c:127
#5  btree_save (tree=tree@entry=0x40000015f210, tx=tx@entry=0x7fc84c2266b8, op=op@entry=0x7fc92bffe460,
key=key@entry=0x7fc92bffe6d0, val=val@entry=0x7fc92bffe6e0, anchor=anchor@entry=0x0, optype=optype@entry=BTREE_SAVE_INSERT,
zonemask=zonemask@entry=2) at be/btree.c:1453
#6 …
=> EOS-13878 scripts: use MOTR_M0D_IOS_BESEG_SIZE for ioservice

be/alloc.c
update allocator stats before chuck size gets modified due to
merge during free operation.
=> EOS-13867 be/alloc: add correct freed size to stats in m0_be_free()

scripts/beck/st/README, scripts/beck/st/error_injection.py
1. To keep search record if no of error induced is greater than available records
2. Added Seed for generating random number
3. loggin start-stop time
4. Skip if valid type not found in the metadata
5. Miscellaneous small fixes
Signed-off-by: Gaurav Gaur <gaurav.gaur@seagate.com>
=> EOS-13177: bug fix in error_injection.py to create holes in metadata

utils/m0setup
Modified logic to only use next available loop devices and
only detach loop devices which were attached by m0setup.
=> EOS-13875 m0setup: use next available loop devices

utils/trace/m0trace
Signed-off-by: Maksym Medvied <max.medved@seagate.com>
=> m0trace: typo fix in --help

be/tool/beck.c
The previous code had a bug where it was passing the extent's start offset in the
COB logical space to balloc.  While writing too many objects we ran into situation of same 
extent getting reserved already and we were getting error about failure in reserving extent.
Instead the extent's offset in the balloc space needs to be passed to balloc for reserving the extent.
Also similar change is done in passing the extent end location to balloc.
=> EOS-13891 beck: fixed balloc extent calculation

be/tool/beck.c
If generation identifier is found in segment header one then only, update
the s_gen_found field in scanner. If the generation identifier of segment 
header one is corrupted then use the generation identifier provided in 
command line input of beck tool till valid generation identifier is found in 
btree/bnode.
Updated the description for 'g' parameter which is used for storing command
line generation identifier input.
Removed M0_ERR from bnode_check() and btree_check(), since it was flooding
script log with error messages that can be avoided.
Added prints for printing generation id once valid generation identifier is found
in btree or bnode. 
Added extra line after printing destination segment generation identifier for better
display in log file.
Signed-off-by: Nikhil Kumar Birgade …
=> EOS-13891 beck: handle segment header generation identifier corruption case

be/tool/beck.c
With previous code directio=false, the value of adom->sad_babshift was getting 
incorrectly derived hence there was issue in reserving balloc extents.
Now by default directio=true, and If option -I is provided in beck, directio will be disabled.
Signed-off-by: Jaydeep Mohite <jaydeep.mohite@seagate.com>
=> EOS-13891 beck: enabled directio for stob domain

net/lnet/linux_kernel/klnet_core.c, net/lnet/linux_kernel/klnet_drv.c, net/lnet/lnet.h, net/lnet/lnet_core.h, net/lnet/lnet_main.c, net/lnet/st/ping.h, net/lnet/ulnet_core.c, net/lnet/ulnet_core.h, net/lnet/ut/linux_kernel/klnet_ut.c, net/lnet/ut/lnet_ut.c, net/test/user_space/common_u.c
Currently we have a list of LNIDs, which is cached during m0tr.ko module
insertion. During the failover, LNID is added in runtime to LNet
configuration, which currently lifts the requirement to re-insert
m0tr.ko kernel module (and hence, the restart of all the Motr-processes
running on the node as well). This slows down the failover/failback time
considerably.
Solution: get rid of the LNIDs caching in m0tr.ko kernel module.
Instead, LNIDs are queried from LNET every time they are needed.
Signed-off-by: Maksym Medvied <max.medved@seagate.com>
=> EOS-6023 net/lnet: remove LNID cache

utils/m0reportbug
* In last version update there was version mismatch, corrected that.
* Updated correct name of libgalois. libgalois  library name itself
contains version name (libgalois-0.1.so) updated actual name in
path_rpm() and path_src()
* Redirected error logs (m0tracedump, journalctl) into REPORT file so
that it won't reflect on terminal but can be seen in report summary.
* Removed logs/binary collection related to halon since we are not using
it, also bumped up version by 2 (since it was missed in last commit)
=> EOS-13890 m0reportbug: Removed halon related things and fixed warn/error logs

scripts/install/usr/libexec/cortx-motr/motr-mkfs
The values of BE SEG size for isoervices is set to LVM size, but
there is also another command-line argument for the same wth default
is passed from in motr-mkfs.
m0mkfs ... -B /dev/vg_metadata_srvnode-1/lv_raw_metadata -z 19060511211520
-F -u 9b81188a-0783-11eb-88b3-a4bf011bf6c1 -z 8589934592
This is fixed by adding SEG SIZE for ioservice through motr-server only.
=> EOS-14179 scripts: fix over-writing of BE SEG size for mkfs for ios

scripts/install/opt/seagate/cortx/motr/libexec/motr_data_recovery.sh
Issue:
Recovery script exited with description
"Device vg_metadata_srvnode--2-lv_raw_metadata-real (253:22) is used by
another device. Failed to resume lv_raw_metadata."
Able to delete the snapshot manually after this.
Fix:
Suspecting that the problem is related to outstanding IOs not getting flushed
to the device.  Flushed buffer for snapshot and metadata devices 
To be sure also added 5 minutes delay to flush out outstanding IOs.
Fixed alignment in replay_logs_and_get_gen_id_of_seg0()
=> EOS-14082: fix failed to resume lv_meta_data while removing the snapshot

utils/spiel/m0_filesystem_stats
Sometimes on VM, motr sanity test fails because m0_filesystem_stats
cannot complete it 5s and errors with timeout, to avoid this
increase the timeout to 10s.
=> EOS-14130 m0_filesystem_stats: Increase timeout to 10s

rpc/rpc_internal.h, rpc/session_foms.c, rpc/session_utils.c
Now RPC ids are generated by hashing the unique fid of reqh service
with the timestamp seed to make the RPC id unique across the cluster.
This change is required to mitigate the case when RPC ids collide
due to them generated at the same local time across different systems
with unsynchronized clocks.
=> EOS-13842: unique RPC id across cluster

be/domain.c, be/domain.h, be/tool/main.c, be/ut/helper.c, be/ut/helper.h, motr/st/utils/be_log_resize.sh, motr/st/utils/be_log_set.sh
Added "create_be_log" flag to create BE log file without m0mkfs.
'path' and 'size' are mandatory arguments and size should be in bytes.
Co-authored-by: Vikram Jadhav <vikram.jadhav@seagate.com>
=> EOS-14158 m0betool: create BE log file without m0mkfs

scripts/install/usr/libexec/cortx-motr/motr-free-space-monitor
- free-space-monitor service is calling m0_motr_iem but this API has
been renamed as m0_iem.
- initialise m0_time_init() before calling m0_iem if calling through
python C extention because m0_init is not called from python code.
=> EOS-14385 free-space-monitor: cluster size IEM alerts are not received

m0t1fs/linux_kernel/file.c, m0t1fs/linux_kernel/file_internal.h, motr/client.h, motr/io_nw_xfer.c, motr/io_req_fop.c, motr/pg.h, motr/st/utils/helper.c, motr/st/utils/motr_utils_st.sh
- target_ioreq::ti_cc_fop is used in some cases.
It is initialized and then be m0_rpc_post().
It needs m0_fop_put() in all cases.
- A flag target_ioreq::ti_cc_fop_inited is used to do put
for this fop, to avoid leakage.
- More debug messages added.
=> EOS-14172 EOS-14166: rpc fop needs m0_fop_put()

conf/rconfc.c, conf/ut/rconfc.c, motr/ut/cs_ut_main.c
- Issue: rconfc-ut:no-rms finalizes rpc session before finilazing all rpc items in it
- rpc session fini happens in rconfc_read_lock_complete() callback for failed
read lock request which is called by outreq_fini(). Then, outreq_fini() is finalizing
rpc items.
- rlock_ctx_creditor_unset is moved to rconfc failure ast callback, so outreq_fini()
will finilaze rpc items then rconf failure callback will call rlock_ctx_creditor_unset
to finilaze rpc session
- fix rconfc-ut:start-fail ut failing by adding FI to pass rlock_ctx_creditor_unset from
failure callback
=> EOS-14164 rconfc: rpc session fini from failed read lock request moved to failure ast callback

scripts/gen-src-skel, scripts/licence_header
The file scripts/gen-src-skel was using license from top cortx-motr directory to generate header.
This needed to be changed as the licence in header was modifed for newer files.
Added a new file scripts/licence_header which has the required header text.
scripts/gen-src-skel now uses this file to add header text.
=> EOS-14338 scripts: Changes to gen-src-skel to modify licence header

scripts/install/usr/libexec/cortx-motr/motr-free-space-monitor
In motr-free-space-monitor `hctl status --json` is called to get cluster
size but sometime it might happen that it failed to parse or cluster size
is zero in such case trying again to get cluster size upto max retry count.
Removed other un-necessasry things like cleanup_motrace() and other error codes.
=>  EOS-14327 motr-free-space-monitor: Added loop to retry on output parse failure

motr/m0d.c, scripts/install/usr/lib/systemd/system/m0d@.service
Pacemaker starts Motr clients after Motr servers processes, but since
pacemaker returns success after systemd process successfully starts.
In this case Motr server may not be started fully and functional to
cater requests and accepts requests from Motr client.
Solution:
Move sd_notify() after m0_cs_start(). It will make sure that when
systemd gets READY event from m0d all Motr internal services are started.
Motr server connects to all Motr internal services from other instance
of Motr servers asynchronously.
Ref: EOS-13872
=> Problem: Motr clients start before Motr IOS process starts functional

addb2/dump.c, scripts/addb-py/chronometry/addb2db.py
Problem:
As a result of the renaming we have got an inconsistency
between scripts that builds database and timelines scripts
for ioo and dix operations: prior ones use short 'id' as a
client id while latter ones use long 'client_id'.
Solution:
Proper way is to use the long form as it corresponds to
the common antities mapping approach that was implemented
initially. Current fix implements it. Now only long form
of client id is used.
=> scripts: fix client id name

be/tool/beck.c
Added support in beck to override BE config default values with the values
provided through a YAML file. These values could be used to tune the beck for
performance.
=> support in beck to override BE config defaults using yaml config file

Makefile.am, cortx-motr.spec.in, motr/setup.c, scripts/install/opt/seagate/cortx/motr/libexec/m0addb_logrotate.sh, utils/m0reportbug
1. Generate new addb-stobs directory during every m0d restart instead of during mkfs only.
2. The newly generated addb-stob directory is appended with the server pid. i.e addb-stobs-$PID
3. Limit number of addb-stob directories in m0d directory to 2.
=> EOS-14450: Added changes to resize addb stobs without mkfs

cortx-motr.spec.in, scripts/install/opt/seagate/cortx/motr/libexec/motr_cfg.sh, utils/m0reportbug
userconfig only if key-value are different
- modified  m0tr_cfg.sh to update /etc/sysconfig/motr
only when therer is a change in values of config params
- redirected warnings to motr-rpm-conf-update.log
Signed-off-by: Vinoth <root@ssc-vm-c-0971.colo.seagate.com>
=> [EOS-14777] Suppress warning during motr rpm update and update

be/tool/beck.c
1) Divide scanner into two parts. The first part will find the bnodes and
put these bnodes into a queue. The second part will process the bnodes 
in a thread.
2) Add partitions in scanner. There is one partition for COB, CTG and AD domain
each. 
3) Use IONBF as option in setvbuf for performance improvement.
=> EOS-14234 beck: Add scanner thread and partition support

scripts/addb-py/chronometry/addb2db.py
* Symptom seen before fix:
OverflowError: Python int too large to convert to SQLite INTEGER:
db_consume_data(args.dumps)
File "addb2db.py", line 588, in db_consume_data
globals()[k].insert_many(batch).execute().
* Sqlite integer fields are int64 and addb2dump produces uint64.
=> EOS-14966: Fixed fom_desc::sender according to the addb2dump output

.xperior/testds/motr-single_tests.yaml
- total 5 group created 01motr-single-node to 05motr-single-node
- If no test group assigned, motr-single-node as a default
=> EOS-10682 xperior/testds: test group created for motr single node test

utils/m0provision
During motr sanity it goes for be_log_resize(), where it further moves
ahead because config parameter MOTR_M0D_BELOG_SIZE is not disabled
During sanity test it is not expected to go for be_log_resize() hence
disabled MOTR_M0D_BELOG_SIZE before sanity run and enabled it back later.
=> EOS-14977: Fixed motr sanity failure due to BELOG_SIZE

ioservice/ut/storage_dev_ut.c
Fix for EOS-14450 introduce change in format of addb stob location, which was
causing failure in "storage-dev-ut" due to hardcoded stob location. Changed
hard-coded stob location a per new format.
=> EOS-14895: Fixed panic in storage-dev-ut

.xperior/testds/motr-single_tests.yaml
=> EOS-15052 increase timeout value for 47motr-tests-user-kernel

lib/ut/vec.c, lib/vec.c, lib/vec.h
- Add m0_bufvec_cursor_{cmp,prefix}()
functions. They will be needed for
prefix compressed keys in b-tree.
- Factor out common code iterating
over bufvec fragments.
- Add randomised unit-tests for bufvec.
=> lib/vec.[ch]: add new bufvec functions.

addb2/addb2.c, addb2/ut/base.c
Problem: addb2 traces sometimes contain more
POP-s than PUSH-es. m0_addb2_cursor_next() fails
with -EPROTO in this case.
Analysis: mach_buffer() limits the amonut of
space used by sensors in a new buffer.
Erroneously, when skipping sensors, this
function also skips corresponding context
PUSH-es, thus creating an invalid buffer.
Solution: fix mach_buffer() to always PUSH all
context labels in a new buffer.
This patch also introduces trace_invariant()
invariant (marked expensive) to check validity
of a trace buffer.
This patch also regularises trace buffer opcodes
to simplify and speed up tracing (gets rid of
non-standard ranged switch-case labels).
Testing: with trace_invariant() enabled, but
without fix to mach_buffer(), existing
UTs fail immediately. No additional tests are
necessary. …
=> EOS-2040: fix context stack underflow in traces.

motr/m0d.c, st/m0d-signal-test.sh
- This was introduced by:
commit a1a5e630aa5105ccbbfdca36964a7b69a8f7c3d7
EOS-13872 motr: don't start clients before motr IOS process starts functional (#146)
- Get the journalctl cursor before starting motr service.
=> EOS-15083 reset 'rc' after overwritten.

balloc/balloc.c, be/btree.c, be/btree.h, stob/io.c
The usage of m0_be_btree_cursor_*() API at m0_balloc_load_extents()
without any external locking on btree may lead to panics:
```
ERROR  [balloc/balloc.c:1312:m0_balloc_load_extents]  Invalid extent
FATAL  [lib/assert.c:48:m0_panic]  panic: (0) at m0_balloc_load_extents() (balloc/balloc.c:1313)  [git: cortx1.0-rc1-15-g1611636]
m0_panic (ctx) at lib/assert.c:50
m0_balloc_load_extents (cb, grp) at balloc/balloc.c:1313
balloc_regular_allocator (bac) at balloc/balloc.c:2335
balloc_allocate_internal (req, tx, ctx) at balloc/balloc.c:2488
balloc_alloc (ballroom, tx, count, out, alloc_zone) at balloc/balloc.c:2678
stob_ad_balloc (adom, adom, alloc_type, out, count=256, tx) at stob/ad.c:1058
stob_ad_write_prepare (map, src, adom, io) at stob/ad.c:1846
stob_ad_io_launch_prepare (io) at …
```
=> EOS-8362: fix sporadic panics at m0_balloc_load_extents()

balloc/balloc.c, configure.ac
In recent commit a1b061a8b the regression was introduced into balloc_alloc_db_update() which zeroes maxchunk attribute of the group if there is only one fragment available for allocation from it. This corrupts internal balloc groups structures making it impossible to allocate from them while there is still plenty of space available.
Solution: fix maxchunk update at balloc_alloc_db_update() by reverting the relevant changes from commit a1b061a.
=> balloc: fix regression in balloc_alloc_db_update()

hsm/m0hsm_api.c
```
hsm/m0hsm_api.c:71:0: error: "DEBUG" redefined [-Werror]
#define DEBUG(_fmt, ...) if (options.trace_level >= LOG_DEBUG) \
^
```
Soulution: rename DEBUG() macro to DBG() in m0hsm_api.c.
Signed-off-by: Andriy Tkachuk <andriy.tkachuk@seagate.com>
=> hsm: fix compilation issue with --enable-debug

be/tool/beck.c
Issue: Mutex fini called before thread fini. If thread has not completed
work yet then got the panic mutex is in use.
Fix: m0_mutex_fini called after the m0_thread_fini
=> EOS-15263 beck: correct the sequence of m0_mutex_fini and m0_thread_fini

doc/Quick-Start-Guide.rst
sudo is not needed for m0 make/rebuild commands.
=> doc/Quick-Start-Guide.rst: drop sudo at m0 make

scripts/install/usr/libexec/cortx-motr/motr-free-space-monitor
Current libmotr api "m0_iem()" is generalize for all IEM alerts from motr.
Which is not allowing to change format of free space monitor alert message as
required, hence added print log (instead of api) to provide alert in required format.
Keeping exiting logic as well (commented) as it may required in LDR-R2
=> EOS-15338 motr-free-space-monitor: changed IEM alert message format 

scripts/provisioning/roles/lustre-client/tasks/main.yml
The current Lustre version we support (2.12.5) does not work on CentOS-7.9 (which is used by Vagrant now when provisioning the nodes), so the provisioning is broken at the moment (unless some older version of CentOS is specified explicitly via the M0_VM_BOX_VERSION parameter).
Solution: update our list of supported Lustre versions up to 2.12.6.
=> provisioning: update Lustre version to 2.12.6

README.rst
Adding link to motr in prose from top-level readme
=> Linking to motr in prose

be/tool/beck.c
btree_node_pre_is_valid() has check (node->bt_num_active_key <
ARRAY_SIZE(node->bt_kv_arr)).
This check used to fail when node->bt_num_active_key = 255 i.e. when all KV
entries were full. This leads to treating KV entries as bad.
The end user result was some of the objects written before recovery were
missing, even when there was no error injection.
=> EOS-15686 be/tool/beck: fix bnode pre-validation check in beck tool.

scripts/provisioning/roles/lustre-client/tasks/main.yml
Currently on vmware_desktop-provider-based nodes there is
only one network interface configured. But in lnet config
at /etc/modprobe.d/lnet.conf there would be two interfaces
added after provisioning and, as result, lnet would not
add any of them (`lctl list_nids` wouldn't show anything)
and Motr processes startup would fail.
Solution: check virtualisation provider when configuring
interfaces in lnet.conf at lustre-client/tasks/main.yml
and use eth0 (NAT) interface in case of VMware provider.
Signed-off-by: Andriy Tkachuk <andriy.tkachuk@seagate.com>
=> provisioning: fix interfaces at lnet.conf on vmware

motr/io.c, pool/pool.c, pool/pool_foms.c, pool/pool_machine.c
Build failed with code coverage flag enabled:
sh autogen.sh; ./configure --enable-coverage; make
=> EOS-15316 code coverage: removed compile time error with coverage flag

scripts/install/usr/libexec/cortx-motr/motr-free-space-monitor
Updated IEM alert message to "Storage usage has reached 70% of the capacity and
may run out of space soon. Contact Seagate support to extend storage capacity"
from "Usable storage is 70 % full", which is more descriptive than earlier one.
=> EOS-15519 motr-free-space-monitor: Updated IEM alert message 

scripts/provisioning/roles/lustre-client/tasks/main.yml
The regression was introduced at commit b0d129e77 when
we started checking for vmware when configuring lnet.conf.
The problem is that we check for the 'facter_virtual' but
facter is not installed by the time when the lustre-client
ansible task if performed. facter utility is installed
later during motr-runtime task.
Solution: check for 'ansible_virtualization_type' variable
instead of 'facter_virtual'. 'ansible_virtualization_type'
is internal to ansible and is independent of facter.
=> Vagrantfile: fix lustre-client provisioning

scripts/provisioning/Vagrantfile
Currently, version 8 is used (set by default by Vagrant) which limits the virtual machines to 8 CPUs and 8 GB RAM.
Solution: set version 10 explicitly in Vagrantfile. Version 10 allows to create machines with 16 CPUs and 64 GB RAM.
=> Vagrantfile: set vmware hw.version to 10

doc/dev/dtm/recovery-stop-condition.txt
Two variants of the stop condition on the sender side are proposed: with "is_last" field and with a separate REDO complete packet.
=> More details on a sender side.

ha/ham-st, ha/ham.c
- 06ham st got stuck while test "Both Send" because,
many times server process exit before client process
complete connection.
- wait time option added for listening mode. So, process
will wait before finilize server connection.
=> EOS-13057 ha: wait time added in ham utility for listening mode

configure.ac, cortx-motr.spec.in, motr/init.c, scripts/provisioning/roles/motr-build/tasks/main.yml
Motr code can be compiled with libfabric using option --enable-libfab to use default version downloaded, compiled and installed using ./scripts/install-build-deps and custom libfabric build  can be used using option --with-libfab=path.
if these options (--enable-libfab, --with-libfab) are not provided then motr code will be compiled without libfabric transport  
Signed-off-by: Jaydeep Mohite <jaydeep.mohite@seagate.com>
=> EOS-16191 Libfabric: Use libfabric source code to build libfabric library for compiling motr code with libfabric transport

configure.ac, dix/req.c, dix/ut/client_ut.c
=> EOS-16485: support zero-spare configuration in DIX

bindings/go/mio/mio.go
The 64bit layout id consists of 2 parts: the layout type and the id itself. The layout type is not zero for the composite objects, so M0_OBJ_LAYOUT_ID() macro must be used to get the id part.
=> go/mio: fix getting the composite objs layout id

motr/composite_layout.c
cext_tlists and cexts arrays allocated at composite_io_divide() were not freed.
The code is refactored a bit also to improve its readability.
=> hsm: fix memleak at composite_io_divide()

bindings/go/mio/mio.go
Currently, m0_obj_op() is not re-entrant for the composite objects (because it checks and allocates `obj->ob_layout`).
Solution: call m0_obj_op() from the main thread only.
The patch allows to run multi-threads i/o on the composite objects:
```
19:47 tkachuk1@datawarp-01:mcp$ ./mcp -prof 0x7000000000000001:0x4e9 -hax 172.18.1.33@o2ib:12345:1:1 -ep 172.18.1.33@o2ib:12345:4:1 -proc 0x7200000000000001:0x376 -v -threads 8 /tmp/1GB 0x1122113:0x11221002
2021/01/20 19:49:24 mio.go:490: W: off=0 len=33554432 bs=4194304 gs=2097152 speed=82 (Mbytes/sec)
2021/01/20 19:49:25 mio.go:490: W: off=33554432 len=33554432 bs=4194304 gs=2097152 speed=88 (Mbytes/sec)
2021/01/20 19:49:25 mio.go:490: W: off=67108864 len=33554432 bs=4194304 gs=2097152 speed=88 (Mbytes/sec)
2021/01/20 19:49:26 mio.go:490: W: …
```
=> go/mio: fix multi-threads i/o on composite objects

bindings/go/README.md
Update update `mio` to `go/mio` to avoid clashes with another mio package for Motr (another client API) developed by Sining Wu (@siningwuseagate) for Maestro project.
=> go/README: update mio -> go/mio

README.rst
Currently, it states that Motr can run on any version of Linux, which is not true.
Solution: fix the sentence by pointing out that Motr can be easily ported to any version of Linux.
=> README: fix portability information

bindings/go/README.md, bindings/go/mcp/mcp.go
Add `-off` option to start i/o on the Motr object from/at the specified offset.
=> mcp: add -off offset option

motr/composite_layout.c
Consider the composite object with several extents:
```
m0hsm> show 0x1122113:0x11221005
- gen 2, tier 1, extents:  (writable)
- gen 1, tier 2, extents: [0->0x3fffffff]
- gen 0, tier 3, extents: [0->0x1ffffffff]
```
1st extent (newer, gen 1) is 1 GB, 2nd extent (older, gen 0) 8 GB.
Writing to the older extent with offset > 1 GB would panic:
```
$ mcp -prof 0x7000000000000001:0x4e9 -hax 172.18.1.33@o2ib:12345:1:1 -ep 172.18.1.33@o2ib:12345:4:1 -proc 0x7200000000000001:0x376 -v -bsz 128 -threads 32 -osz $((2*1024*1024)) 0x1122113:0x11221005 /dev/null
2021/01/21 16:34:39 mio.go:547: R: off=0 len=134217728 bs=4194304 gs=2097152 speed=790 (Mbytes/sec)
2021/01/21 16:34:39 mio.go:547: R: off=134217728 len=134217728 bs=4194304 gs=2097152 speed=1000 (Mbytes/sec)
2021/01/21 16:34:39 mio.go:547: R: …
```
=> hsm: fix write at offset on older extent

dtm0/Kbuild.sub, dtm0/Makefile.sub, dtm0/clk_src.h, dtm0/tx_desc.c, dtm0/tx_desc.h
Transaction descriptor is an on-wire/on-disk
structure used to propagate DTM0-related
information accoss the network (rpc) and to preserve
it across reboots (be).
The tx_desc module defines the corresponding
data types and associated functions.
=> EOS-16866: [DTM0] Introduce tx_desc.

be/dtm0_log.h
With https://github.com/Seagate/cortx-motr/pull/365, common tx descriptor structure has been moved to tx_desc.h and hence removed from dtm0_log.h file and cleanup whatever was required.
=> EOS-16459: [DTM0] Updated log header to cleanup common structure

scripts/provisioning/README.md, scripts/provisioning/build-prep-1node.sh
Add an example about starting a single-node Motr cluster.
-----
[View rendered scripts/provisioning/README.md](https://github.com/Seagate/cortx-motr/blob/andriytk-patch-1/scripts/provisioning/README.md)
=> provisioning/README: add single-node example

doc/Quick-Start-Guide.rst, scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py, scripts/install/opt/seagate/cortx/motr/bin/motr_setup, scripts/install/opt/seagate/cortx/motr/libexec/motr_cfg.sh
- EOS-16363
- lnet sanity test added for multinode cluster
- lvm creation improved, so not fail if volume group exist
- general error handling of motr_setup commands
- motr_cfg.sh fixed to run without m0provision and salt
- always return 0 on success
- failure will retun with error code and traceback
=> provisioner: multinode motr provisioner support added

dix/req.c, dtm0/Makefile.sub, dtm0/conf.cg, dtm0/fop.c, dtm0/helper.c, dtm0/helper.h, dtm0/service.c, dtm0/ut/main.c, fop/fom_generic.c, lib/trace.h, motr/ut/dix_conf.cg, motr/ut/idx_dix.c
[DTM0]: Add dtm0 connections.
The patch updates the ping-pong test
(it turns it into "ping-pong-pong-poing" test).
Also, it introduces a test template for m0client
operations and connects dtm0 services together.
=> [DTM0] Add dtm0 service connections

scripts/provisioning/build-prep-1node.sh
It's still required that the user have sudo privileges to run the script though.
=> build-prep-1node.sh: improve to use by non-root users

motr/m0crate/crate_io.c
Currently, it shows "Deleting" instead of "Opening" in the log:
```
trace: [1612444701:441610295] t01: Creating objects...
trace: [1612444705:817830062] t01: Creation done.
trace: [1612444705:817873262] t01: Deleting objects... !!! <- here
trace: [1612444706:726894586] t01: Deletion done.      !!!
trace: [1612444706:726942709] t01: Writing objects...
trace: [1612444712:624709872] t01: Write done.
trace: [1612444712:624737930] t01: Deleting objects...
trace: [1612444715:353146688] t01: Deletion done.
```
Solution: fix the logging at cr_op_namei().
=> m0crate: fix operations logging

be/Makefile.sub, be/dtm0_log.c, be/dtm0_log.h, be/ut/Makefile.sub, be/ut/dtm0_log_ut.c, dtm0/tx_desc.c, dtm0/tx_desc.h, ut/m0ut.c
Implemented following APIs and supporting APIs needed for that as well as UT to ensure implementation is working as expected.
Also have added modification to DLD as per discussion and changes done in this PR.
1. m0_be_dtm0_log_init
2. m0_be_dtm0_log_fini
3. m0_be_dtm0_log_create
4. m0_be_dtm0_log_destroy
5. m0_be_dtm0_log_find
6. m0_be_dtm0_log_update
7. m0_be_dtm0_log_prune
$ sudo ./utils/m0run   -- "m0ut -t dtm0-log-ut"
dtm0-log-ut
dtm0-log-list                                   0.00 sec    4 KiB
[ time: 0.00 sec, mem: 4 KiB, leaked: 0 B ]
Time: 0.00 sec, Mem: 4 KiB, Leaked: 0 B, Asserts: 11
Unit tests status: SUCCESS
utime 0.229253 stime 0.077094 maxrss 55640 nvcsw 1388 nivcsw 13
minflt 13468 majflt 2 inblock 0 oublock 65544
rchar 95429 wchar 1083 syscr 202 syscw 42
read_bytes 0 …
=> EOS-16459: [DTM0] Implement DTM0 local non-persistent log structure for originators

cas/cas.h, cas/client.c, cas/service.c, dix/client.c, dix/client.h, dix/req.c, dtm/dtm.h, dtm0/Kbuild.sub, dtm0/Makefile.sub, dtm0/dtx.c, dtm0/dtx.h, dtm0/fop.c, dtm0/fop.h, dtm0/service.c, dtm0/service.h, motr/client_init.c, motr/client_internal.h, motr/idx.c, motr/idx_dix.c, motr/ut/idx_dix.c
The patch introduces DTX into DIX and
the related modules (motr client, dix/cas
requests and so on).
The patch has an update version of the UT
where m0 client sends a kv pair. When
DTM0 is enabled (--enable-dtm0), DTX module
sets the TX record. The transaction id of this
record is printed on the receiver side.
=> EOS-16866: [DTM0] DIX with DTX.

scripts/install/opt/seagate/cortx/motr/libexec/motr_data_recovery.sh
Issue:
While checking status of motr-kernel service on remote node,
the command for checking status were executing on local node shell.
Fix:
Used escape "\\" char while passing command to remote node to ignore the
special meaning for symbol "`".
Signed-off-by: Kanchan Chaudhari kanchan.chaudhari@seagate.com
=> EOS-17153: data recovery orchastration failed with motr-kernel service is not starting on remote node

motr/idx.c
Problem: When "--enable-dtm0" is not passed
the client code compilation fails.
Solution: Wrap the unused variabe with the DTM0
feature flag.
The fix addressed the compilation issue caused by landing of https://github.com/Seagate/cortx-motr/pull/412
=> Fix m0c compilation without DTM0 enabled.

cas/client.c, cas/service.c, dtm0/dtm0.h, dtm0/fop.c, dtm0/fop.h, dtm0/tx_desc.c, dtm0/tx_desc.h, dtm0/ut/main.c, ut/m0ut.c
Added dtm0 fop request, reply structures, operation and message types,
markers in code where dtm0 operation related credit calculation should
be performed and dtm0 log routines should be called for the basic case
of executing a dtm0 request.
Also added DLD for dtm0 service.
Signed-off-by: Mehul Manharlal Joshi <mehul.joshi@seagate.com>
=> EOS-16179:[DTM0]

bindings/go/mio/mio.go
This will allow the dynamic linker to find libmotr.so
in runtime also. No need to set LD_LIBRARY_PATH now.
=> go/mio: add -Wl,-rpath option for libmotr.so

scripts/install/opt/seagate/cortx/motr/libexec/motr_data_recovery.sh
Added license header to motr_data_recovery.sh file.
Signed-off-by: Kanchan Chaudhari kanchan.chaudhari@seagate.com
=> EOS-18284: add license header to motr_data_recovery.sh file

addb2/global.c, fop/fom.c
Problem: It's been found that ADDB stob doesn't contain
IO path records on a node with 96 CPU cores. ADDB2 queue overflow
message was observed during debugging.
Solution: Global ADDB2 system's queue size has been increased.
FOM ADDB2 system's queue size has been scaled up to the number
of CPU cores.
=> EOS-16937: ADDB stob doesn't contain IO path records

doc/Quick-Start-Guide.rst
Drop mentioning the explicit kernel version and CentOS version and mentioning
that different kernel versions are supported at the same time - it's very confusing.
Just mention CentOS-7 version for x86_64 platform and ARM64 platform porting
work in progress.
Fix typo in mentioning EPEL repo and put the exact command about how to install it
instead of pointing to the document which is about to be deleted.
=> Quick-Start-Guide.rst: fix Prerequisites section

be/Kbuild.sub, be/dtm0_log.c, be/dtm0_log.h, dix/req.c, dtm0/dtx.c, dtm0/dtx.h, dtm0/service.c, dtm0/service.h, dtm0/tx_desc.c, dtm0/tx_desc.h, motr/idx.c, motr/idx.h, motr/idx_dix.c, motr/ut/idx.c, motr/ut/idx_dix.c
The patch extends m0c and dix code to propagate
the Executed ("E" in the title) state from CAS request
to DTX, and it separtes the "completed" machinery (asts, callbacks)
into separate "executed" and "stable" on the m0c side.
Note1: the patch has a few TODO/XXX comments for the reviewers.
Some of them may need to be resolved before considering
this patch for merging.
Note2: the patch was tested with "--enable-dtm0" only.
It needs to be verified with "--disable-dtm0".
=> EOS-17417: [DTM0] Propagate E state for DTX.

motr/client_internal.h, motr/pg.h
It should be m0_op_io::ioo_ext field.
=> Fix m0_op_io::ioo_ivec field name in comments

dtm0/service.c, dtm0/service.h, dtm0/ut/main.c, motr/ut/idx_dix.c, pool/pool.c
A new event-based connections mechanism is introduced.
Each node subscribes on state changes of process objects
with DTM0 service in confd to establish the connection
to DTM0 service when remote process becomes ONLINE.
NOTE: currently there is a logic to make a workaround
for current HA implementation: skip processing of all
HA messages until TRANSIENT is received. TRANSIENT is
just a trigger for handling HA messages in this case.
=> EOS-17584 dtm0: implement initial version of all2all connections

dtm0/it/all2all/all2all, dtm0/it/all2all/test.yaml, motr/st/utils/ha_msg_send.sh
This integration test involves Hare and Motr. The test
checks that after a specific sequence of HA messages
all processes are connected with each other.
As current implementation of Hare does not support
required protocol then some HA messages are sent by
a special script.
Test steps:
- check that Hare is installed;
- initialise loop (storage) devices;
- bootstrap the cluster using Hare;
- check m0traces that no HA messages are handled;
- send a trigger HA message "TRANSIENT" to activate
HA messages handling by DTM0 services;
- check m0traces;
- send "ONLINE" HA messages to trigger connection
procedures;
- check m0traces that connection procedures completed;
- cleanup loop devices.
=> EOS-17642: implement an integration test for all2all connections

be/dtm0_log.c, be/dtm0_log.h, be/ut/dtm0_log_ut.c, cas/service.c, dtm0/clk_src.c, dtm0/clk_src.h, dtm0/doc/dtx.txt, dtm0/dtx.c, dtm0/dtx.h, dtm0/fop.c, dtm0/fop.h, dtm0/service.c, dtm0/service.h, dtm0/tx_desc.c, dtm0/tx_desc.h, dtm0/ut/clk_src_ut.c, motr/idx_dix.c, motr/ut/dix_conf.cg, motr/ut/idx_dix.c, utils/trace/m0trace
The patch aimed at PERSISTENT (P) notice mechanism
implementation for the happy-path scenario.
P notice is sent by the server side when the corresponding
CAS operation gets comitted, and it is beign handled
by the log through the ast mechanism.
The patch also incudes several minor improvements
for DTM0 traces and fixes for the configuration
of the Motr client UT to enable proper communication
between the DTM0 services on the client and the server
sides of the UT.
=> EOS-17630: [DTM0] Handle P notice on the client.

dtm0/it/all2all/all2all, utils/m0setup
Now all process FIDs, ids and endpoints are retrieved using
hctl status command. Also various number of m0ds supported.
=> EOS-18758 dtm0: extend all2all w.r.t. different hare and cluster configs

motr/m0crate/crate.c, motr/m0crate/crate_client.h, motr/m0crate/crate_index.c, motr/m0crate/parser.c, motr/m0crate/scripts/README.md, motr/m0crate/scripts/gen_index_yaml_run_workload, motr/m0crate/scripts/m0crate-index.yaml.template, motr/m0crate/tests/test1.yaml, motr/m0crate/tests/test2.yaml, motr/m0crate/tests/test3.yaml, motr/m0crate/tests/test4.yaml, motr/m0crate/tests/test5.yaml, motr/m0crate/tests/test6.yaml
There are improvement areas such as,
```
Correctness in output logs (for all log levels) of m0crate KV test run.
a. Following parameters are not being used by m0crate kv test but still displayed in the output logs.
Before Fix:
info: average size:          65536
info: maximal size:          1048576
info: block size:            0
After Fix:
No need to display this if KV test run is running.
b. Following parameter shows wrong output.
Before Fix:
info: number of operations:  1000 (OP_COUT: 32 was passed. always shows the same value.). 
After Fix:
info: number of operations:  32
c. If we read following output it looks like percentage of ops but its actually 
count of number of operations remaining. 
Before Fix:
trace: dix: prcnt: [5, 4, 0, 0]		
After Fix: 
trace: dix: ops remaining: [5, 4, 0, …
```
=> m0crate kv(index) test fixes.

Makefile.am, sns/Makefile.sub, sns/parity_defs.h, sns/parity_math.c, sns/parity_math.h, sns/parity_ops.h
- Implemented isal_diff() function to calculate differential parity.
- Added MACRO to check if ISA-L code is enabled or not.
- Use Galois library only in kernel space.
=> EOS-18137 sns/parity_math: implement isal_diff() function

motr/ut/idx_dix.c
Problem: the DTM0-related client-side UT has only
one test with a single PUT operation. We need
to verify more cases including DEL operation,
multi-op cases and wait-on-exec-only tests.
Solution: add the tests required.
The test was verified with the following command:
./utils/m0run -d -- m0ut -t
idx-dix-mt:dtm0,idx-dix-mt:dtm0_putdel,idx-dix-mt:dtm0_e_then_s
=> EOS-18627: Add more UTs for happy-path.

cas/service.c, dtm0/fop.c, dtm0/fop.h, dtm0/ut/main.c
Added code to serialize and deserialize an m0_cas_op for storing into the payload of a dtm0 logrecord.
Added changes to dtm0-ut to exercise and verify the code change.
=> Dtm0 m0_cas_op serialization and deserialization 

m0t1fs/linux_kernel/file.c, motr/io_pargrp.c, sns/cm/repair/xform.c, sns/parity_math.c, sns/parity_math.h, sns/ut/parity_math_ut.c
- Added Reed Solomon code under Macro RS_ENCODE_ENABLED.
- Created empty function fail_idx_isal_recover(). Added assert in it as
this functionality is not implemented for Reed Solomon as well.
- In function m0_sns_cm_repair_cp_xform(), added M0_PARITY_CAL_ALGO_ISA
to check algo range.
- Removed debug messages.
=> EOS-18143 sns: Intel ISA misc changes

cas/service.c, fop/fom.c, fop/fom.h, fop/fom_generic.c
Problem: CAS FOM locality index is calculated as a hash of
catalogue FID.
During performance profiling it has been found that the same
locality index is assigned to FOM if the CAS FOPs contain
the same FID. For instance, typical S3 client performs
operations on a single S3 bucket, which lead to limited set of
indecies (meta-index and ordinary index related to S3 bucket).
In that case, assigned localities' runq and waitq queues get
overloaded, while other localities' queues are not populated
by incoming CAS FOPs. It increases CAS FOP processing latency.
Solution: Locality index is implemented using incremental
static counter. It's updated by +1 value each time cas_fom_home_locality()
function is called.
=> EOS-18604: Uniform distribution of CAS FOM locality index

dtm0/helper.c, dtm0/service.c
DTM0 Persistent log is not initialized properly
when the service starts. The patch addresses
that issue.
=> DTM0: Fix plog initialization.

motr/io_pargrp.c, motr/ut/io_pargrp.c
Simplify bufs allocations at pargrp_iomap_init() with help of new pargrp_iomap_bufs_alloc() and pargrp_iomap_bufs_free() routines.
=> client-io: simplify pargrp_iomap_init

doc/Quick-Start-Guide.rst
Signed-off-by: Patrick Hession <patrick.hession@seagate.com>
- The current guide does not make it clear enough that you can optionally do RPM generation or build from source.
- Specified that you should not do RPM generation if you have built from source.
- Tested on VMWare Workstation Pro 16
=> Clearing up optional builds

dtm0/Kbuild.sub, dtm0/it/all2all/README.md, dtm0/it/all2all/all2all, dtm0/it/all2all/cdf.yaml, dtm0/it/all2all/hare.patch, dtm0/it/all2all/m0crate.yaml, motr/client_init.c, pool/pool.c
Now the m0crate is used to put key/val pairs with DTX
enabled to check that whole chain works.
Some workarounds are added to start the DTM0 service
on the client side and wait for connections from the
cluster nodes. Some fixes provided.
Also the patch for Hare with partial DTM0 support is
attached to have the ability to run the integration
test.
=> [DTM0] EOS-17644: add the client to all2all integration test

dtm0/it/all2all/README.md, dtm0/it/all2all/all2all, dtm0/it/all2all/m0crate.yaml.in
Now hctl status output is used to get cluster params
and set them in m0crate cfg file before running m0crate.
=> EOS-17644 dtm0: override m0crate cfg in all2all test

motr/m0crate/parser.c
When the MOTR_CONFIG section is missing in the configuration
file or it's named differently (for example MERO_CONFIG) -
m0crate just crashes with the following stack:
```
0  0x000000000040c05e in atoi (__nptr=0x223a0f0 "8") at /usr/include/stdlib.h:280
1  copy_value (load=0x2226010, max_workload=<optimized out>, index=0x7fff0f6bc524,
key=<optimized out>, value=<optimized out>) at motr/m0crate/parser.c:281
2  0x000000000040ccec in parse_yaml_file (load=load@entry=0x2226010, max_workload=max_workload@entry=32,
index=index@entry=0x7fff0f6bc524, config_file=<optimized out>) at motr/m0crate/parser.c:588
3  0x0000000000403eca in main (argc=3, argv=0x7fff0f6bc648) at motr/m0crate/crate.c:1345
```
Which is a bit confusing because the problem is actually at
frame 1 (not 0):
```
(gdb) f 1
1 …
```
=> m0crate: fix segv crash when MOTR_CONFIG is missing

file/file.c, ioservice/ut/bulkio_ut.c
Problem:
Configure the code with --enable-data-integrity flag and
compile it. bulk-server-ut:bulkio_server_single_read_write
starts failing with assert in file_checksum_check()
Root cause:
1. We have enabled following fault injection in bulkio_ut.c
m0_fi_enable("io_fop_di_prepare", "skip_di_for_ut");
2. Because of this fault injection, we skip adding checksum information
in io_fop_di_prepare()
3.Later in io_launch(), we try to verify the checksum.
But checksum was not added in first place. Thus our test
fails.
4. This test works without --enable-data-integrity
because when this flag is not set we do not do checksum check,
we call file_di_none_check() which does nothing.
But when ENABLE_DATA_INTEGRITY flag is set we call file_di_crc_check()
and does checksum check. This is the problem. …
=> EOS-18776: bulk-server-ut fails with --enable-data-integrity

dtm0/fop.c, dtm0/service.c, dtm0/ut/main.c, motr/client_init.c, motr/ut/idx_dix.c
[DTM0] EOS-19055: Fix DTM0 UT for m0 client.
The patch addresses the issue where the UT
used to test DTM0 with M0 client failed.
The root cause was the part where the client
starts the DTM0 service: the FID of the client
matches with the FID of the server, and because
of that the wrong DTM0 service FID was selected,
that led to the situation where the server-side
DTM0 service sends P messages to itself (rather
than to the client-side DTM0 service).
Also the patch alleviates the failures of the DTM0
service UT: it still fails but only at the point
of finalization (connections are not terminated
properly and rconf complaints about objects
that disappeared without proper notice).
DTM0: Remove event-driven connectivity in UT.
The patch fixes the problem where the DTM0 service
UT does not work …
=> [DTM0] EOS-19055: Fix DTM0 UTs (clnt and svc)

lib/misc.c, lib/types.h
Enhance m0_uint128_sscanf() to allow parsing the IDs specified in decimal and octal formats also. (Currently, it understands hex format only.)
=> lib: enhance m0_uint128_sscanf to allow dec/oct formats

rm/ut/rcredits.c
rm-rcredits-ut:debtor-death panics sometimes at debtor_death_acceptance_wait() when checking for the remote pointer which can be freed in another thread in parallel.
Solution: protect remote by taking it from the r_remotes list under the lock and taking the reference counter on it.
=> EOS-18808 fix panic on rm-rcredits-ut:debtor-death

cas/service.c, configure.ac, dix/req.c, dix/ut/client_ut.c, motr/client_init.c, motr/idx.c, motr/ut/idx_dix.c
The patch renames the DTM0 configure flag
into ENABLE_DTM0, sets this flag to zero when
"enable-dtm0" was not defined at the configure
step, and, finally, this patch converts
the DTM0-related pre-processor conditions into
runtime (rt in the title) conditions.
=> [DTM0] Use rt checks agains DTM0 configure flag.

sns/parity_math.c, sns/parity_math.h
- Updated functions m0_sns_ir_init(), m0_sns_ir_fini() and
m0_sns_ir_failure_register().
=> EOS-18140 sns/parity_math: implement incremental recovery using ISAL

lib/ut/vec.c, lib/vec.c, lib/vec.h, m0t1fs/linux_kernel/file.c, m0t1fs/linux_kernel/file_internal.h, m0t1fs/linux_kernel/ut/file.c, motr/client.h, motr/io_pargrp.c, motr/io_req.c, motr/pg.h, motr/ut/io_pargrp.c, motr/utils.c
Currently, pargrp_iomap_populate() might incorrectly determine
the RMW-mode if the segments in the user data index vector are
overlapping. The total size of the segments in this case may
be bigger than the parity group size and pargrp_iomap_populate()
would not set RMW-mode. But the segments are overlapping and the
data they collectively cover may not actually span the whole
parity group, in which case we do need RMW-mode.
Solution: fix & simplify pargrp_iomap_populate() by using new
m0_ivec_cursor_conti() function which returns the last index of
contiguous segments starting from cursor position up to the given
position. Comparing the result of this function with the parity
group boundary we can check reliably if the user data in the
index vector spans the whole parity group.
We can also …
=> client-io: fix & simplify pargrp_iomap_populate

m0t1fs/linux_kernel/file.c, m0t1fs/linux_kernel/ut/file.c, motr/io.h, motr/io_nw_xfer.c, motr/io_pargrp.c, motr/pg.h, motr/ut/io.c, motr/ut/io_pargrp.c, motr/utils.c
Get rid of clobbering code in the client-io, like data_row_nr(),
data_col_nr(), parity_col_nr() and parity_row_nr(). These are
just wrappers which rather confuse and clobber the code rather
than clarify anything.
Introduce rows_nr() instead of data_row_nr() and parity_row_nr().
And use layout_n() and layout_k() directly instead of data_col_nr()
and parity_col_nr().
=> client-io: get rid of redundant code

doc/reading-list.md
"Motr" should start with a capital letter in texts.
-----
[View rendered doc/reading-list.md](https://github.com/Seagate/cortx-motr/blob/andriytk-patch-1/doc/reading-list.md)
=> Fix minor typo in text: motr -> Motr

motr/idx_dix.c
There is a race condition between the user
thread and the locality thread where
a motr client operation gets stabilized
and the dix_req is getting destroyed.
Here is the scheme:
```
User thread:
await on STABLE for op1
...
fini_entity(op1->entity) <- frees the entity
and poisons it.
Locality:
set op1 state to STABLE <- unblocks the "awaiting".
dix_req_destroy(op1->dix_req) <- enity is finalized already.
...
read op1->entity->id <- reads poisoned bytes.
```
The patch reorders the calls, so that the dix_req is getting
destroyed right before the state of the operation is changed
to "STABLE". In this case, we are always operating on a
valid entity structure inside the dix_req_destroy call.
=> [DTM0] Fix use-after-free in STABLE.

motr/idx_dix.c
The patch addresses a flaw in the original DTX
design where a client operation was marked as "EXECUTED"
when the corresponding dtx reached "EXECUTED" state.
With this patch applied, the operation reaches EXECUTED
state only after the dtx enters EXECUTED_ALL. In other
words, the client operation is executed when all
the CAS replies are received.
This change helps to enforce isolation of the operations:
once an dtx reached E_ALL state, another dependent dtx
can be submitted.
NOTE: The patch is a "band-aid" that helps to support the
isolation property. However, this change can lead to a significant
clean up of the DTX states and the DTX integration with the client:
the DTX.EXECUTED state could be removed and the connections
between DIX/CAS and DTX SMs could be re-wired. This could be …
=> [DTM0] EOS-19239: Move op to E state when E_ALL reached.

dtm0/service.c, motr/conf.c
The patch fixes the problem where m0d services
were failing because DTM0-related connections
were not properly finalized.
=> [DTM0] EOS-19130: Fix panic during disconnect.

lib/ub.c, sns/ut/parity_math_mt_ub.c, sns/ut/parity_math_ut.c, ut/m0ub.c
Add m0_parity_math_mt_ub as part of run-ub
- m0_parity_math_mt_ub is added in run-ub list to run multi-threaded
unit benchmarking.
- Improved m0_parity_math_mt_ub with more tests.
- Added functions to spoil failed units and compare the recovered units
with the original after recovery.
Add unit test for mixed failures
- Added unit test 'reed_solomon_recover_with_fail_vec_rand' to test
parity_math encode and recover functionality for mixed failures i.e.
failures in random data fragments as well as in parity fragments.
Unit benchmarking changes
- Updated results_print() function in ub.c to print results with correct
columns
=> EOS-18145 sns: update ub and ut for parity_math functions

m0t1fs/linux_kernel/file.c, motr/io_pargrp.c, sns/parity_defs.h, sns/parity_math.c, sns/parity_math.h, sns/parity_ops.c, sns/ut/parity_math_ut.c
- Updated functions m0_sns_ir_mat_compute() and m0_sns_ir_recover().
- Added new recover function for incremental recovery using Intel ISA.
- Updated unit test for direct_recover().
- Updated few more functions to log return value.
- Updated year in Copyright notice.
=> EOS-18854 sns/parity_math: implement incremental recovery using ISAL

conf/objs/service.c, dtm0/service.c
Due to an "if (COND) X; Y;"-like typo, the "cs_params"
field was finalized inside service_decode.
The patch addresses this issue. Also, it adds more
traces into the function that uses these arguments,
and it fixes some minor coding style-related issues
there.
=> [DTM0] Do not release cs_params at the wrong moment.

lib/user_space/timer.c, lib/ut/timer.c, motr/cob.c, net/bulk_emulation/mem_xprt_xo.c
Gentoo Linux has rolling updates and thus provides latest toolchain versions. This patchset contains of a subset of the patches required to build Motr on Gentoo system with latest software versions. It doesn't contain patches conflicting with #523 and should be treated as addition to that PR.
=> Fix build on Gentoo Linux

scripts/install/usr/lib/systemd/system/m0d@.service
EnvironmentFile is hardcoded at /etc/sysconfig directory
which is absent in Ubuntu/Debian, so the startup fails.
Solution: drop EnvironmentFile configuration, it's redundant
for m0d@.service. motr-server script which is used to startup
m0d service can automatically determine the location of the
environment files and use them.
=> scripts/systemd: fix m0d startup on Ubuntu

README.rst
Signed-off-by: Patrick Hession <patrick.hession@seagate.com>
Added a link to the Motr Performance Tuning Wiki page.
=> Added link to wiki page

bindings/go/go.mod, bindings/go/mcp/mcp.go
mcp: enabled go module (#466)
Signed-off-by: kiwi <gheewooi.ong@seagate.com>
-----
[View rendered bindings/go/README.md](https://github.com/kiwionly2/cortx-motr/blob/go1.16/bindings/go/README.md)
=> update Go binding code to enabled module so can work with Go version 1.16

doc/Quick-Start-Guide.rst
Drop needless stuff (it's a *quick* start guide after all),
fix formatting of the commands.
This should be landed after https://github.com/Seagate/cortx-motr/pull/656 fix.
=> doc: edit quick start guide

scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py, scripts/install/opt/seagate/cortx/motr/bin/motr_setup
On VM, MOTR_M0D_IOS_BESEG_SIZE is set to default size(128M) which leads
to panic during mem_alloc.
Solution: configure MOTR_M0D_IOS_BESEG_SIZE to the same size as minimum
of available metadata volume.
backtrace:
#5  btree_save (tree=tree@entry=0x400000123930,
tx=tx@entry=0x7f6d48011e68,
op=op@entry=0x7f6d667fb450, key=key@entry=0x7f6d667fb6c0,
val=val@entry=0x7f6d667fb6d0, anchor=anchor@entry=0x0,
optype=optype@entry=BTREE_SAVE_INSERT,
zonemask=zonemask@entry=2)
at be/btree.c:1454
#6  0x00007f6de9dbf298 in be_btree_insert
(tree=tree@entry=0x400000123930,
tx=tx@entry=0x7f6d48011e68, op=op@entry=0x7f6d667fb450,
key=key@entry=0x7f6d667fb6c0, val=val@entry=0x7f6d667fb6d0,
anchor=anchor@entry=0x0, zonemask=zonemask@entry=2) at
be/btree.c:1908
#7  0x00007f6de9dc02d8 in m0_be_btree_insert …
=> EOS-19147: crash in mem_alloc on VM when running 1 million object write

btree/btree.c
Changed the ut to use Big endian keys since the comparison within the btree 
code uses memcmp which will not give expected output while comparing 2 integer
values.
=> Changed btree ut to use Big endian Keys for expected comparison results.

lib/trace.h, rpc/conn.c, rpc/session.c, rpc/session_foms.c, sm/sm.c, sm/sm.h
A new instrumentation schema similar to ADDB2-based instrumentation
is introduced. This schema is based on m0traces. The reason for that
is failures testing when the latest portion of ADDB2 data may not be
flushed on disk so that the entities states before failure can not
be retrieved. Solution for that is to use m0traces as an
instrumentation tool as m0traces are flushed right before the crash.
Current implementation covers generic code of state machines,
connection and sessions.
With respect to perfortmance an addintional field is added to state
machine structure that enables/disables states transitions tracing.
Tracing is disabled by default.
For the states machines that correspond to connections and sessions
tracing is enabled. Also added local and node-to-node mappings for …
=> EOS-19921 dtm0: add m0trace instrumentation for connection and session

btree/btree.c
Updated put function for btree:
- Handled scenario if key already exist while insertion
- added changes to support different values for ksize and vsize
=> EOS-20316: Implement btree key-value operations kv-put

scripts/install/etc/sysconfig/motr, scripts/install/opt/seagate/cortx/motr/libexec/m0addb_logrotate.sh
* Generally we set MOTR_M0D_ADDB_STOB_DIR path in
/etc/sysconfig/motr from motr.conf for hardware deployment,
But for VM deployment we do not change sysconfig/motr params
and it leaves "MOTR_M0D_ADDB_STOB_DIR" parameter unset, that
restricts m0addb_logrotate.sh to cleanup addb logs from VM setups.
* Enabling logrotation for addb logs in VM as well by setting addb
log directory to default valuse "/var/motr/m0d-*"
=> EOS-20883: Enabled ADDB logs rotation for VM deployments as well

lib/user_space/uuuid.c, lib/uuid.c
Taking uuid from /etc/machine-id instead of /sys/module/m0tr/parameters/node_uuid.
=> EOS-20422: Remove the need for m0d to get UUID

motr/client.c, motr/client.h, motr/client_internal.h, motr/idx.c, motr/idx_dix.c, motr/obj.c, pool/pool.c, pool/pool.h
Added idx_pool_version_get() internal API to get index pool version
and layout type. It will be called when m0_entity_create() API is
triggered from consumers like s3, m0kv. It is applicable for create
index operation.
Added required changes to support pver and layout type which are
passed by S3. It is applicable for PUT, GET, NEXT and DEL KV operations
in md-path.
=> EOS-19810: avoidance of internal dix layout index lookups

cas/index_gc.c, cas/service.c, fdmi/fol_fdmi_src.c, fdmi/fol_fdmi_src.h, fdmi/source_dock.c, fdmi/source_dock.h, fdmi/source_dock_internal.h, fdmi/ut/filterc_ut.c, fdmi/ut/fol_ut.c, fdmi/ut/sd_apply_filter.c, fdmi/ut/sd_post_record.c, fdmi/ut/sd_send_not.c, fop/fom.c, fop/fom_generic.c, fop/fom_generic.h, ioservice/cob_foms.c
FDMI is a reliable transport by design, so there is no way for the
caller to handle M0_FDMI_SOURCE_POST_RECORD failure. The only
implementation that exists currently in fdmi/fol_fdmi_src always
returns 0. This patch shifts failure handing for
M0_FDMI_SOURCE_POST_RECORD() from the caller to FDMI source
implementations.
Signed-off-by: Maksym Medvied <max.medved@seagate.com>
=> EOS-20841 fdmi/source_dock: make M0_FDMI_SOURCE_POST_RECORD() void

dtm0/it/all2all/all2all, lib/trace.h, rpc/conn.c, rpc/session.c, rpc/session_foms.c, sm/sm.c
Improved m0traces instrumentation related to states logging,
connections and sessions relation.
Also added dumping of m0traces at the end of all2all test.
=> EOS-19916 dtm0: improve m0traces instrumentation

m0t1fs/linux_kernel/file.c, motr/io_pargrp.c, sns/cm/repair/xform.c, sns/parity_math.c, sns/parity_math.h, sns/ut/parity_math_mt_ub.c, sns/ut/parity_math_ut.c
- Updated functions m0_parity_math_calculate(), m0_parity_math_diff(),
m0_parity_math_recover(), m0_parity_math_fail_index_recover() and
m0_sns_ir_recover() to return error code in case of failures.
- Updated the callers of these functions to handle the returned error
codes.
=> EOS-17288: Return error code from parity math functions

bindings/go/mcp/mcp.go, bindings/go/mio/mio.go, bindings/go/mio/mkv.go, bindings/go/mkv/mkv.go
Add Vi settings to the Golang-source code files at the bottom.
=> go: add vi settings to the sources

configure.ac, cortx-motr.spec.in
- Added option --disable-isal to disable the use of Intel ISA library.
In this case, Galois library will be used.
- By default motr code will use Intel ISA library if it is present.
=> EOS-20988: Add option to enable or disable ISA library

be/btree.c, be/tool/beck.c, be/ut/btree.c
Reverting change from commit id fb19a784b900a73dfdb9fec45659b6c8b282644b which caused the btree truncate to fail in cases when the truncate record count would align with any of the btree node KV counts.
Changed the btree ut to catch similar conditions during truncate operation.
Added -m option to beck tool which will map the BE segment in the memory and wait in a while(1) loop if this option is provided. This is useful during debugging of core dumps.
=> Eos 21067 Reverting change from commit id fb19a7 which caused btree truncate failures in some cases.

sm/ut/sm.c, ut/m0ut.c
Changed the size of permissive_trans array from 256 elements to 225 elements to
make the ut run without crashing.
=> EOS-21226: Fixed ut/sm.c

bindings/go/mkv/mkv.go
Import mio as a module. See commit 09ff618 also.
Closes #762.
=> go/mkv: fix build with go-1.17

motr/io_nw_xfer.c
In case when target_ioreq_init() returns an error, the
target_ioreq is freed, but after this we still reference
to it, which might lead to panic.
Solution: return the error code immediately from
nw_xfer_tioreq_get() after freeing the target_ioreq.
=> client: fix panic at nw_xfer_tioreq_get()

motr/setup_dix.c
Added fix to handle spare is set as 0
=> EOS-21403: bootstrap is failed with 1+2+0 DIX pool version

ioservice/io_foms.c
Signed-off-by: Maksym Medvied <maksym.medvied@seagate.com>
=> ioservice/io_foms: use M0_DTX_INVALID instead of hardcoded 0

btree/btree.c
- Fixed the ut to pass correct key for get_key operation.
- Modified assert to handle multi-thread sceanrio
- Modified key counts for delete operation
=> Fix btree-ut:multi_thread_single_tree_kv_op.

motr/io_nw_xfer.c, motr/io_req_fop.c, motr/st/utils/motr_dgmode_io_st.sh, motr/st/utils/motr_st_inc.sh, pool/pool.c, pool/pool_machine.c
Degraded read for partially spanned parity groups is failing due to cobs are not created
and iofops are returning -ENOENT.
Updated the unit spanned logic to create cobs for all the units which are not spanned
by checking PA_WRITE flag, which was set during iomap creation.
Updated Dgmod ST with unit sizes larger than PAGE_SIZE, in which this case can be
reproduced.
=> Degraded read is failing for partially spanned parity groups 

motr/client.h, motr/client_internal.h, motr/cob.c, motr/obj.c, motr/st/utils/cat.c, motr/st/utils/client.c, motr/st/utils/helper.c, motr/st/utils/helper.h, scripts/install/opt/seagate/cortx/motr/libexec/m0addb_logrotate.sh
* During Read and Write(update) operation we do cob lookup to retrieve
pver from server, but if we could get pver from s3 itself while trying to
read object we can avoid cob lookup.
* Added required changes for the same, While creating object pver and LID will
be stored into object attributes (obj->ob_attr.oa_pver) and the same will be
returned by s3 while they try to read the object.
* Tried to simulate behavior on Motr side by setting pver (what is received in
create object) into m0_read() before proceeding for object read, These changes
from helper.c and debug logs will be removed from final patch.
=> EOS-19418: Skip cob lookup, upon receiving pver from s3

btree/btree.c
In multithread UT, there was deadlock between node lock and tree lock.
Moved active node descriptor list to global scope to avoid deadlock.
=> EOS-21221: Move active nd list from tree descriptor to global scope.

btree/btree.c
Issue: A thread was waiting to take tree lock at P_LOCKALL. In the meantime
another thread took lock, inserted records and changed height of the tree.
When thread one took tree lock, it found height is changed and returned to next
state without unlocking the tree.
Fix: Changed the P_LOCKALL and P_SETUP order for lockall case.
=> EOS-21221: Fix deadlock at P_LOCKALL state.

fop/fom.c, iscservice/isc.c, iscservice/isc_fops.h, lib/hash.c
Reverts Seagate/cortx-motr#808 which introduced too many test failures.
=> Revert "isc: fix foms hashing by localities"

btree/btree.c
Issue: Thread 1 is waiting to take global lock in node_get(). In the meantime
thread 2 deleted the same node. Thread 1 took lock and failed as the node is
deleted.
Fix: Add node validation in node_get(). If node validation fails, restart
respective tick function.
=> Add node validation check in node_get().

btree/btree.c
Fixed bug in P_ALLOC phase:
Freeing node which is allocated and not stored or used.
some other changes:
using oi->pivot for P_ALLOC phase instead of oi->i_used to avoid resetting of oi->i_used
=> Changes in P_ALLOC phase

btree/btree.c
- Added MACROS: COPY_RECORD, COPY_VALUE, INIT_REC_WITH_KV_INFO
- Changing lev->l_seq = lev->l_node->n_seq to lev->l_seq = oi->i_nop.no_node->n_seq
to avoid confusion
Signed-off-by: RadhaGulhane13 <radha.gulhane@seagate.com>
=> Changes in code to provide readability

iscservice/isc.c
Improve parallelism of computations by evenly distributing isc-foms among all the available localities.
Test results on my devvm with 4 CPUs:
1. Without the patch:
```
$ /usr/bin/time ./c0isc_demo max 123:12371 $((256*1024))
idx=8846249 val=32767.991000
1.21user 0.24system 0:10.57elapsed 13%CPU (0avgtext+0avgdata 126396maxresident)k
0inputs+32776outputs (2major+42331minor)pagefaults 0swaps
```
2. With the patch:
```
$ /usr/bin/time ./c0isc_demo max 123:12371 $((256*1024))
idx=8846249 val=32767.991000
1.26user 0.23system 0:06.39elapsed 23%CPU (0avgtext+0avgdata 126288maxresident)k
0inputs+32776outputs (2major+42426minor)pagefaults 0swaps
```
=> isc: improve parallelism of computations

rpc/ut/link_ut.c
This will give enough time for the async connection to complete before
timeout. Otherwise, the async connection will not succeed.
And then the UT will hung there waiting for the connection state to be
changed.
=> EOS-22610 Increase timeout value for async connection

scripts/install/opt/seagate/cortx/motr/libexec/m0addb_logrotate.sh
m0addb_logrotate.sh cleans up the old addb recored from the "MOTR_M0D_ADDB_STOB_DIR"
path specified in /etc/sysconfig/motr, but this path get sets during HW
deployment only. For VM we use default path /var/motr/m0d-*. This default path
was set at wrong place earlier, corrected it now.
=> m0addb logrotate: Corrected default path of addb record

bindings/go/mio/mkv.go
Check index fid provided by user to make sure it starts with `0x78`.
This should help to avoid issues like https://github.com/Seagate/cortx-motr/issues/826.
=> go/mkv: add check for index fid format

mdservice/ut/lustre.c, net/lnet/lnet_core.c
When compiling with gcc-9.3:
net/lnet/lnet_core.c:402:45: error: taking address of packed member of
'struct nlx_core_ep_addr' may result in an unaligned pointer value
[-Werror=address-of-packed-member]
402 |  rc = nlx_core_nidstr_decode(lcdom, nidstr, &cepa->cepa_nid);
|                                             ^~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
Solution: use local variable to get the nid value from nlx_core_nidstr_decode().
=> net/lnet: fix compilation with gcc-9.3

utils/m0singlenode
Issue: EOS-21987 : 52singlenode-sanity reports success on my VM despite
reporting failures
Fix: Added a NOTE saying motr-server-ha failure is expected.
=> EOS-21987: 52singlenode-sanity reports success on failure

motr/idx.h
Remove duplicate documentation because they are a copy-paste of comments from https://github.com/Seagate/cortx-motr/blob/main/motr/client.h#L368.
Instead, add a reference to motr/client.h.
Users can also find more detailed descriptions of the index K-V store in client.h
=> Update idx.h. Remove duplicate doc

be/alloc.h, btree/btree.c, btree/btree.h, btree/internal.h
Initial code is added for persisting btree in BE segment. The code adds a
define AVOID_BE_SEGMENT which if enabled continues to create btree in volatile
memory. Currently this #define is turned ON since the code to capture the btree
changes is not present in the btree functions causing the ut's to crash.
=> Initial code for BE segment support in new btree.

btree/btree.c
- Removed expensive invariant check from ut.
- Added expensive invariant check in insert and delete routine whenever there is modification in node.
- Performing expensive invariant check in node lock mode.
=> Expensive check changes

bindings/go/README.md
I'm using go 1.15.5 on CenOS 7.8.2003.
My `go env GOBIN` doesn't show any output.
My `go env GOPATH` points to `/home/cc/go` and I can find the `mcp` binary installed in `GOPATH/bin`.
Therefore update the README to help users locate their binary.
A similar issue was reported in #682
-----
[View rendered bindings/go/README.md](https://github.com/mengwanguc/cortx-motr/blob/patch-10/bindings/go/README.md)
=> Update go/mio README.md

btree/btree.c
- calling P_CAPTURE before P_FREENODE
- unlocking tree after node_free operation.
=> Eos 22550 : changes for capturing transactions for KV Delete operation.

utils/m0reportbug
In devvm, m0reportbug was only packing m0traces.* files from
/var/motr/ and /var/motr/m0d-* paths, and it was not picking
the files from subdirectories of /var/motr/
Added the code in m0reportbug script to find m0traces.* files
from the relevant paths
=> EOS-21940 Fix m0reportbug to work on devvm

btree/btree.c
This is the final PR. 
It includes following changes :
- calling node_fini separately than node_free.
- calling node_fini before P_CAPTURE and then calling P_FREENODE so that issue of freeing node_descriptor bfore node_capture will be resolved.
- Added node_lock at necessary places whenever we call node_isvalid()
=> Eos 22550 modified : changes for capturing transactions for KV Delete operation.

Kbuild.in, Makefile.am, m0t1fs/linux_kernel/file.c, m0t1fs/linux_kernel/st/common.sh.in, m0t1fs/linux_kernel/st/m0t1fs_dgmode_io.sh, m0t1fs/linux_kernel/st/m0t1fs_test.sh, motr/init.c, motr/io_pargrp.c, sns/parity_defs.h, sns/parity_math.c, sns/parity_math.h, sns/parity_ops.c, sns/parity_ops.h, sns/ut/Kbuild.sub, sns/ut/parity_math_ut.c, ut/linux_kernel/m0ut_main.c
- Removed Galois API function calls.
- The Reed Solomon algorithm implementation, which used Galois APIs, is
commented with #if 0 block, as other functions are already implemented
to use Intel ISA library for encoding, recovery, differential parity
calculation and incremental recovery functionalities
- Added structure fields related to old Reed Solomon algorithm
implementation to #if 0 block as new fields are used for Intel ISA
implementation.
- Updated ut file to use Intel ISA implementation.
- Removed parity_math_ut from kernel space.
- Removed Kbuild.sub file as no ut to be run in kernel space.
- Updated year in Copyright header for modified files.
=> EOS-22440: ISAL - remove galois function calls (Part 1)

Makefile.am, configure.ac, cortx-motr.spec.in, scripts/install-build-deps
- Removed option which disables the use of Intel ISA .
- If Intel ISA is not present, the compilation will stop with message to
install Intel ISA.
- Removed option from install-build-deps to skip installation of Intel
ISA.
- Added Intel ISA rpm as mandatory build time and run time dependency.
=> EOS-22449: Make Intel ISA mandatory (No fallback)

Makefile.am, fdmi/plugins/.gitignore, fdmi/plugins/Makefile.sub, fdmi/plugins/debug.c, fdmi/plugins/fdmi_app, fdmi/plugins/fdmi_sample_plugin.c, utils/.gitignore
FDMI sample app.
- python fdmi_app cleanup:
* a standard arguments parsing
* added possibility to pass fdmi_filter_id on start. If missed then config file is used
* handling errors of forked c-program with showing error code and error message
* cleanup with printfs - errors and messages go to stderr
* checking for missed json fields
* fixed python warnings and errors
- c-program fdmi_sample_plugin cleanup:
* fixed error handling and corrected mero client and service fini() in error cases
* removed copy-pasted useless code
* more info on what params are used for running
* fixed printing errors to stdout. Now they go to stderr since the python wrapper parses stdout we better
avoid printing debug and errors there
* header file cleanup, moved static vars to the c file
* fixed missed init for …
=> FDMI sample app

motr/setup.c
Issue: EOS-23180 motr panic while bootstrapping cluster
Fix: Repair zone is taking more percentage than Normal zone and
sometimes more than 100%. Changed repair zone safety coefficients
=> EOS-23180: motr panic while bootstrapping cluster

utils/spiel/m0spiel
The function should be service_init(), not spiel_service_init() in the example.
=> utils: fix help example in m0spiel

btree/btree.c
=> Return ENOENT error code if key not found in btree get operation.

fdmi/plugin_dock.c, fdmi/plugin_dock_fom.c, fdmi/plugins/fdmi_sample_plugin.c
* No need to add extra ref after fdmi record is already processed.
* proper shutdown of fdmi service on plugin app side.
=> No need to add extra ref after fdmi record is already processed.

doc/motr-developer-guide.md
Add In-Store Compute (aka Function Shipping) demo link to motr-developer-guide.md
-----
[View rendered doc/motr-developer-guide.md](https://github.com/Seagate/cortx-motr/blob/andriytk-patch-2/doc/motr-developer-guide.md)
=> doc: add isc/demo link to motr-developer-guide.md

be/tx_credit.c, btree/btree.c
With these changes the math routines used for credit calculations also account for callback credits.
=> Changes to credit calculation functions to include callback calculations

scripts/install/opt/seagate/cortx/motr/conf/support.yaml
The new format of support.yaml is:
support_bundle:
- "sh /opt/seagate/cortx/motr/libexec/m0reportbug-bundler"
=> EOS-23582: update the format of support.yaml file

doc/Quick-Start-Guide.rst, scripts/install-build-deps
Modified Quick-Start-Guide to handle "DistributionNotFound: ipaddress"
issue.
=> EOS-23124: Improve Troubleshooting section in Quick-Start-Guide

motr/idx.c
Client(s3server) will store the pool version and layout type if the  MO_ENF_META flag is set while index creation. Motr will store the pool version and layout type if the M0_ENF_META flag is not set while index creation.
As per initial design, we have to add M0_ENF_META flag in to object index flags. Later it was changed to entity flags to support MD and DATA path. It was found while re-analyzing small object performance.
Modified M0_ENF_META flag validation to improve small object performance.
=> EOS-22704: Re-Analyze small objects Read throughput with MD cache patch

fop/fom.c, fop/fom.h, lib/locality.c, lib/locality.h, lib/thread.c, lib/thread.h
After commit 4c27187 the spurious warnings started appearing:
[lib/locality.c:157:m0_locality_here]  thread migrated to another CPU core
The warnings were meant for the locality threads only, who are confined to a specific CPU cores. But they appear now for any thread created in Motr process.
Solution: add the warning code as a locality chore which runs once in 10 mins.
Also, set the initial value of tls_loci at m0_thread_trampoline() which is called from the new thread already, rather than at m0_thread_init() which is called from the parent-thread. As we use m0_processor_id_get() for the initial value, this seems to be more appropriate.
=> lib: fix bogus warnings about thread migration

cas/ctg_store.c, cas/ctg_store.h, cas/service.c, fdmi/fol_fdmi_src.c, fdmi/plugins/fdmi_plugin_st.sh
FDMI events for key/value del operation based on the idea of lookup
before the del and populating fdmi records with the key and value
after lookup.
- enable del op in fol_fdmi_src.c;
- allow ctg_op_tick_ret() not to set the next phase in some cases;
- added m0_ctg_lookup_del() that performs lookup before del and populates
passed buffer with the value of the deleted key. The value then is saved
in m0_cas_op that fully comes to the FDMI record and becomes available in
FDMI event and for filtering;
- fixes and cleanups in fdmi_plugin_st.sh that tests the new functionality.
=> FDMI events for key/value del operation

btree/btree.c
This ut will perform different operations (Put, Delete and Destroy Tree) and confirm the operation changes persist on the BE segment. To confirm the persistence we reload the BE segment and then confirm if the btree data on the BE segment is still the way we expect it to be.
=> Btree ut validate persistence across cluster restarts

scripts/install/usr/libexec/cortx-motr/motr-free-space-monitor
EOS-23898 : motr-freespace-monitor: Add a delay between retry if capacity_info
Problem : Hare may take sometime to retrieve capcacity info during
startup, if the capacity_info is not recieved, free space monitor would
timeout with error.
Solution: Add delay between retry, After 10 retries, if it still fails
than return failure.
Signed-off-by: Yeshpal Jain <yeshpal.jain@seagate.com>
=> EOS-23898 : motr-freespace-monitor: Add a delay between retry if capacity_info is 0

btree/btree.c
Removed obsolete ut's and also removed the #ifndef __KERNEL__ scattered 
throughout the code. There are some places where the __KERNEL__ defined check
is still present but it is only where we cannot avoid its absence.
=> Removed #ifndef __KERNEL__ wherever possible from btree.c file.

btree/btree.c
This changes are meant to enhance the invalid case of UT where we cannot open a tree after it is destroyed.
=> Check for invalid tree open

btree/btree.c, motr/init.c
With this change the btree module init and fini will get called similar to other
modules thus removing the need to call these explicitly in every ut.
=> Calling m0_btree_mod_init() from init subsystem.

btree/btree.c, btree/btree.h
Added functions m0_btree_put_credit2(), m0_btree_update_credit2() and
m0_btree_del_credit2(). These alternate functions are to be used when the btree
pointer is not available. The new alternate functions should never be used to
replace the original credit functions for performance reasons.
=> Added alternate credit calculator functions to be used in absence of btree.

btree/btree.c, btree/btree.h
Modify tree_create() and tree_open() to accept tree from the user and assigning it to bop.bo_arbor instead of allocating memory for bop.bo_arbor in tree_create()
=> Rectify tree ops

btree/btree.c
If the matching Key is found then slant will return it. Only if the matching
Key is NOT found then slant will return the next highest Key.
Changed m0_btree_del to accept NULL parameter as callback data.
Also some memory leaks are fixed which were found by running valgrind on the
btree ut's.
=> Changes to make slant return the matching key if found.

be/tool/beck.c, be/tool/main.c, btree/btree.c, btree/internal.h, cob/cob.c, cob/cob.h, cob/ns_iter.c, cob/ns_iter.h, cob/ut/cob.c, sns/cm/ag.c
With the changes in this commit the COB module now uses the new BTree. The
changes still need to be verified on a cluster, but with the code in this commit
all the COB ut's are working.
=> Integration of new BTree with the COB module of Motr.

.gitmodules, Kbuild.in, Makefile.am, bindings/go/mio/mio.go, bindings/go/mio/mkv.go, configure.ac, cortx-motr.spec.in, doc/faq.rst, doc/test-coverage, motr/examples/example1.c, motr/examples/example2.c, scripts/addb-py/chronometry/s3server_integration/s3srv_build_prepare, sns/parity_math.c, utils/spiel/setup.py
- Removed Galois code compilation.
- Removed Galois code entry as Motr sub-module.
- Removed remaining occurrences of Galois.
=> EOS-20623: Remove Galois code compilation and usage

net/test/ut/main.c, net/test/ut/network.c
Changes:
Added UT for verifying libfabric address format.
`<xprt>:<family>:<type>:<IP/FQDN>@<port>`
=> EOS-24326: add ut for address decode of libfab address format

ioservice/cob_foms.c, ioservice/io_foms.c, ioservice/ut/bulkio_ut.c, mdstore/mdstore.c, sns/cm/cm_utils.c, sns/cm/repair/ut/cm.c, sns/cm/storage.c
Since the new BTree does not yet support accepting comparison functions from
the BTree consumer the COB code needs to zero-out the Keys before inserting them
or searching for them in the btree or else the memcmp fails.
=> Fixes to COB BTree integration for running m0cp/m0cat.

btree/btree.c
Removed ut's which are not used.
Fixed ut basic_tree_op_icp which used to crash.
Added code to check for node validity when it is on BE segment.
- An issue is seen during initialization of balloc trees. Some incorrect data is
- seen on the root node of the btree when it is on BE segment.
-  An enhancement in the ut to check for node validity when the nodes
- are offline.
-  [Yes ] Coding conventions are followed and code is consistent
- [Yes ] Unit and System Tests are added
- [Yes ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [No ] Testing was performed with RPM
=> Clean up of btree ut's

dtm0/it/all2all/all2all, dtm0/it/helpers, dtm0/it/s3setup/README.md, dtm0/it/s3setup/cluster_yaml.patch, dtm0/it/s3setup/hare.patch, dtm0/it/s3setup/s3setup.sh
The script is implemented to minimize amount of manual work
to get the development s3 setup. The script is used on top
of the S3 setup made by 1Node deployment pipeline for CentOS7.9,
so it is required to run this pipeline before running the
script.
The steps done by the script:
- stop running cluster using Pacemaker
- backup configs
- clone, checkout dtm0 branch and build motr/hare
- dev-install motr/hare
- restore and patch configs
- OPTIONAL: bootstrap the cluster using hare
- OPTIONAL: run s3bench and gather addb2 data
Also there is an option to run the following cycle that may be
useful for debugging (works when the custom setup is ready):
bootstrap the cluster, run s3bench, stop the cluster, gather
addb2 data.
=> EOS-24489 dtm0: implement a script for s3 custom setup

motr/cob.c
Problem:
1. Handling of skip md cob lookup case was not handled properly in motr
code for DELETE opcode. Also we did not receive the M0_ENF_META flag
from S3 which was allowing us to send a cob lookup call to motr server
during delete_entity.But on server particular cob entry is not present
as we had skipped while creating object which we are trying to delete
now. This resulted in an ENOENT error from motr server.
2. There was one more problem that even though we skip md cob lookup in
case of object delete, it was also skipping data delete cob
(M0_IOSERVICE_COB_DELETE_OPCODE) as well, and because of that it was
not freeing up the disk space.
Solution:
1. Skipped md cob_lookup for entity_delete() operation if M0_ENF_META flag
is set by application.
2. second problem addressed by posting …
=> EOS-24831: Object deletion gives return code as ENOENT 

.xperior/testds/motr-single_tests.yaml, conf/objs/fdmi_filter.c, fdmi/plugins/fdmi_plugin_st.sh, fdmi/plugins/fdmi_sample_plugin.c, m0t1fs/linux_kernel/st/m0t1fs_common_inc.sh, scripts/st.d/67fdmi-plugin-multi-filters
Features included:
* FDMI_ENABLE_FILTERS to control if FDMI is enabled
* Explain the DIX_PARITY and DIX_SPARE when generating DIX conf
* Interactive mode for this ST.
* Switch for output as string or as hex. Useful when doing manual testing.
Add fdmi st into jenkins tests
-     If yes for above point, post link to the corresponding PR.
=> EOS-24863: FDMI Test scripts modified to have multiple FDMI filters

motr/init.c
Root cause : Reordering of the initialization sequence of transports
caused the issue. sock was put before lnet, because of this cas_client
in UT is trying to use very first transport(sock) while the server is
using the transport based on the endpoint format(lnet). That is why we
see ETIMEDOUT. Client cannot connect to server because they are using
different transport
Fix: Changed the transport order back to lnet first and then sock next
=> EOS-24883: cas-client  FAILED with -ETIMEOUT

scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
- Storage_node keys were expected for control_node while running fsm service
- fixed the values to fetch appropriate type matching its machine-id from conf store. 
=> Motr Provisioner integration issue resolved

lib/ut/uuid.c, lib/uuid.c
Updated code for parsering both uuidgen and /etc/machine-id formats
Signed-off-by: JugalPatil <jugal.patil@seagate.com>
=> Merge UUID patch from main to kubernetes branch.

conf/ha.h, dtm0/fop.c, ha/halon/interface.c, ha/note.c, ha/note.h, m0t1fs/linux_kernel/super.c, motr/client_init.c, motr/setup.c, pool/pool.c
- Added M0_NC_DTM_RECOVERING and corresponding
M0_CONF_HA_PROCESS_DTM_RECOVERED message.
- Added REDO FOP/FOM stubs.
- Added documentation and examples of the use of
M0_CONF_HA_PROCESS_DTM_RECOVERED message inside the
code of m0ds, mkfs, clients, hax.
- Based on pull/1052.
- jira: EOS-24483
Signed-off-by: Anatoliy Bilenko <anatoliy.bilenko@seagate.com>
To implement DTM recovery new motr process states and messages in hax ↔︎ motr process protocol need to be added. Motr process transits through the set of states, overall DTM recovery flow including M0_CONF_HA_PROCESS_* messages and corresponding broadcasting of HA state messages.
-  https://seagate-systems.atlassian.net/wiki/spaces/~770032066/pages/609880834/DTM+Basic+Recovery+HLD+draft
-  [X] Coding conventions are …
=> Added M0_NC_DTM_RECOVERING HA state DLD

be/io.h, be/io_sched.c
It was possible for the op, passed to m0_be_io_sched_add(), to become
DONE before sched lock is taken in be_io_sched_cb() because parent op
could become DONE before the child op M0_BTS_GC callback is called.
This situation led to failed invariant, assertion failures [1] or just
spinning in infinite loop in m0_list invariant due to a broken list [2].
The patch fixes the issue by moving the op (passed to
m0_be_io_sched_add()) to DONE only after finishing processing of the
corresponding m0_be_io.
The bug was discovered during EOS-25005 patch testing.
[1]
be-ut
io_sched  motr[15961]:  e4b0  FATAL  [lib/assert.c:50:m0_panic]  panic: (io->bio_ext.e_start == sched->bis_pos) at be_io_sched_cb() (be/io_sched.c:132)  [git: 2.0.0-307-37-gd35074f6-dirty] /w/var/m0ut/m0trace.15961
Motr panic: …
=> EOS-25109 be/io_sched: fix op done ordering bug

cortx-motr.spec.in
Fix packages dependencies in rpmbuild spec file on CentOS 8.3:
1) sysvinit-tools package is not available on CentOS 8 anymore;
2) python36-ply is named python3-ply on CentOS 8.
=> spec: fix rpm deps on CentOS 8

btree/btree.c, btree/btree.h, cob/cob.c, conf/db.c
Current implementation of m0_btree_destroy_credit() used the (m0_btree *)
parameter for getting the correct node-type needed to get the destroy credit
count. In some cases this tree pointer is not available at the code location
where the credit calculations are done. To cover these scenarioes the modified
m0_btree_destroy_credit() also takes m0_btree_type parameter which is used to
find out the node type needed for getting the correct credit count.
=> Changes to m0_btree_destroy_credit() for accepting m0_btree_type parameter

utils/functions
=> EOS-25295 : Fix invocation of m0_default_xprt in utils/functions.

btree/btree.c
=> EOS:25147 Removed __KERNEL__ around function m0_btree_truncate_credit.

btree/btree.c
- Convert m0_btreee_oimpl->i_level variable from dynamic to static.
-  Coding conventions are followed and code is consistent
- Unit and System Tests are added
=> EOS-25146: Make m0_btreee_oimpl->i_level variable static.

be/alloc.c, be/alloc.h, be/btree.c, be/linux_kernel/stubs.c, be/ut/alloc.c, motr/m0crate/btree_without_tx_seg.c
- Define BE allocator interface to allocate/free BE memory and also provide allocator chunk header size to the caller.
-  [ ] Coding conventions are followed and code is consistent -> Done
=> EOS-25421: Add APIs for aligning chunk header.

be/partition_table.c, be/partition_table.h
Added partition_table_create_init() API. This function creates a partition table and writes the partition table on the disk.
Again it will read the partition table from the disk and validate the partition table.
=> EOS-24531: Implementation partition_table_create_init() API

fdmi/filter.c, fdmi/plugins/fdmi_app, fdmi/source_dock.c, fdmi/source_dock_fom.c, fdmi/source_dock_internal.h, fdmi/ut/sd_send_not.c, rpc/conn_pool.c, rpc/conn_pool.h
When a Motr FDMI plguin app failed, the delivery of FDMI notification from source side
to plugin app side will STUCK there, and retrying several times, and eventually failed with timeout.
The fop replied callback is triggered with a failure. In this case, the rpc connection and session
from source side to plugin side is dead.
On FDMI source side, if FDMI notification fop is failed to send, we remove this RPC link from
the connection pool, and destroy it. The notification fop is released. Now, we post the FDMI record
again so it will be re-sent with a new RPC connection/session. We are using the asynchronously
interfaces to establish and destroy the RPC connection.
-  [x] Coding conventions are followed and code is …
=> EOS-24872 FDMI events delivering after failure plugin comes back

bindings/go/mio/mio.go, bindings/go/mio/mkv.go
Fix build after commit bc844a8 (ARM64 platform support) by including config.h file.
=> go/mio: fix build after arm64 port

btree/btree.c
=> Add the missing keycompare function call in btree_put_split_and_find().

motr/motr-pub.api, net/ip.c, net/ip.h, net/libfab/libfab.c
- During testing in K8s env it was observed that, sometimes, the DNS resolution fails for some FQDNs when all the containers are not in ready state.
-  Added a retry mechanism for DNS resolution. The retry will be done during connection establishment.
=> EOS-25789 : Add retry mechanism for DNS resolution in libfabric.

conf/rconfc_link_fom.c, cortx-motr.spec.in
Clean up the clink in rconfc_herd_link_fom_wait_on before clink initialization.
Signed-off-by: Vidyadhar Pinglikar <vidyadhar.pinglikar@seagate.com>
- In rconfc_link_fom_tick, if rconfc_herd_link_fom_wait_on is called in both initial states, (M0_RLF_INIT and M0_RLF_SESS_WAIT_IDLE) then in that case, sess->s_sm.sm_chan is getting initialized twice with link->cl_is_oneshot = false;
- Due to this clink is not getting deleted when signaled but is re-initialized subsequently again in M0_RLF_SESS_WAIT_IDLE where its tlink is also initialized; due this tlink verification assert is getting hit.
-  As a fix, Clink clean-up API is invoked every-time, its initialized in rconfc_herd_link_fom_wait_on.  
Checklist for …
=> EOS-24894: Clean up the clink in rconfc_herd_link_fom_wait_on 

cortx-motr.spec.in
During image creation, it applied m0provision config stage which modifies the sysconfig parameter during image creation which is not required, m0provision config was required for R1 to apply the changes when we update the RPM's, with R2 and LC we already have mini provisioner which does the same job this is a redundant and can lead to errors in some environement so better to remove it from rpm spec file to apply config changes.
=> EOS-25506: LC : remove m0provision config from rpm spec files

motr/setup.c
- If a long pathname is used for addb path then m0d crashes.
2021-11-08 14:57:40 cortx_setup [14]: ERROR [main] Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/cortx/setup/cortx_setup.py", line 127, in main
rc = command.process()
File "/usr/lib/python3.6/site-packages/cortx/setup/cortx_setup.py", line 117, in process
CortxProvisioner.cluster_bootstrap(self._args.cortx_conf, mock)
File "/usr/lib/python3.6/site-packages/cortx/provisioner/provisioner.py", line 202, in cluster_bootstrap
"%s phase for %s. %s", …
=> ADDB: setup addb path buffer size to 512 bytes to support long pathname

net/libfab/libfab.c, net/libfab/libfab_internal.h
Closes #1119.
Compilation with gcc-8 fails, see #1119 for details.
N/A
=> EOS-25297 : fix compilation errors with gcc-8 for libfabric

be/fmt.h, be/io.h, be/log.h, ha/link_fops.h, lib/bob.h, lib/ext.h, lib/time.h, lib/types.h
When compiling a C++ app with Motr API by gcc version 8.3,
there is a lot of warnings for string literals and macors:
/usr/include/motr/be/log.h:318:58: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
#define BL_F "(lg_current=%"PRIu64" lg_discarded=%"PRIu64" lg_free=%"PRIu64")"
^
Solution: add spaces between the literals and macros.
Closes #1216.
=> Fix C++ compiler warnings for public headers

Makefile.am, configure.ac, lib/atomic.h, lib/vec.h
Include config.h automatically where needed. This
will simplify life for Motr API users.
Closes #1212.
`motr/config.h` has to be included by Motr API user apps in addition to some motr headers - which is inconvenient.
Include `motr/config.h` automatically from public headers where required.
=> lib: include config.h automatically

fdmi/plugins/fdmi_app, fdmi/plugins/fdmi_plugin_st.sh
The existing FDMI plugin ST needs improvement for failure case testing.
Adding failure case testing in batch mode. (Previously only manually doing failure case test)
Doing more KV ops to show that client operations are stalled when FDMI plugin fails.
=> EOS-25890: FDMI plugin failure test in ST

utils/m0reportbug
=> EOS-25693-new: Support Bundle generation is not creating and collecting data for m0reportbug-traces. 

rpc/frmops.c, rpc/item.c, rpc/item_internal.h
Reverts Seagate/cortx-motr#980.
=> Revert "rpc: call ->rio_sent() unconditionally."

motr/st/utils/motr_rpc_cancel_test.sh, scripts/m0
Re-enable ST 49motr-rpc-cancel for libfabric as it is completely running in user-space.
-  Re-enable ST 49motr-rpc-cancel for libfabric as it is completely running in user-space.
=> EOS-26198: re-enable st 49motr-rpc-cancel for libfabric

configure.ac
To solve this issue, if motr/config.h does not exist
then create motr/config.h as a symlink to ../config.h
during configure.
=> EOS-26562: motr code fails to build if motr/config.h is not found.

motr/idx_dix.c
Incorrect check of M0_ENF_META flag in oi_flags
Analysis:
Actually M0_ENF_META flag is available in entity_flags. It is validated
with oi_flags. Need to modify M0_ENF_META flag validation.
Fix:
Modified M0_ENF_META flag validation for index creation.
=> EOS-26541: Incorrect check of M0_ENF_META flag in oi_flags field of struct m0_op_idx

doc/Quick-Start-Guide.rst, scripts/provisioning/roles/motr-build/tasks/main.yml
- In motr repo, `make rpms` fails with below error
`libfabric-devel is needed by cortx-motr-2.0.0-1_giteef39d9_3.10.0_1127.19.1.el7.x86_64`
- During installation of motr build dependencies, make and install local libfabric rpms instead of installing libfabric binaries.
- Update motr Quick Start Guide for libfabric un-installation steps for users who want to use lnet as the default transport for 
motr.
=> EOS-26104 : libfabric-devel is needed for 'make rpms' for motr.

be/linux_kernel/stubs.c, dtm0/drlink.c, dtm0/drlink.h, dtm0/fop.c, dtm0/fop.h, dtm0/linux_kernel/stubs.c, dtm0/service.h, dtm0/ut/Makefile.sub, dtm0/ut/drlink.c, dtm0/ut/helper.c, dtm0/ut/helper.h, dtm0/ut/main.c
The UT is called dtm0-ut:drlink-simple.
The patch also introduces m0_ut_dtm0_helper to simplify rpc server and
client startup/shutdown for DTM0 UTs.
Signed-off-by: Maksym Medvied <maksym.medvied@seagate.com>
=> EOS-22462 dtm0/ut/drlink: send DTM0 messages from server to client

net/libfab/libfab.c
Reset the buf->fb_bulk_op to NULL in libfab_buf_fini().
- Motr ioservice crashed during `libfab_buf_fini()`.
-  For a network buffer, `libfab_buf_fini()` is called before generation of buffer completion event and from the same event callback it is called again during buffer deregister. This leads to motr service crashing due to invalid contents in the `buf->fb_bulk_op` during the first call to `libfab_buf_fini()`. Hence explicitly setting this field to NULL after freeing the memory in the first call to `libfab_buf_fini()` to avoid accessing memory which is already freed.
Checklist …
=> EOS-25581 : main/551: m0d panic at m0_tlist_remove after m0_tlist_del

bindings/go/mio/mio.go
The problem is with getOptimalBlockSz(): sometimes, it may
return the size which is bigger than amount of parity groups
spanned by the object. For example, with 1+0+0 EC configuration,
unit size of 4M and object size of 9485447 bytes, it will
return 16MB bs - which is more than 3 parity groups spanned
by the object (4 * 3 == 12MB).
Solution: fix the logic of getOptimalBlockSz(), so that it
would never return the size bigger than the size of all parity
groups spanned by the object. (The size of a parity group
meant here is measured by the size of all data units in it.)
=> go/mio: fix bogus ENOENT error on read

scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
If Metadata disk size is not 4k aligned value, mini provisioner fails with the below motr panic.
Motr panic: (m0_is_aligned(g->sg_size, M0_BE_SEG_PAGE_SIZE)) at be_seg_hdr_create() be/seg.c:108
Align BESEG size ot the nearest 4K size,
for ex : if metadata device is 5000, it will be set to 4096.
=> EOS-26638: Align metadata size to nearest 4k size

fdmi/plugins/fdmi_app, fdmi/plugins/fdmi_plugin_st.sh
Store FDMI in persistent storage (kafka)
When the `fdmi_app` gets FDMI events from plugin, it decodes event from json string.
It checks duplication. (FDMI events are saved temporarily in a queue in memory).
* If this is a duplicated event, just send record ID back to plugin's stdin. When plugin gets
this record ID, it will release this record by calling FDMI API.
* If this is a new event, 
- it will be inserted into the in-memory queue. (Later duplicated events come,
they will be de-duplicated) 
- **And then we will send it to kafka asynchronously.** (Using KafkaProducer)
Asynchronous way has better performance. We add callbacks for success and failure.
- On success callback, we send ACK to plugin.
The above is the happy path.
For failure …
=> Store FDMI events in kafka.

ioservice/ut/bulkio_ut.c, stob/ad.c
Problem :
In some cases, after deleting the object, entire space used by object
is not reclaimed.
Root cause:
This issues is observed in some cases where we do not write a complete
parity group in one IO request. Following happens in 3+2 config (an example)
1.Write 1 M at offset 0 - space consumed is 3M (1M for data and 2 M for parity)
2.Write 2 M at offset 1048576 - space consumed is 4M (2M for data and 2 M for parity)
Total space consumed is 7M, after unlink space reclaimed is 5M. Leak of 2M.
This leak is because of parity units.
In step 2, a memory leak happens.
We do not deallocated the space consumed by parity units because of step 1 and
we reallocate space for the parity units again.
Because of this leak we are not able to reclaim space even after object delete.
Memory leak happens …
=> EOS-25302 After delete, storage is not reclaimed completely.

motr/io_req_fop.c
Signed-off-by: Shipra Gupta <shipra.gupta@seagate.com>
s3server service failing intermittently while executing s3 tests.
1.There was an assumption taken in code that m0_ivec_cursor_move returns false after reaching end of cursor. This assumption is wrong and generated defect.  Changed the code as per correct return value of  m0_ivec_cursor_move. 
2. rep_ivec may contain very less data and it may not be eligible to fetch checksums. In this case simply return, do not assert.
3. Use the correct unit size to move the cursors.
Tested the fix for different IO sizes on 3 node cluster setup.
Sanity tests performed.
=> EOS-24933: s3server service failing intermittently while executing s3 tests.

motr/ut/idx_dix.c
The DTM0 service is required for REDO UT. So this UT should not
be executed if DTM0 is disabled.
=> EOS-26618 dtm0: skip execution of REDO UT if DTM0 is disabled

btree/btree.c
Issue: The allocated memory was not page aligned. It resulted into madvise
returning INVALID error code.
Fix: Added fix to allocate page aligned memory.
The allocated memory was not page aligned. It resulted into madvise
returning INVALID error code.
=> EOS-26278: Fix btree-persistence ut failure.

.xperior/testds/motr-single_tests.yaml, scripts/m0
- 23spiel-dix-repair* STs were disabled for libfabric. 
-  Re-enabled below STs as those are executed successfully even for libfabric
> 23spiel-dix-repair
23spiel-dix-repair-quiesce
=> EOS-26774: re-enable 23spiel-dix-repair* for libfabric

btree/btree.c
UT to test the CRC support in new BTree. The ut code runs different threads with each thread working on separate btrees and each btree supporting different key size, value size and also crc type.
=> EOS-26309: Btree ut to test crc

btree/btree.c, cas/ctg_store.c
- Bug fixes for reading objects after cluster reboot
-  Fixing node capturing: capturing the entire directory for variable key variable value node format
=> bug fixes for reading objects after cluster reboot

lib/misc.c, lib/types.h
Currently, if any of the u64 values is bigger than LLONG_MAX, say, `0x8f9381cfacb7576a` - m0_uint128_sscanf() returns just LLONG_MAX for it (`0x7fffffffffffffff`), which is, obviously, wrong.
Solution: fix m0_uint128_sscanf() in such a way that if any of the u64 values are resulted in LLONG_MAX - it will try to scan the numbers in unsigned hex format.
Also, make 0x prefix for hex format optional. If 0x prefix is not specified, decimal format is tried. If it fails to
parse the values, hex format is tried then. This way we try our best to parse the numbers in various formats.
Relates to https://github.com/Seagate/cortx-motr/pull/486.
Checklist for …
=> lib: fix m0_uint128_sscanf() for large values

motr/client.h
The documentation of `M0_ENF_META` flag in Motr client API is not very clear. Especially, on when the flag should be used and why.
Clarify and extend the `M0_ENF_META` flag usage documentation.
=> client.h: clarify M0_ENF_META usage doc

btree/btree.c
Earlier, internal nodes for fixed format were refering to value
size provided by user. Therefore, making changes to use 8 bytes
as value size for internal nodes.
=> vsize changes for internal fixed format node

scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py, scripts/install/opt/seagate/cortx/motr/bin/motr_setup
- add 'data_node' and 'storage_node' as valid node types for F99C integration.
-  Changes for separate s3 pod
-  Coding conventions are followed and code is consistent
-  Test Cases cover Happy Path, Non-Happy Path and Scalability
-  Testing was performed with RPM
- https://jts.seagate.com/browse/EOS-25904
Signed-off-by: Jugal Patil <jugal.patil@seagate.com>
=> [EOS-25904] support 'data_node' or 'storage_node' as node type

motr/io_nw_xfer.c
In degraded read ti_goff_ivec not cleared after operations
Memory leak shall happen during degraded read
=> EOS-27025: Memory leak during Degraded Read operation

ut/m0kut
Parsing of uuid was failing for uuid of length 36 updated m0_uuid_parse to parse uuid of length 36 and 32.
Signed-off-by: Jugal Patil <jugal.patil@seagate.com>
- UUID parsing failing for klibm0-ut
-  update lib/uuid.c/m0_uuid_parse to parse uuid of length 36 and 32.
-  Coding conventions are followed and code is consistent
- kernel ut is now passing details in JIRA EOS-27101
- https://jts.seagate.com/browse/EOS-27101
=> [EOS_27101] UUID parsing failing for klibm0-ut

motr/client_internal.h, motr/io.c, motr/io_req.c, motr/io_req_fop.c
- Checksum verification is failing in degraded I/O path and in read verify mode, because we don't send checksums for parity, so 
the checksums are not recreated for the missing data unit in degraded I/O path, so checksum verify function fails and returns IO ERORR (EIO)
Disable checksum verification check for degraded I/O and if read verify is enabled. 
-----
[View rendered .github/pull_request_template.md](https://github.com/yatin-mahajan/cortx-motr-1/blob/EOS-24233/.github/pull_request_template.md)
[View rendered bindings/go/README.md](https://github.com/yatin-mahajan/cortx-motr-1/blob/EOS-24233/bindings/ …
=> EOS 24233: Disable checksum verification for degraded read and read verify

motr/ut/io_nw_xfer.c, utils/m0singlenode
- Allocate ti_goff_ivec in UT testcase before free call
- m0singlenode update default xprt fetch function
=> EOS-27125:  Errors in UT io-nw-xfer-ut and m0singlenode script

btree/btree.c
btree embedded CRC implementation for Variable key value sized node format
=> Eos 23642  : btree embedded CRC implementation for Variable key value sized node format

ha/ham-st, ha/ham.c, rpc/it/rpc_ping.c, utils/functions, utils/spiel/m0spiel
Changes:
Updated following ST files to use transport specific address format
02rpcping
06conf
06ham
07m0d-fatal
07mount
07mount-multiple
08spiel
08spiel-multiple-confd
24stob-domain-recreate-on-corruption
=> EOS-26965: Update ST files to use the transport specific address format.

scripts/install/opt/seagate/cortx/motr/sanity/motr_sanity.sh, scripts/install/usr/libexec/cortx-motr/motr-service.functions
Update ST-52motr-singlenode-sanity files to use the transport specific address format.
-  Use the below format when using lnet as the transport.
`<ip>@<tcp/o2ib>:12345:<portal id>:<tmid>`
-  Use the below format when using libfabric as the transport.
`<inet>:<tcp>:<fqdn/ip>@<port>`
=> EOS-25942 : Update ST-52motr-singlenode-sanity files to use the transport specific address format.

doc/Quick-Start-Guide.rst, scripts/install-build-deps, scripts/provisioning/roles/base-os/tasks/main.yml, scripts/provisioning/roles/base-os/vars/RedHat.yml, scripts/provisioning/roles/lustre-client/tasks/main.yml, scripts/provisioning/roles/motr-build/tasks/main.yml, scripts/provisioning/roles/motr-build/vars/RedHat.yml, scripts/provisioning/roles/motr-runtime/tasks/main.yml
On vanilla CentOS provisioning, there are a number of different issues.
- install pip3 at install-build-deps
- enable el8 PowerTools repo
- drop python3-plumbum from el8_pkgs
- install yum-utils
- ignore failure on enabling powertools
- install lustre build deps 2 times
- extend supported lustre versions
=> scripts: fix vanilla OS provisioning issues

scripts/build-prep-1node.sh
It's not easy to build and prepare everything for the 1st single-node cluster startup.
`build-prep-1node.sh` is a convenience script that clones, builds, and prepares everything for the 1st single-node cluster startup (including [Hare](https://github.com/Seagate/cortx-hare)). It also downloads and installs all the needed dependencies automatically.
=> scripts: add build-prep-1node.sh

dix/req.c
In case of degraded cluster getting failure for some of the put request which goes
to failed node and because of that whole index put failed even though we other put
requests are successful. Which actually fails bucket creation and multipart upload in
degraded mode.
Returns success from motr client for dix put request even we got success from single
request out of N request and report failure only if all the put requests are failed.
UT is not added in this PR, Separate Jira [EOS-27333](https://jts.seagate.com/browse/EOS-27333) is created to add UT.
=> EOS-27288: CAS request should succeed even one put request is success

be/domain.h, motr/conf.c, motr/setup.c, motr/setup_internal.h, stob/partition.c
Enable partition stob based on different configuration 
1. Single Data specified(confd) No meta specified per cvg or same meta n data disc specified:
Part Stob:  
- seg0 - Max (1MB , chunk size)
- seg1 - 10% of total
- log  - Max(128M, chunk size)  //TODO:
- data - remaining
2. Single Data specified(confd) : Meta  specified (cmdline)
Part Stob:  
- seg0 - Max (1MB , chunk size)
- seg1 - remaining
- log  - Max(128M, chunk size)  //TODO:
3. Single Data specified(confd) : Meta specified (cmdline): Log specified (cmdline)
-  partition stob not needed
4. Multiple Data specified (confd) : meta specified
- seg0 - Max (1MB , chunk size)
- seg1 - remaining
- log  - Max(128M, chunk size)  //TODO:
5. Multiple Data specified (confd) : No meta specified 
no parition stob  
-  [ ] …
=> EOS-27115: Enable partition stob based on different configuration

net/libfab/libfab.c
In libfab_buf_dom_dereg(), call fi_close() only for the used segments of network buffer.
- Motr confd service crashed due to invalid memory access of unused variable arising due to suspected bit-rot of in-memory data structure.
- This can be handled in the libfabric code in the following way.
In libfab_buf_dom_dereg(), call fi_close() only for the used segments of network buffer.
This will prevent the service from crashing, but the root cause of the issue could not analyzed from the core dump.
Also this will be an optimized way of deregistering the buffer segments and hence it avoids unnecessary access of unused variables.
Checklist for …
=> EOS-25895 : stable/115: m0panic at fi_close after libfab_buf_dom_dereg

doc/motr-developer-guide.md
Add Ceph RGW Motr SAL implementation to Motr client API examples list at Motr Developers Guide.
-----
[View rendered doc/motr-developer-guide.md](https://github.com/andriytk/cortx-motr/blob/add-motr-sal-example-mdg/doc/motr-developer-guide.md)
=> doc: add Ceph RGW Motr SAL to examples at MDG

helpers/ufid.h
There is minor issue in the usage examples of m0_ufid_next() and m0_ufid_new() functions - the 1st argument is wrong.
Fix the doc.
=> helpers: fix minor doc issues at ufid.h

lib/user_space/processor.c, scripts/provisioning/roles/lustre-client/tasks/main.yml, scripts/provisioning/roles/motr-build/tasks/main.yml, scripts/provisioning/roles/motr-build/vars/RedHat.yml
`install-build-deps` script fails on arm64 platform.
Fix it by avoiding hardcoding the `x86_64` architecture in ansible provisioning scripts, and using `ansible_architecture` variable instead.
=> install-build-deps: fix for arm64 platform

scripts/build-prep-1node-cortx-mgw.sh, scripts/build-prep-1node.sh, scripts/install-build-deps
With `--no-ansible` option it would still install
ansible. And when it installs it (even without the option)
it would not make sure epel repo is installed and updated.
This is a regression introduced at commit 86d2c997f.
Fix it by introducing the old ansible logic back.
=> install-build-deps: fix no-ansible option

utils/m0reportbug
./deploy-scripts/k8_cortx_cloud/logs-cortx-cloud.sh does not
contains m0reportbug-traces.tar.gz.
*problem: Motr Support Bundle generated from container other than cortx-motr-io-001
and cortx-motr-io-002 does not contains m0reportbug-traces.tar.gz.
*Solution: Get M0TR_M0D_TRACE_DIR value from /etc/cortx/motr/sysconfig//motr instead of
/etc/sysconfig/motr.
=> EOS-27562: Motr Support Bundle generated by the script

scripts/build-prep-1node-cortx-mgw.sh, scripts/install-build-deps
When "scripts/install-build-deps --no-ansible" is used which calls
'yum-build-deps cortx-motr.spec', which may fail to find
lustre devel packages. This causes exit of the other build-prep*.sh
scripts.
To fix this issue install only user mode packages with --no-ansible.
=> scripts/install-build-deps: support only user mode for --no-ansible

scripts/install-build-deps
fix rpm-build package installation, as due to presence of rpm-build-libs
it was getting skipped.
Also use "yum-build-deps -y", so that no manual intervention is needed.
=> scripts: install the packages without manual intervention

Kbuild.in, doc/fault-injection.md, m0t1fs/linux_kernel/st/m0t1fs_common_inc.sh, m0t1fs/linux_kernel/st/m0t1fs_rlock_revoke.sh, m0t1fs/linux_kernel/st/m0t1fs_test.sh, scripts/install/usr/libexec/cortx-motr/motr-service.functions, utils/functions
As m0ctl uses debugfs, which supports only GPL licensed modules,
use of m0ctl for kernel tests is removed and build of m0ctl
kernel module too is removed.
Fix for motr build failure in RL 8.x in kernel mode, https://github.com/Seagate/cortx-motr/issues/1384
-----
[View rendered doc/fault-injection.md](https://github.com/Seagate/cortx-motr/blob/remove-m0ctl-module/doc/fault-injection.md)
=> EOS-27532 m0ctl: removed support for m0ctl kernel module

reqh/reqh.c
While generating confguration, Hare assigns metadata device to CAS
service type, M0_CST_CAS. But m0_reqh_mdpool_service_index_to_session()
expects it to be M0_CST_IOS and asserts the same.
Solution:
Expect metadata device service type to be M0_CST_CAS instead
of M0_CST_IOS.
Signed-off-by: Mandar Sawant <mandar.sawant@seagate.com>
=> reqh: md device service type is not M0_CST_IOS

cortx-motr.spec.in, scripts/build-prep-1node-cortx-mgw.sh, scripts/install-build-deps
Currently "any" suffix in usermode only rpm name represents that
it can work with any kernel version. Use of "any" suffix is not a
standard practice for rpm name, without it too same can be represented,
so removing it.
Also enabled powertools repo for quick package installation option.
Added python3-devel as dependency in cortx-motr.spec.
Fixed echo statement in build prepare scripts for MGW deployment.
=> spec: drop "any" suffix for user mode only motr rpm name

reqh/reqh.c
Reverts Seagate/cortx-motr#1388
=> Revert "reqh: md device service type is not M0_CST_IOS"

btree/btree.c, lib/user_space/user_x86_64_atomic.h
Solution:
Make variable "thread_run" volatile.
Make variable struct m0_atomic64::long a_value volatile.
- "btree-ut" hang when code is compiled without "--enable-debug" flag
=> EOS-28430 btree: btree-ut hangs when code compiled without --enable-debug flag

be/extmap.c, scripts/install/etc/sysconfig/motr
The documentations for `m0_be_emap_paste()` have some diagrams which have tabs and are broken in different editors.
Use spaces instead of tabs.
The tiny fix in the comment at `scripts/install/etc/sysconfig/motr` appeared to fix https://jts.seagate.com/browse/EOS-28468 issue with mini-provisioner also.
=> be: fix doc cosmetics for m0_be_emap_paste()

balloc/balloc.h
Bug Fixes for memory limit support
Objective: Bug Fixes for memory limit support
Description: With the following values of LRU list watermarks,
low=6MB, target=9MB, high=12MB
We hit the lru_list_purge() functionality but soon we get a crash related to balloc.
Setup: 1 Node K8s
ssc-vm-g4-rhev4-0170.colo.seagate.com
=> EOS-27820: Memory limit functionality crashing with lower watermarks.

configure.ac
Fix compilation issue for kernel module when '--enable-debug' is set to true.
[Refer this](https://gcc.gnu.org/bugzilla//show_bug.cgi?id=84187#c3)
=> EOS-28457 : GITHUB ISSUE-Kernel module compilation fails with --enable-debug

net/libfab/libfab.c
Use updated ip of restarted service in libfab_conn_init() instead of stale value.
- After pod restart, when the connection is being re-established, the dst is getting updated/calculated wrongly in libfab_conn_init().
Generally after pod restart IP's are changed and libfab_conn_init is still referring to older IP even though the dns resolution correctly returned the new ip.
-  Use updated ip of restarted service in libfab_conn_init() instead of stale value.
=> EOS-27537 : Services for the pod which is restarted are going in offline state.

btree/btree.c
Some performance block observed due to use of expensive_invariant.
=> EOS-27813: Updating the M0_ASSERT to M0_ASSERT_EX for expensive_invariant

spiel/cmd.c, spiel/spiel.h, spiel/ut/spiel_ci_ut.c, sss/process_foms.c, sss/process_fops.c, sss/process_fops.h
Added an API m0_spiel_proc_counters_fetch() which sends sss process fops
using spiel interface and retrives bytecount data from ioservice's cob btree.
=> EOS-27039: Added spiel API to fetch bytecount from ioservice

dix/ut/client_ut.c
Motr CI: failure seen in dix-client-ut while running local_failures test
Analysis:
As per new change (PR# 1363), Consider DIX request to be successful if there is at least
one successful CAS request. Before DIX request to be failed if there is at least
one failed CAS request.
Fix:
Two cas requests can be sent successfully, So local-failures UT will get reply code
as 0.
=> EOS-27572: Motr CI: failure seen in dix-client-ut while running local failures test

fdmi/fol_fdmi_src.c, fdmi/source_dock_fom.c, fdmi/source_dock_internal.h, fdmi/ut/fol_ut.c
FDMI records are posted regardless any FDMI filters are defined.
When starting FDMI service, check if any FDMI filter is defined.
If no FDMI filters are defined in configuration, we will skip posting FDMI records.
=> EOS-27717: Don't post FDMI records if no FDMI filters defined.

dix/ut/client_ut.c
Problem:
This UT introduces failure in one of the cas request and expect failure in generic response, But now as part of
f2ba0d107310b2a795e6c3818b7fb4fa454eb10a (for degraded write) we return generic response as success
even though one of N CAS request is successful. This is causing panic in UT as expected failure is not received.
Solution:
Change this UT as per new behavior, Introduce failure in all the CAS put requests  and expect failure in response.
This UT introduces failure in one of the cas request and expect failure in generic response, But now as part of
f2ba0d107310b2a795e6c3818b7fb4fa454eb10a (for degraded write) we return generic response as success
even though one of N CAS request is successful. This is causing panic …
=> EOS-28836: dix-client-ut:server-is-down with panic

fdmi/ut/fol_ut.c
At the end of this UT, we need to manually reset src_dock->fsdc_filters_defined.
Otherwise in the following UT, ASSERT failure happens.
=> reset src_dock->fsdc_filters_defined manually in the end of UT

addb2/sys.c, cas/client.c, conf/cache.c, conf/helpers.c, configure.ac, ha/link.c, layout/linear_enum.c, lib/locality.c, motr/st/layout.c, rm/rm_fops.c, rpc/link.c
In commit 46047958a `-O0` gcc option was changed to `-O2` for debug mode build of the kernel module to fix some compilation issues, but it will generate the code which would be hard to debug, defeating the purpose of the debug mode build.
Use special `-Og` option, which allows building kernel code and yet generates debug-friendly code.
Read more about `-Og` at https://lwn.net/Articles/756616/.
=> configure: fix --enable-debug for kernel module

be/extmap.c, btree/btree.c, cob/cob.c, conf/db.c
- Cursor returns addresses of key and value. In the old btree , as keys and values are present outside the node, these addresses returned by the cursor will not change but in the new btree as keys and values are present inside the node, addresses key and value can change if there is any update operation on the node. This issue was found during the m0unlink testing. Therefore, while using the cursor in the new btree, It is required to copy the required key and value in a callback which will be done by m0_btree_get and m0_btree_iter functions.
- 
Checklist …
=> E0S-28545 : Replace cursor calls with get and iter routines

bindings/go/README.md, bindings/go/go.mod, bindings/go/mcp/mcp.go, bindings/go/mkv/mkv.go
Currently, it's not possible to use motr go bindings outside of motr sources.
Update module name to `cortx-motr/bindings/go`. This allows to use:
import github.com/Seagate/cortx-motr/bindings/go/mio
in external go apps.
=> go: update module name to cortx-motr/bindings/go

cas/ctg_store.c, cas/m0ctgdump-howto.md, cas/st/ctgdump_tesh.sh, m0t1fs/linux_kernel/st/m0t1fs_common_inc.sh
The test script can be run in 2 modes:
(1) Test mode: ./ctgdump_test.sh test
Motr services are started with parity group setting (N == K).
An index is created and key/values pairs are inserted.
All CTG stores of the index are dumped and compared.
(2) Compare mode:
./ctgdump_test.sh comp be_stob_path cas_ep proc_fid index_fid
This mode only dumps and compares all CTG stores of the spcified index.
example: ./ctgdump_tesh.sh comp /var/motr/systest-766208/ libfab:172.16.179.134@tcp:12345:33:900 0x7200000000000001:0 7800000000012345:12345
Signed-off-by: Sining Wu <sining.wu@seagate.com>
-  [ ] Coding conventions are followed and …
=> CORTX-27592 add a test script for m0ctgdump

cas/client.c, dix/req.c, motr/idx_dix.c, motr/ut/idx_dix.c
Validate the UT for M0_OIF_SKIP_LAYOUT when enabled forcefully
Added two UT's to validate for M0_OIF_SKIP_LAYOUT.
1. ut_dix_namei_ops_dist_oi_flags - Index operations
2. ut_dix_record_ops_dist_oi_flags - Record operations
=> EOS-28602: Validate the UT for M0_OIF_SKIP_LAYOUT when enabled forcefully

conf/cache.c
The compilation of kernel module on CentOS 7.9 with gcc-4.8 fails with --enable-debug configure option:
conf/cache.c:226:31: error: ‘obj’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
FID_P(&obj->co_id), obj->co_status);
^
cc1: all warnings being treated as errors
The problem started appearing lately after we changed `-O0` flag to `-Og` for kernel modules compilation in the debug mode at commit 1fc7b4ba5.
Solution: initialise obj pointer at conf_cache_encode().
=> Fix compilation with --enable-debug on CentOS 7.9

ioservice/cob_foms.c, ioservice/io_foms.c, ioservice/io_service.h
Integrated bytecount btree calls in cob_write and cob_delete path.
Cob size is now updated in m0_cob::co_nsrec::cnr_size after each write.
Decrement of byetcount now works with cob updation.
Overlapping cob extents are not accounted for during cob overwrite.
If a cob is overwritten, it will make cob size inaccurate.
=> EOS-27044: Integrate bytecount btree operations in write and delete path

cob/cob.c, cob/cob.h, cob/ut/bytecount.c
Added an operation m0_cob_bc_entries_dump() to traverse the bytecount
btree and dump all keys and records in a key buffer and a record buffer
as out parameters.
This operation also returns the count of key-value pairs in the btree.
Added UT to test this feature.
=> EOS-28387: Added a bytecount btree operation to dump all key-values

cob/cob.c, cob/cob.h, cob/ut/bytecount.c, spiel/cmd.c, spiel/ut/spiel_ci_ut.c, sss/process_foms.c, sss/process_fops.h
sss foms now make m0_cob_bc_entries_dump() calls to populate
reply fop key record buffers with bytecount data from bytecount btree.
Changed implementation of spiel API m0_spiel_proc_counters_fetch() to
accept data from btree instead of hardcoded data.
=> EOS-28388: fetch data from bytecount btree

balloc/ut/balloc.c, btree/btree.c, btree/btree.h
Fix global variable init issue for btree-ut.
-  When running multiple unit tests, the global variables of btree code contained some stale data from the balloc-ut which was run previously. This was causing the lru_test to crash.
-  Added global variable init and fini functions which are called from module inti/fini and ut init/fini functions.
=> CORTX-27365 : btree-ut:lru_test is failing

net/libfab/libfab.c, net/libfab/libfab_internal.h
Add support for libfabric v1.12
- When running with libfabric v1.12.0, mkfs was getting stuck during cluster bootstrap.
-  For version >= 1.12, the libfabric library does not return the error -111 (ECONNREFUSED) if the remote service has not yet started. Thus the connection request does not receive any reply and the endpoint keeps waiting in the FAB_CONNECTING state. To avoid this, the state of the endpoint is reset after a timeout of 5s to FAB_DISCONNECTED. Thus, when the next buffer is posted to the endpoint, it will again try to establish connection by sending out a new connection request.
Checklist for …
=> CORTX-28516 : Libfabric - Compatibility for v1.12

cas/ut/service_ut.c
Problem:
Found issue while running cas-service ut with following command:
./utils/m0run m0ut --debugger=cgdb -- -t 'cas-service,be-ut:emap,balloc-ut'
Earlier 1GB segment were being used to run cas-service ut.
Fix:
Increase the seg0 size to 16MB for cas-service ut.
=> CORTX-29117: "server-restart-nomkfs", cas-service ut is failing in new btree

dix/cm/st/dix_repair_st.sh, dix/cm/st/m0t1fs_dix_repair.sh, dix/cm/st/m0t1fs_dix_repair_quiesce.sh, m0t1fs/linux_kernel/st/m0t1fs_common_inc.sh, m0t1fs/linux_kernel/st/m0t1fs_dix_common_inc.sh, spiel/st/m0t1fs_spiel_dix_repair.sh, spiel/st/m0t1fs_spiel_dix_repair_quiesce.sh
- Motr system test 24motr-dix-repair test log file not found in the indicated folder after test failure.
-  The logging is added for motr and m0t1fs DIX repair tests. This will keep the test logs available in case of failure.
=> CORTX-23743: Add logging for DIX repair tests

cm/sw_update_fom.c
Changed  log level to DEBUG, instead of ERROR for ENOBUFS and ENODATA
- ENOBUFS and ENODATA errors are being treated as ERROR, which are expected errnos during SNS Repair
-  Changed log level of expected errnos to DEBUG
-  [ x] Coding conventions are followed and code is consistent
- [x ] JIRA number/GitHub Issue added to PR
- [ x] Jira and state/status is updated and JIRA is updated with PR link
- [x ] Check if the description is clear and explained
=> Cortx-29009: ENOBUFS and ENODATA are expected during SNS repair.

motr/motr-pub.api
As code coverage symbols are specific to gcov and are
available only when --coverage-enable option is set
while configuring. Hence we can safely ignore these
symbols when this configuration option is not used.
Build failure due to missing symbols
Ignore symbols specific to code coverage
=> CORTX-29525: Ignore symbols specific to code coverage

be/extmap.c, btree/btree.c, cas/ctg_store.c, cob/cob.c
We observe a lot of expected ERRORs in kubectl logs. These errors make reading the logs a bit problematic, and might hide the errors. 
=> Suppress excess errors in kubectl logs due to Btree

btree/btree.c, btree/btree.h
Added mechanism for slow purging of lru list.
Moved initialization of lru used space watermarks to m0_btree_glob_init().
=> CORTX-29280 : Implement slow remapping of nodes in LRU list to avoid possible thrashing for random IO accesses.

addb2/dump.c
ADDB domain name is changed to include PID as a postfix
Ex:
` "_addb2-dump" to "addb2-dump_<PID>"`
Signed-off-by: Rahul Kumar <rahul.kumar@seagate.com>
=> CORTX-28510: Include PID into ADDB domain name in m0add2dump utility

utils/spiel/m0spiel
Problem:
Currently ./m0spiel -h displays error as it searches for -l option
always. It uses the path provided with -l to get to net_xpt file which
is then used to get the current transport being used. With -h option,
the -l option is not found and hence displays error.
Solution:
The solution is to use 'whereis fi_info' command to check whether
libfabric is installed or not. If it is installed then the default
transport is libfabric else other transport is being used. This solution
doesn't look for -l option.
- Currently ./m0spiel -h displays error as it searches for -l option always. It uses the path provided with -l to get to net_xpt file which is then used to get the current transport being used. With -h option, the -l option …
=> cortx-29816: m0spiel: Fix error in displaying help

dix/req.c, motr/client.c, motr/cob.c, motr/sync.c
There are memory leaks at `dix_cas_rops_send()` and `m0__obj_namei_send()` and `sync_pending_stx_update()` reported by valgrind when doing S3 object put/get/del operations with rgw:
```
+==15225== 144 bytes in 3 blocks are definitely lost 
+==15225==    at 0x4C360A5: malloc (vg_replace_malloc.c:380)
+==15225==    by 0xBE4FE3C: m0_alloc (memory.c:133)
+==15225==    by 0xBE98059: sync_pending_stx_update (sync.c:772)
+==15225==    by 0xBE987E4: sync_record_update (sync.c:807)
+==15225==    by 0xBE83435: ioreq_cc_bottom_half (io_req_fop.c:500)
+==15225==    by 0xBEF2FFE: m0_sm_asts_run (sm.c:175)
+==15225==    by 0xBEF2FFE: m0_sm_asts_run (sm.c:150)
+==15225==    by 0xBE1BAC1: loc_handler_thread (fom.c:925)
+==15225==    by 0xBE5174D: m0_thread_trampoline (thread.c:117)
+==15225==    by …
```
=> CORTX-29526: fix memleaks at data-path

doc/Seagate-FDMI-Design-Notes.md, doc/Seagate-FDMI-HLD.md, doc/reading-list.md
The older PRs are outdated as repo is updated:
The older PRs are:
https://github.com/Seagate/cortx-motr/pull/1300
https://github.com/Seagate/cortx-motr/pull/1299
-----
[View rendered Motr-Terminology-Guide.md](https://github.com/swatid-seagate/cortx-motr/blob/swatid-fdmi-upload/Motr-Terminology-Guide.md)
[View rendered doc/Seagate-FDMI-Design-Notes.md](https://github.com/swatid-seagate/cortx-motr/blob/swatid-fdmi-upload/doc/Seagate-FDMI-Design-Notes.md)
[View rendered doc/Seagate-FDMI-HLD.md](https://github.com/swatid-seagate/cortx-motr/blob/swatid-fdmi-upload/doc/Seagate-FDMI-HLD.md)
[View rendered …
=> FDMI file upload and reading-list.md file update

scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py, scripts/install/opt/seagate/cortx/motr/bin/motr_setup
…nfd in mote mini provisioner
Set proper setup size for services other than ios and confd
1: We set the setup size according to mem limits for each motr service. This mem limits are available in /etc/cortx/cluster.conf
2: Currently, these limits are available only for ios and confd motr services. 
3: If provisioner pass service parameter (to motr_setup command during deployment phases) is other than confd and ios, it tends to fail to set the setup_size. To overcome this, we ignore these (non ios and non confd) services and just set the setup_size to small to services other than ios and confd.
We deployed the cluster successfully. 
In deployment,  we …
=> CORTX-29719: Set proper setup size for services other than ios and confd

cas/ctg_store.c, cas/ctg_store.h
Changes:
- Verified using stob-ut, struct m0_be_emap_key is having header field,
which contains the versioning info of the key.
- In CAS module added version number in the header of the value part:
In case of CT_META, CT_BTREE, CT_DEAD_INDEX btree's header contains
version number in first 32-bits and key/value length in bytes in
next 32 bits. For other btree's in cas, 64-bits header contains
key/value length in bytes.
- Verified that versioning is available in value part of the CAS KV, using
cas-client,cas-service and  dix-cm-iter ut.
- Changes in Motr data structures to support Upgrade by adding Version field (if not present)
- …
=> CORTX-29183: Changes in Motr data structures to support Upgrade

conf/pvers.c
When the allowance was set to less than K at any level, and that many numbers of failures
was reached, then bytecount had become critical, but it was still marked as degraded
according to old logic as the failures were still less than K.
ex: in a 3 node cluster with SNS 4+2+0, we support at max 1 node failure.
So when a node failed, data should've become critical, but with old logic,
it was marked as degraded, as number of failures was 1 which is < K.
Updated the logic to check if failures at any level has reached it's max or not.
If it does then pool version is marked as CRITICAL even if failures < K.
-  [ ] Coding …
=> CORTX-29713: m0_conf_pver_status() now returns CRITICAL if max failures reached at any level

lib/ut/timer.c
Fix: make m0_ub_set struct object m0_timer_ub to non const.
Signed-off-by: root <root@ssc-vm-rhev4-2209.colo.seagate.com>
=> CORTX-29857: GITHUB ISSUE-list unit benchmarks failed.

scripts/install/opt/seagate/cortx/motr/bin/motr_setup
- Fixed motr_setup help typo changed "upgarde" to "upgrade"
=> CORTX-30717 motr_setup help typo

scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
Rename motr keys according to new key names (here cvg_count to num_cvg)
Created a macro for this key type so that in future, if this key is again renamed then we just need to change the macro
Tested with cortx k8s deployment
=> CORTX-29739: Rename cvg_count and storage_set_count keys

m0t1fs/linux_kernel/st/m0t1fs_failure_after_sns_repair_quiesce.sh, m0t1fs/linux_kernel/st/m0t1fs_poolmach.sh, m0t1fs/linux_kernel/st/m0t1fs_rpc_cancel_test.sh, m0t1fs/linux_kernel/st/m0t1fs_sns_repair_1f.sh, m0t1fs/linux_kernel/st/m0t1fs_sns_repair_1k_1f.sh, m0t1fs/linux_kernel/st/m0t1fs_sns_repair_1n_1f.sh, m0t1fs/linux_kernel/st/m0t1fs_sns_repair_abort.sh, m0t1fs/linux_kernel/st/m0t1fs_sns_repair_abort_quiesce.sh, m0t1fs/linux_kernel/st/m0t1fs_sns_repair_ios_fail.sh, m0t1fs/linux_kernel/st/m0t1fs_sns_repair_mf.sh, m0t1fs/linux_kernel/st/m0t1fs_sns_repair_quiesce.sh, m0t1fs/linux_kernel/st/m0t1fs_sns_repair_shutdown.sh, motr/st/utils/sns_repair_motr_1f.sh, motr/st/utils/sns_repair_motr_1k_1f.sh, motr/st/utils/sns_repair_motr_1n_1f.sh, motr/st/utils/sns_repair_motr_abort.sh, motr/st/utils/sns_repair_motr_abort_quiesce.sh, motr/st/utils/sns_repair_motr_ios_fail.sh, motr/st/utils/sns_repair_motr_mf.sh, motr/st/utils/sns_repair_quiesce.sh, motr/st/utils/sns_repair_shutdown.sh, spiel/st/m0t1fs_spiel_sns_repair.sh, spiel/st/m0t1fs_spiel_sns_repair_quiesce.sh
Following STs are updated:
08spiel-sns-repair
08spiel-sns-repair-quiesce
14poolmach
15sns-repair-shutdown
16sns-repair-multi
18sns-repair-quiesce
18sns-repair-quiesce-failure
19sns-repair-abort
20rpc-session-cancel
21fsync-single-node
22sns-repair-ios-fail
23sns-abort-quiesce
26motr-user-kernel-tests
34sns-repair-1n-1f
43motr-sync-replication
45motr-rmw
60sns-repair-motr-1f
61sns-repair-motr-1n-1f
62sns-repair-motr-mf
63sns-repair-motr-1k-1f
64sns-repair-motr-ios-fail
65sns-repair-motr-abort
66sns-repair-motr-abort-quiesce
Signed-off by: Ankit Yadav <ankit.yadav@seagate.com>
Checklist for …
=> EOS-28989: Updated STs to use the transport specific address format.

btree/btree.c
Problem:
Btree Get Record changes to load all required nodes before acquiring tree Lock
Solution:
Implemented state P_SIBLING in btree_get_kv_tick state machine.
In P_SIBLING state, if slant operation flag is true, and we are at the last
record inside the current node, then try to find sibling by loading the
required nodes and store sibling in node descriptor.
If this operation successful, take tree lock and check sibling validity
then fetch the record in P_ACT state.
- Btree Get Record changes to load all required nodes before acquiring tree Lock …
=> CORTX-30548: Load all required nodes before acquiring tree Lock in btree get op

conf/confd_stob.c
Memory allocated with m0_alloc_aligned() should be
freed with m0_free_aligned(). Existing m0_free()
happens to work correctly with memory allocated
by m0_alloc_aligned(), but this is against the
specification and will complicate the upcoming
allocation profiler.
=> conf/confd_stob.c: use aligned free for aligned allocations.

motr/ut/client.h, motr/ut/io_dummy.c, motr/ut/io_nw_xfer.c
Memory allocated with m0_alloc_aligned() should be
freed with m0_free_aligned(). Existing m0_free()
happens to work correctly with memory allocated
by m0_alloc_aligned(), but this is against the
specification and will complicate the upcoming
allocation profiler.
=> motr/ut: use aligned free for aligned allocations.

cas/client.c, dix/req.c
Problem:
Fix for memory leak introduced in commit 49ee796c0
lead to memory corruption related to m0_cas_id usage.
The m0_cas_id field of m0_cas_op may be finalized
before it's being sent to the server side.
Solution:
Have a copy of m0_cas_id (including layout) on a CAS
level to sync it with the CAS request lifetime.
=> CORTX-30728 cas/client: fix memory corruption issue

lib/user_space/thread.h, lib/user_space/ucookie.c
Cookie code (lib/user_space/ucookie.c) uses long jumps
to exit the signal handler. longjmp() restores the contents
of processor registers, including instruction and stack
pointers, to the state saved by setjmp(). longjmp() does
not restore the thread signal mask, which indicates how the
thread reacts to signals. But the signal mask is different
when the signal handler is executed (the signal being
handled is blocked), so longjmp() out of a signal handler
resumes execution with a wrong mask. Specifically, when the
cookie module jumps out of sigsegv(), the thread continues
with SIGSEGV blocked and the next receipt of SIGSEGV will
unconditionally terminate the process.
Fix this by using sigsetjmp() and siglogjmp().
=> lib/user_space: use sigsetjmp() and siglongjmp().

fdmi/ut/sd_apply_filter.c, fdmi/ut/sd_send_not.c
Results of strdup() cannot be used in motr code that
assumes that strings are freed by m0_free().
=> fdmi/ut: use m0_strdup().

scripts/jenkins/code-coverage.groovy
Added a field to specify different build parameters for Jenkins code coverage job.
The current code coverage job executes with the default build option, because of which we cannot run this for features like DTM. 
Added a field to provide build option while executing the job.
=> CORTX-29855: Add support to specify build options in Jenkins code coverage job

ut/m0ut.c
Disable LNet unit tests when Lustre support was not
compiled in, not when libfabric support was compiled in.
=> m0ut.c: LNet unit tests should depend on ENABLE_LUSTRE.

dtm0/service.c
dtm0 fop types are initialised in m0_dtm0_stype_init()
invoked by m0_init(). Hence, they should be finalised
in m0_dtm0_stype_fini() (called by m0_fini()). Finalising
them at service shutdown by dtm0_service_stop() is
premature and leads to failures of randomised (-H0) unit
tests. Specifically, dtm0-ut:drlink-simple hangs, because
fop types are not registered (they were finalised earlier)
and the test fops are not processed by the receiver.
=> Finalise dtm0 fop types in m0_dtm0_stype_fini().

stob/ut/domain.c
./__s is the standard stob domain name and with the
randomised UT (m0ut -H0), it is possible that the
domain at this pathname already exists, leading to
assertions:
./utils/m0run -H0
...
stob-ut
cache                                           3.06 sec    6 KiB
cache-idle-size0                                1.94 sec    6 KiB
null-stob-domain                                0.00 sec    1 KiB
null-stob                                       0.00 sec    7 KiB
linux-stob-domain  motr[3910443]:  7c20  FATAL  [lib/assert.c:50:m0_panic]  panic: Unit-test assertion failed: rc == -ENOENT at stob_ut_stob_domain() (stob/ut/domain.c:45) ...
Fix this by using a different pathname.
=> Use unique stob domain pathname.

layout/ut/plan.c
UT suites should be repeatable (see m0ut -n option). This means that
m0_ut_suite::ts_fini() should leave the system in the state that
m0_ut_suite::ts_init() expects.
layout-access-plan-ut initialisation changes some global variable and trips on
this on the next iteration:
```
layout-access-plan-ut [Andriy T.]
motr[2348461]:  c7d0  FATAL  [lib/assert.c:50:m0_panic]  panic: (({ unsigned __nr = (sizeof *(ha)); unsigned i; for (i = 0; i < __nr && ({ ((char *)ha)[i] == 0 ; }); ++i) ; i == __nr; })) at m0_ha_init() (ha/ha.c:647)  [git: 2.0.0-670-45-g87fc0d31-dirty] /var/motr/m0ut/m0trace.2348461
(gdb) bt
m0_arch_panic (c=0x7fffec337b40 <__pctx.15696>, ap=0x7ffffffec868) at lib/user_space/uassert.c:131
m0_panic (ctx=0x7fffec337b40 <__pctx.15696>) at lib/assert.c:52
m0_ha_init (ha=0x7fffedb1e000 …
```
=> layout-access-plan-ut: make it repeatable

cas/service.c
cas_fom_tick ENTRY record in m0trace includes numerical state ID. This commit adds state name as text to that m0trace record.
- cas_fom_tick ENTRY record in m0trace includes numerical state ID.  It is inconvenient to debug, as there is no easy way to convert number state name.
-  There's a function already implemented which can convert state ID to its name -- `m0_fom_phase_name`.  I'm using it in M0_ENTRY to produce state name.
=> Add CAS FOM state name in m0trace

sns/parity_math.c, sns/ut/parity_math_ut.c
Unit tests must be ready for repeated execution (see m0ut -n option). Reset
static variables in parity math UT. This fixes sporadic UT failures, see
https://github.com/Seagate/cortx-motr/issues/1661.
Also, gf_invert_matrix() does not return error code, it returns -1. Use EDOM
instead.
=> parity-math-ut: fix repeated execution

motr/m0kv/cmd_main.c, motr/m0kv/index.h, motr/m0kv/index_op.c, motr/m0kv/index_parser.c
Analysis:
Pool version info will be stored by the client(S3 server/m0kv/m0client)
if the M0_ENF_META flag is true. That support was not available
for m0kv.
Fix:
Added the "-e" flag to support M0_ENF_META. Pool version info
will be available on console when run "m0kv index create" operation.
m0kv needs to pass the pool version info as an argument for
PUT/GET/DEL/NEXT if the "-e" flag is added.
MO_ENF_META flag Ref:
https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/297862297/md-path+optimization+by+avoiding+internal+dix+layout+lookups
=> CORTX-30423: M0_ENF_META support for m0kv

net/libfab/libfab.c
Fix a bug in libfab_domain_params_get() where
fi_freeinfo() was called on an unallocated fi.
Signed-off-by: Nikita Danilov nikita.danilov@seagate.com
=> libfab.c:libfab_domain_params_get() free "fi" only when it was allocated

motr/m0crate/crate_client.h, motr/m0crate/crate_index.c, motr/m0crate/crate_io.c, motr/m0crate/parser.c, motr/st/utils/m0crate_st_workloads.yaml
M0_ENF_META support for m0crate
Analysis:
Pool version info will be stored by the client(S3 server/m0kv/m0crate)
if the M0_ENF_META flag is true. That support was not available
for m0crate.
Fix:
Added the "IS_ENF_META" flag to support M0_ENF_META. m0crate needs
to pass the pool version info for PUT/GET/DEL/NEXT if the
"IS_ENF_META" flag is enabled.
=> CORTX-30429: M0_ENF_META support for m0crate

motr/io_req.c, motr/st/utils/motr_utils_st.sh, stob/ad.c
Panic: `((cr->tc_balance[cu]) != 0) at btree_save() (be/btree.c:1393)`
Stack is the same in all processes core files:
#3  0x00007f9454ccbe37 in m0_panic (ctx=ctx@entry=0x7f94550e15a0 <__pctx.8664>) at lib/assert.c:52
#4  0x00007f9454c0747c in btree_save (tree=tree@entry=0x40000010ed80, tx=tx@entry=0x7f94200a7f90, op=op@entry=0x7f944ca77ec0,
val=val@entry=0x7f944ca77e70, anchor=0x0, optype=BTREE_SAVE_UPDATE, zonemask=2, key=<optimized out>, key=<optimized out>)
at be/btree.c:339
#5  0x00007f9454c086f7 in m0_be_btree_update (tree=tree@entry=0x40000010ed80, tx=tx@entry=0x7f94200a7f90,
op=op@entry=0x7f944ca77ec0, key=key@entry=0x7f944ca77e60, val=val@entry=0x7f944ca77e70) at be/btree.c:1952
#6  0x00007f9454bfd62b in btree_update_sync (val=0x7f944ca77e70, key=0x7f944ca77e60, tx=0x7f94200a7f90, …
=> Fix crash of all ios processes in some write scenarios

m0t1fs/linux_kernel/st/m0t1fs_dgmode_io.sh, m0t1fs/linux_kernel/st/m0t1fs_multi_clients.sh, m0t1fs/linux_kernel/st/m0t1fs_rpc_cancel_test.sh, m0t1fs/linux_kernel/st/m0t1fs_server_inc.sh, m0t1fs/linux_kernel/st/m0t1fs_sns_repair_1f.sh, motr/st/utils/motr_device_util.sh, motr/st/utils/motr_dgmode_io_st.sh
warning fixed : "Double quote to prevent globing and words splitting".
We see 1688 occurrence of pattern, "Double quote to prevent globing and words splitting".
We are putting the variable references in double quotes.
=> CORTX-30751: Codacy code cleanup (#1606)

stob/ut/stob.c
Similar to https://github.com/Seagate/cortx-motr/pull/1642.
Signed-off-by: Nikita Danilov nikita.danilov@seagate.com
=> Use unique pathnames to avoid clashes in randomised UT runs

sns/cm/repair/ut/cp_common.c
Prevent domains of different types from being created at the same path.
=> sns/cm/repair/ut: use different domain paths for ad and linux stobs.

fdmi/ut/pd_ut.c
Memory allocations happen asynchronously with the
test (from other threads), so fault-point activation
is not deterministic.
=> detour_create(): fix unreliable UT.

addb2/addb2.h
Move magic field to the beginning of the struct to catch the mysterious
corruption.
=> m0_addb2_sensor: move s_magic field.

cas/cas.h, cas/client.c, cas/service.c, dix/req.c, motr/idx.c, motr/idx.h, motr/idx_dix.c, motr/ut/idx_dix.c
Adding a flag disabling use of dtm for a particular operation.
This flag is set by the motr user (e.g., s3 server), passed through
layers of motr client stack and is sent to the server.
=> CORTX-30965 Add NODTM per-operation flag to MOTR client interface

net/libfab/libfab.c
Add support for libfabric v1.14.x and v1.15.x.
- Adapting libfab.c file due to change in behavior of some API's of the libfabric library.
=> CORTX-29418 : Add support for libfabric v1.14.x and v1.15.x

motr/m0kv/index_op.c
When ENF_META flag was not used, m0_idx_op::in_attr was not properly
initialized.  Which lead to precondition check failure when trying to
run PUT KV with m0kv.
- See #1741 for issue description.
=> CORTX-31248: Initialize m0_idx_op with zeroes in m0kv index_op.

motr/io_req.c, motr/io_req_fop.c
During degraded read, if we fail to read some parity unit,
the resulted data returned to the user will be corrupted.
See https://github.com/Seagate/cortx-motr/issues/1598#issuecomment-1117641227.
RCA: we don't mark the parity unit as PA_READ_FAILED,
so we pass the wrong map of the failed units to recover.
Solution: call iro_dgmode_recover() after marking the units
as PA_READ_FAILED, which is done via ioreq_fop_dgmode_read() ->
pargrp_iomap_dgmode_process() calls at ioreq_dgmode_read().
=> client: fix corrupted read on 2+ drive fails

addb2/st/addb2dump-plugin.sh, cas/st/ctgdump_tesh.sh, console/st/console-st.sh, dix/cm/st/m0t1fs_dix_repair.sh, dix/cm/st/m0t1fs_dix_repair_quiesce.sh, motr/st/utils/motr_conf_update_st.sh, motr/st/utils/motr_device_util.sh, motr/st/utils/motr_fs.sh, motr/st/utils/motr_local_conf.sh, motr/st/utils/motr_raid0_st.sh
Warning fixed: "Double quote to prevent globing and words splitting."
Signed-off-by: alfhad <fahadshah2411@gmail.com>
We see 1688 occurrence of pattern, "Double quote to prevent globing and word splitting".
We are putting the variable references in double quotes.
=> CORTX-30751: Codacy code cleanup (#1606).

motr/io_req.c
The regression was introduced at 570645319 after which
SNS system tests started failing.
RCA: rc is not reset after device_check() at ioreq_dgmode_read().
As result, in some conditions, it may be interpreted as failed
degraded read.
Solution: reset rc after device_check() call.
=> CORTX-31264: fix SNS system tests regression

motr/io_req.c
The regression was introduced at commit 446fe0372:
motr/io_req.c:1736:21: error: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘m0_bcount_t’ {aka ‘long long unsigned int’} [-Werror=format=]
M0_LOG(M0_NOTICE, "user data written with degraded redundancy: "
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Solution: use PRIu64 format for printing m0_bcount_t.
=> CORTX-31292: fix m0tr.ko build regression

bindings/go/mio/mio.go
Four motr connection parameters can be (optionally) provided
to mio.Init() API in the following order:
1) local endpoint;
2) hax endpoint;
3) profile fid;
4) local process fid.
This might be useful in case user wants to configure these
parameters via a configuration file and provide the values
explicitly to go/mio library.
=> go/mio: add optional connection params to Init()

lib/user_space/utrace.c
save traces between container/pods restart in k8s.
=> CORTX-28925-new: Append timestamp/any unique value to m0trace to

motr/client.h, motr/io.c, motr/io_nw_xfer.c, motr/st/utils/cat.c, motr/st/utils/helper.c, motr/st/utils/motr_utils_st.sh, motr/st/utils/truncate.c
Use no hole mode by default and rename M0_OOF_NOHOLE flag to M0_OOF_HOLE, which user should set to enable hole mode.
This will help to avoid returning corrupted data to the user in case there are no units at the server side in parity groups (for some reason) by automatically enabling degraded read mode in such cases.
Relates to https://github.com/Seagate/cortx-motr/issues/1598.
=> client: use no hole mode by default

cm/ut/cm.c
Also, assert that the ast is not used when re-initialised.
=> cm-ut:cm_ag_ut: zero structures before use

scripts/install/opt/seagate/cortx/motr/common/m0_dix_utils_common.sh, scripts/install/opt/seagate/cortx/motr/common/m0_sns_utils_common.sh, scripts/install/opt/seagate/cortx/motr/common/m0_spiel_dix_utils_common.sh, scripts/install/opt/seagate/cortx/motr/common/m0_utils_common.sh, scripts/install/opt/seagate/cortx/motr/libexec/m0_ha_sim, spiel/st/m0t1fs_spiel_dix_common_inc.sh
- The m0_ha_sim utility by default supports m0repair utility for SNS and DIX repair / rebalance. There was no support to use m0spiel for SNS and DIX repair / rebalance.
-  Added new option -u for m0_ha_sim to get the utility from user. m0repair is used by default. Based on the utility selected, the repair and rebalance functions are called.
=> CORTX-30921: Add spiel support for dix repair and rebalance in m0_ha_sim

sns/cm/repair/ut/cm.c, ut/m0ut.c
Added steps for rebalance in SNS repair UT to improve code coverage for SNS rebalance
Renamed sns-cm-repair-ut to sns-cm-repreb-ut
For code coverage improvement analysis please refer CORTX-30098.
Signed-off-by: Jugal Patil <jugal.patil@seagate.com>
=> Improve code coverage for SNS rebalance

scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py, scripts/install/opt/seagate/cortx/motr/bin/motr_setup
- Since 'storage' has no item other than "cvg', the hierarchy 'storage'>'cvg' can be merged to 'cvg' in GConf and changes need to be aligned accordingly wherever it is being used.
1: Current Structure:
storage:
cvg:
- devices:
data:
- /dev/sdc
- /dev/sdd
metadata:
- /dev/sdb
name: cvg-01
type: ios
- devices:
data:
- /dev/sdf
- /dev/sdg
metadata:
- /dev/sde
name: cvg-02
type: ios
num_cvg: 2
2: New Structure
cvg:
- name: cvg-02
type: ios
devices:
metadata:
- /dev/sdb
data:
- /dev/sdc
- name: cvg-01
type: ios
devices:
metadata:
- /dev/sde
data:
- /dev/sdf
num_cvg: 2.             …
=> CORTX-29834: Remove dependency from key storage, instead use cvg

Makefile.am, cortx-motr.spec.in, scripts/provisioning/roles/motr-runtime/vars/RedHat.yml, utils/Makefile.sub
removed ruby references from motr repo
removed m0genfacts reference from makefile
Signed-off-by: Parikshit Dharmale <parikshit.dharmale@seagate.com>
- [CORTX-30762](https://jts.seagate.com/browse/CORTX-30762)
- cortx-motr repository installs Ruby and related libraries, a security_vulnerability is tagged because all the ruby packages installed with the image has known vulnerabilities in it. 
references to ruby are removed 
reference to m0genfacts are removed which causes  ruby installation
- Tested with custom build 6048, motr rpm does not have ruby dependency 
- Tested in deployed cluster, all the motr containers does not have ruby lib installation 
Checklist for …
=> remove ruby lib from motr repo

be/dtm0_log.c, be/dtm0_log.h, dix/req.c, dtm0/dtx.c, dtm0/dtx.h, dtm0/fop.c, dtm0/tx_desc.c, dtm0/tx_desc.h
Problem:
Currently there is no support for TRANSIENT failures on the DIX
and DTX levels for DIX PUT operations, only the happy path is
supported (with and without DTM0 enabled). In case of TRANSIENT
failure the DIX PUT operation hangs in awaiting of response from
the OFFLINE process as currently the requests are sent to OFFLINE
devices (as TRANSIENT notification is mapped to OFFLINE devices
state).
Solution:
In order to support transient failures for DIX PUT operations the
following changes have been introduced:
- skip sending of CAS requests to OFFLINE devices;
- add services that correspond to OFFLINE devices into
participants list as they are still the cluster members, when
they are back we need to restore missing info, that's why we
need to add them also;
- move transient participants …
=> CORTX-27608 dix/dtm0: add support of transient failures for PUT

Makefile.am, debian/cortx-motr.install, scripts/install/opt/seagate/cortx/motr/common/m0_spiel_sns_utils_common.sh, scripts/install/opt/seagate/cortx/motr/libexec/m0_ha_sim
- The m0_ha_sim utility by default supports m0repair utility for
SNS and DIX repair / rebalance. With this change, support for m0spiel
utility is added for SNS repair / rebalance.
- Added new option -u to get the utility from user. m0repair is used by
default.
- Fixed codacy issues.
- PR : https://github.com/Seagate/cortx-motr/pull/1770
=> CORTX-30920: Add m0spiel support in m0_ha_sim for SNS Rep/Reb.

motr/st/utils/spiel_sns_motr_repair.sh, spiel/st/m0t1fs_spiel_sns_common_inc.sh
Problem: The ST 71spiel-sns-motr-repair was returning the END status as SUCCESS, even if the test failed.
This was a misleading behavior.
Solution: Added checks to return appropriate return values from function calls or test steps.
for more details please refer CORTX-29192.
Signed-off-by: Swapnil Chaudhary <swapnil.chaudhary@seagate.com>
=> CORTX-29192: spiel sns repair ST failing at last step

scripts/install/opt/seagate/cortx/motr/sanity/motr_sanity.sh, scripts/install/usr/libexec/cortx-motr/motr-service.functions
- The failure was seen for 52motr-singlenode-sanity test on lnet transport.
-  The issue was in one of the condition check for transport.
=> CORTX-31497: Fix 52motr-singlenode-sanity system test for lnet transport

spiel/st/spiel_multiple_confd.sh, utils/functions, utils/spiel/m0spiel
- The m0spiel utility was using old address format for libfabric transport. 
- Also for lnet transport, there was failure in getting the IP address. Even command `m0spiel -h` also failed for lnet transport.
-  Added support for new address format for libfabric transport.
- Fixed issue in getting address for lnet transport.
=> CORTX-29815 m0spiel: Add support for new address format

dix/req.c, dix/req_internal.h
Problem:
Before merging of degraded DIX PUT support for transient
failures (PR https://github.com/Seagate/cortx-motr/pull/1545)
the degraded GET worked by a mistake: sending of requests
to offline targets + resend logic.
The PR mentioned above prevents sending of requests to
offline devices, so the offline unit is skipped. Other alive
targets are not selected due to dix_online_unit_choose()
function (limits the number of units to be selected to 1
to send a single request for DIX GET, allows to iterate
over parity units in case of server-side failures).
So if the first unit is offline then whole DIX operation
wails with -EIO immediately and no resend logic is triggered.
So need a proper way to handle transient failures for DIX GET.
Solution:
Mark a unit as unavailable (previously named …
=> CORTX-30872 dix: add support of transient failures for GET

btree/btree.c
Problem:
This issue was happening because we are collecting memory stats
using system api. There might be case when we write objects in that
timeframe some other process on the system might release memory and
hence we can see memory freed in our stats.
Solution:
If above case arises, cleanup the existing btree and records, then
restart the test, try upto 20 times restarting the test. If we
still get the issue, fail the test.
=> CORTX-31308: "btree-ut:lru_test" failing intermittently

utils/trace/m0trace
- On Rocky Linux 8.4, m0trace shows warnings "when/given is experimental".  Rocky has more recent perl version, which is now showing such warnings.
- Tell Perl to suppress the warning.
=> Fix m0trace 'experimental' warnings on Rocky Linux

be/dtm0_log.c, be/dtm0_log.h, be/ut/dtm0_log_ut.c, motr/ut/idx_dix.c
Signed-off-by: Anatoliy Bilenko <anatoliy.bilenko@seagate.com>
- added log iterator code as a part of DTM0 recovery algorithm and UT.
https://seagate-systems.atlassian.net/wiki/spaces/~770032066/pages/609880834/DTM+Basic+Recovery+HLD+draft
- [not needed] Testing was performed with RPM
- [N/A] Side effects on other features (deployment/upgrade)
- [N/A] Dependencies on other component(s)
- [N/A] Changes done to WIKI / Confluence page / Quick Start Guide
=> EOS-24484: Added DTM0 Log iterator and UTs.

scripts/install/etc/sysconfig/motr
A deadlock like situation is observed in setups comprising of 15 nodes
and beyond, for instance, on below systems atleast 3 ioservices are trying
and failing to connect to each other.
```
[root@ssc-vm-g2-rhev4-1630 ~]# kubectl logs cortx-data-ssc-vm-g3-rhev4-2184-7d578c588d-tnhnq cortx-motr-io-002039bf80 ri_nr_sent_max=18446744073709551615ri_deadline=0 ri_nr_sent=1
2022-05-26 15:28:13,542 - motr[00057]: b760 ERROR [rpc/frmops.c:486:item_done] packet 0x7fdcd00fb730, item 0x7fdc40212fd0[33] failed with ri_error=-110
2022-05-26 15:28:13,542 - motr[00057]: b760 ERROR [rpc/frmops.c:482:item_done] item: 0x7fdc4012c8b0 dest_ep=inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-1635@21001 ri_session=0x7fdcd0526c80 ri_nr_sent_max=18446744073709551615ri_deadline=0 ri_nr_sent=1 …
```
=> rpc: ioservices fail to connect to each other on larger setups (15, 24)

motr/io_req.c
Problem:
There exists cases where an -ENOENT error is returned when
trying to read a data unit:
(1) In case of read before write, due to CROW, COB will not be
present, resulting into -ENOENT error.
(2) The COB of the unit to read is not created if ioservice
crashes before the COB creation.
For case 2, as current implementation returns -ENOENT immediately
from ioreq_dgmode_read() without triggering degraded read,
application gets -ENOENT error.
Solution:
As the -ENOENT error in the above cases only means the
corresponding COB doesn't exist and it doesn't mean the object to
read doesn't exist as the object has to be opened before read. So
in either of these cases, let device_check() decide if degraded
read can proceed.
-  [ ] Coding conventions are followed and code is …
=> client: do degraded read when -ENOENT is returned

lib/ut/fold.c
Reverts Seagate/cortx-motr#1798
=> Revert "CORTX-30947: Codacy: Fix 'Division by Zero' issue"

addb2/st/addb2dump-plugin.sh, console/st/console-st.sh, dix/cm/st/m0t1fs_dix_repair.sh, fdmi/st/echo/echo_plugin_start.sh, fdmi/st/fdmi_test.sh
Warning fixed: "SC2006: Use $(...) notation instead of legacy backticked `...`".
Signed-off-by: alfhad <fahadshah2411@gmail.com>
We see 369 occurrence of pattern, "Use$(...) notation instead of legacy backticked ....".
Replaced the backticked with "$(...)"
=> CORTX-30753: Codacy code cleanup(#1608)

scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
warning fixed : "subprocess_without_shell_equals_true"
Codacy warning, "subprocess_without_shell_equals_true"
Explicitly disabled the subshell because it can pose a security risk in case the default changes. 
=> Codacy code cleanup

be/tx_group_format.c, be/tx_group_format.h
Problem : In m0_be_op_fini, when bos_tlink_fini is performed then its expected that bo_set_link should not have link for 
link for parent's m0_be_op::bo_children. 
State seen at the time of crash:
Two gft_pd_io in progress state, with corresponding two bio in sched queue; crash is hit while performing the gc callback processing for gft whhose gft_pd_io is in progress state and bio is queued behind an active io.
Panic:
2022-04-24 11:19:15,672 - motr[00107]: e2e0 FATAL [lib/assert.c:50:m0_panic] panic: (!m0_list_link_is_in(link)) at m0_list_link_fini() (lib/list.c:178) [git: 2.0.0-670-27-g0012fe90] /etc/cortx/log/motr/0696b1d9e4744c59a92cb2bdded112ac/trace/m0d-0x7200000000000001:0x2e/m0trace.107
2022-04-24 11:19:15,672 - Motr panic: (!m0_list_link_is_in(link)) at m0_list_link_fini() …
=> CORTX-30993 - BE: Avoid usage of gft_tmp_op to put group fom op into active state

pool/pool.c
Problem: when running a repeated bootstrap/shutdown of the cluster (bootstrap till all m0d are online, followed by immediate shutdown, no delays anywhere; repeated in the loop), the following assertion is triggered time to time (saw it twice, one time on 6th iteration, another time at 27th iteration).
```
(gdb) bt
0  0x00007fed6452338f in raise () from /lib64/libc.so.6
1  0x00007fed6450ddc5 in abort () from /lib64/libc.so.6
2  0x00007fed66709150 in m0_arch_panic (c=0x7fed66d1ab00 <__pctx.23240>, ap=0x7ffd24f6ecb8) at lib/user_space/uassert.c:131
3  0x00007fed666e9498 in m0_panic (ctx=0x7fed66d1ab00 <__pctx.23240>) at lib/assert.c:52
4  0x00007fed667b4d41 in service_ctxs_destroy (pc=0x7ffd24f6ef20) at pool/pool.c:865
5  0x00007fed667b7c4e in m0_pools_service_ctx_destroy (pc=0x7ffd24f6ef20) …
```
=> Fix assertion during shutdown in m0_pools_service_ctx_destroy.

dtm0/domain.c
Check that conf is initialized before accessing it (fix regression after merging domain/recovered, see #1744).
Problem: client-ut fails:
```
$ sudo ./utils/m0run -- m0ut -t client-ut
START Iteration: 1 out of 1
client-ut
m0_client_init  motr[648725]:  6ba0  FATAL  [lib/assert.c:50:m0_panic]  panic: (confc->cc_root != ((void *)0)) at m0_confc_root_open() (conf/helpers.c:226)  [git: 2.0.0-794-16-g4bdd8326-dirty] /var/motr/m0ut/m0trace.648725.2022-06-10-03:33:52
Motr panic: (confc->cc_root != ((void *)0)) at m0_confc_root_open() conf/helpers.c:226 (errno: 0) (last failed: none) [git: 2.0.0-794-16-g4bdd8326-dirty] pid: 648725  /var/motr/m0ut/m0trace.648725.2022-06-10-03:33:52
```
```
(gdb) bt
#0  0x00007fffe9ba837f in raise () from /lib64/libc.so.6
#1  0x00007fffe9b92db5 in abort () from …
```
=> Check that conf is initialized before accessing it

dtm0/drlink.c, dtm0/fop.h, dtm0/recovery.c, dtm0/recovery.h
* Add comment on locks and destroying sm group in m0_dtm0_recovery_machine_fini().
* Use m0_xcode_dup() to implement dtm0_req_fop_dup()
* Rewrite ASSERT condition for better readability.
* Minor code formatting adjustments.
* Rewrite ASSERT to avoid side effects.
* Add documentation for m0_dtm0_recovery_machine_redo_post.
=> dtm/recovery: Address code review comments.

lib/vec.c, lib/vec.h, motr/client.h, motr/io.c, motr/io_nw_xfer.c, motr/io_pargrp.c, motr/io_req.c, motr/st/utils/helper.c, rpc/frmops.c
Currently, in degraded read mode we read all data units of the
parity group without M0_IO_FLAG_NOHOLE flag (we get zeros from
servers for the missing units instead of errors). So if unit is
missing not because there is no user data (last parity group),
but because of previous degraded write - we will provide wrong
input for the recovery function and return garbage to the user.
Solution: 1) read data units with M0_IO_FLAG_NOHOLE flag in de-
graded mode; 2) introduce M0_OOF_LAST flag for the user to
specify for the last read unit(s) of the object, and don't try
to read the missing units beyond the object size.
Also, check M0_OOF_LAST flag to avoid RMW on writing the last
units of non-fully-spanned parity group, and avoid calculating the
wrong parity when overwriting the existing object of …
=> CORTX-31617: fix data recovering on degraded read

motr/m0crate/crate_client.h, motr/m0crate/crate_index.c, motr/m0crate/parser.c, motr/st/utils/m0crate_st_workloads.yaml
Added IS_SKIP_LAYOUT to enable M0_OIF_SKIP_LAYOUT. It will enable
single Tx support.
Added IS_CROW_DISABLE to disable MO_OIF_CROW.
=> CORTX-30435: Support to configure SKIP_LAYOUT and CROW for m0crate

dtm0/drlink.c, dtm0/recovery.c, dtm0/recovery.h
* Remove unneeded _ST macro.
* Add M0_PRE(!m0_sm_conf_is_initialized(&m0_drm_sm_conf)); in m0_drm_domain_init().
* Minor coding style fixes.
* Add documentation comments.
* Review and elaborate on XXX comments.
* Rename restore() -> dtm0_restore().
* Make `redo` structure a local variable, move it out of coroutine context, add
comment.
=> dtm/recovery: Address code review comments (part 3).

cas/cas.h, cas/service.c, dix/fid_convert.c, dix/fid_convert.h, dtm0/fop.c, motr/ut/idx_dix.c
Problem:
REDO messages sent by the DTX participants contain CAS operation
with a component catalogue FID containing device ID that is local
for each participant.
Handling of the REDO message resulting in a processing of CAS
operation. During processing of any CAS operation we didn't check
that device encoded into component catalogue FID is served by
the target CAS service using conf cache (rely on the client).
But in case of REDO device ID is incorrect, that results into
a new component catalogue creation using CROW mechanism that is
incorrect.
Solution:
Find attached device in conf and store it inside of CAS service
structure when CAS service starts.
When the REDO message arrives the REDO message handler related to
CAS service gets device id attached to a local CAS service and
sets it as …
=> CORTX-31180 dtm0/cas: fix sdev ID for incoming REDO messages

scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
- Increase rpc queue length. It is required for 15/36 node deployments.
In 15/36 node deployments, we observe tmieouts in the s3 requests so rpc queue length need to be increased to 64.
=> CORTX-31985: Set MOTR_M0D_MIN_RPC_RECVQ_LEN to 64 for VM

lib/bitmap.c, lib/ut/cookie.c
Fix1: lib/ut/cookie.c - Initialize a variable before its usage
Fix2: lib/bitmap.c - Validate a pointer before dereferencing it
- Fix Codacy Issues
-  Initialize a variable before its usage. Validate a pointer before dereferencing it
=> cortx-30077 : Fix codacy issues

fdmi/plugins/fdmi_plugin_st.sh
As giving double quote to MOTR_PARAM will result in it being
treated as single argument hence we need to keep this
variable without quotes and ignore the warning.
This reverts commit bdeec5589462f8edfe30c7fb0e73600712a7275b.
=> CORTX-32333: Revert "CORTX-30751: Codacy code cleanup (#1606) (#1730)"

scripts/addb-py/chronometry/task_queue/task_queue.py
warning fixed : "Unexpected keyword argument 'priority' in
function call"
Getting codacy warning, "Unexpected keyword argument 'priority' in function call"
Restructured the code to avoid this warning. 
=> CORTX-32365: Codacy code cleanup (#1914)

net/ip.h
- Increase FQDN length to 255 characters in motr for kubernetes.
Motr currently defines network names to a maximum length of 150 characters via `#define M0_NET_IP_STRLEN_MAX 150` , however this will cause issues in more dynamic Kubernetes environments as it is a relatively low character count when deploying large and robust CORTX clusters on Kubernetes.
In following with the https://www.ietf.org/rfc/rfc1035.txt spec and [base Kubernetes Object Naming characteristics](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names), this should be updated to be 253 characters or less.
Checklist for …
=> CORTX-32368: Increase FQDN length to 255 characters in motr for kubernetes

motr/io_req_fop.c, net/libfab/libfab.c, reqh/reqh_service.c
In k8 environment we may face the situation where the hostnames of the
endpoints in the Motr configuration does not match with the hostnames
returned by gethostbyaddr(). Because of that, we may end up in the
situation where we are trying to connect to an endpoint to which we have
already established connection. This leads to disconnects/reconnects
that may not be properly handled by some of the Motr components.
For example, DTM0 sends Pmsgs using a separate rpc_link. If the link is
connected to "host1@1" (string taken from configuration) then consequent
attempt of IO service to do bulk operation with "host1.local@1" (string
taken from gethostbyaddr) will cause disconnects and attempts to
re-connect.
Apparently, bulk and libfab modules are not able to handle this
situation gracefully: …
=> CORTX-32086 net: fix for io bulk failure when multiple hostnames associated with same ip

spiel/ut/spiel_conf_ut.c
=> CORTX-30106: Changed data type of return value for read to ssize_t from size_t

dtm0/recovery.c, dtm0/ut/main.c
Problem:
Following panic occured in RGW server,
0x00007fe42959810d in m0_panic (ctx=ctx@entry=0x7fe429a58da0 <signal_panic>) at lib/assert.c:52
0x00007fe4295a975c in sigsegv (sig=11) at lib/user_space/ucookie.c:52
<signal handler called>
0x00007fe42959ff6c in m0_tlist_next (d=d@entry=0x7fe4299c55a0 <lrec_tl>, list=0x55dc7fe1f6a0, obj=0x0) at lib/tlist.c:283
0x00007fe4294eb492 in lrec_tlist_next (amb=<optimized out>, list=<optimized out>) at be/dtm0_log.c:43
m0_be_dtm0_log_iter_next (iter=iter@entry=0x55dc84dccd38, out=out@entry=0x7fe41cc47ef0) at be/dtm0_log.c:689
0x00007fe429553704 in default_log_iter_next (m=<optimized out>, iter=<optimized out>, tgt_svc=<optimized out>,
origin_svc=<optimized out>, record=0x7fe41cc47ef0) at dtm0/recovery.c:2077
0x00007fe42955448e in …
=> CORTX-33161 client: fix panic of RGW server

fop/fom.c
Problem:
As livenesss of DTM foms is longer they are logged as hung foms,
which causes logs getting filled, due to which containers are evicted
due to disk full.
Solution:
Don't post the hung fom logs for DTM requests.
=> CORTX-32856 fom: don't long hung foms of DTM requests

fdmi/source_dock_fom.c, fdmi/source_dock_internal.h
Also, we don't do wakeup the timer fom when stopping FDMI service. It will finalizes
itself when timeout arrives. This is to avoid race conditions if there are
two ways to wake up a fom.
```
cas-service [Nikita]
init-fini [Nikita]                              0.29 sec   74 MiB
init-fail [Leonid]                              0.30 sec   81 MiB
re-init [Egor]                                  2.03 sec    6 MiB
re-start [Nikita] 
---jenkins metadata---
[[ATTACHMENT|/storage/fsroots/motr-remote-controller-smc13-m11/workspace/Cortx-PR-Build/Motr/junit/01motr-single-node.00userspace-tests/00userspace-tests.testnode0.m0reportbug-traces.partial.tar.xz]]
[[ATTACHMENT|/storage/fsroots/motr-remote-controller-smc13-m11/workspace/Cortx-PR-Build/Motr/junit/ …
```
=> Start FDMI source dock timer fom only when FDMI filters are defined.

fdmi/ut/filterc_ut.c
The UT test thread posts a FDMI record, and waits for it to be processed (in another thread).
The original code uses m0_chan to do the synchronization.
But the m0_chan_wait() must be called before the m0_chan_signal()/m0_chan_broadcast().
Otherwise, the m0_chan_wait() will not be signaled.
Now let's use m0_semaphore to synchronize this.
m0_semaphore_{down, up} can be called in any order.
=> Fix fdmi ut filterc

motr/client.c, motr/client.h, motr/idx_dix.c
The UT idx-dix:namei-ops-cancel-dist panics sometimes.
The problem is:
A Motr application wants to cancel an ongoing op by m0_op_cancel().
Then, this application waits for this op, and then calls m0_op_fini() and frees the op.
But the op cancel itself is asynchronous as an AST. At the time of the AST is scheduled to run,
the op itself may be already freed.
In order to maintain the call sequence of Motr application, a semaphore is introduced.
If the op cancel is still in progress, the m0_op_fini() will have to wait for this semaphore.
The semaphore will be up when the cancel AST is done.
=> Fix namei ops cancel dist

scripts/install-build-deps
Problem : On Rocky Linux version 8.4 ./scripts/install-build-deps
is failing for ansible with the error "nothing provides
(ansible-core >= 2.12.2 with ansible-core < 2.13)
needed by ansible-5.4.0-2.el8.noarch" also if we ignore
the ansible then it is failing with the error "nothing
provides libLLVM-13.so()(64bit) needed by
castxml-0.4.5-2.el8.x86_64".
Solution : New yum repo is added via yum-config-manager. If the
installation of ansible is failed, it will install
epel repo and ansible again after fetching from the
newley added repo.
Checklist for …
=> CORTX-32040 : GITHUB ISSUE-./scripts/install-build-deps fails

dtm0/it/all2all/cdf.yaml
Problem:
The log device support has been added for hare CDF
* https://github.com/Seagate/cortx-hare/pull/2136
that leads to CDF format errors during cluster bootstrap
in all2all DTM0 integration test.
Solution:
Add missing log sections for confd and m0d into CDF.
In case of DTM0 integration test that sections contains an
empty devices list.
=> dtm0/it: fix all2all CDF according to new changes in hare

dtm0/it/all2all/all2all
Earlier, ctgdump failures were ignored, and certain issues were not detected in integration test.  For example -- recent b-tree changes broke ctgdump (it crashes with core dumps), but all2all did not "notice" these crashes and reported success.
=> DTM0: detect ctgdump failures in all2all script

be/dtm0_log.c, be/dtm0_log.h, dtm0/recovery.c, dtm0/recovery.h, dtm0/ut/main.c
Re-opens the same fix as in PR #1846.
Problem: under load, with continuous S3 IO, recovery will never end -- new entries will be continuously added to the end of the log, and recovery machine will keep replaying them forever.
Solution: Remember last entry in the log at the start of recovery, and stop recovery when reaching that point.  All new transactions added after will not be replayed.
=> DTM/recovery: Do not send REDO for transactions which happened after recovery started

ha/ut/note.c, rm/rm_service.c
* In commit 3af2fc786e, we do reverse session cleanup in prepare_to_stop().
So, we must also do rms_resource_free() in rso_prepare_to_stop().
This patch fixes the rm-ut:rmvsv UT failure:
Thread 29 (Thread 0x7f77553f4700 (LWP 1763408)):
0  0x00007f77adb9ada8 in nanosleep () from /lib64/libc.so.6
1  0x00007f77adb9acae in sleep () from /lib64/libc.so.6
2  0x00007f77afc34af2 in m0_debugger_invoke () at lib/user_space/uassert.c:144
3  0x00007f77afc34c04 in m0_arch_panic (c=c@entry=0x7f77b00fa700 <signal_panic>, ap=ap@entry=0x7f77553f2538) at lib/user_space/uassert.c:129
4  0x00007f77afc22ba7 in m0_panic (ctx=ctx@entry=0x7f77b00fa700 <signal_panic>) at lib/assert.c:52
5  0x00007f77afc34c48 in sigsegv (sig=11) at lib/user_space/ucookie.c:52
6  <signal handler called>
7  m0_rpc_conn_is_snd …
=> Do rms_resource_free() in rso_prepare_to_stop()

be/extmap.c, cas/ctg_store.c
Issue:
- ctg_open() is responsible for allocating tree pointer and
opening the btree. This was missing before accessing the
catalogue tree in the ctgdump().
Fix:
- Added ctg_open() call before accessing tree pointer.
- Added m0_btree_close() to close tree in ctg_fini().
=> CORTX-33586: ctgdump is crashing after new btree merge

be/alloc.c, be/alloc.h, be/linux_kernel/stubs.c, be/ut/alloc.c, be/ut/main.c, btree/btree.c
- Current BE allocator will clear memory contents when m0_alloc*() routines are
called. This is not always desirable since the Tx credits requirements increase
because the cleared memory needs to be captured in the transaction.
This commit contains:
1) Changes to skip memory clearing during allocation.
2) Revised credit needs when no-clear version of the allocation is called.
3) UT to verify memory allocation contents.
4) Btree changes to use he no-clear memory routines.
=> Changes in BE allocator to support no-clear mode during allocation.

rpc/session.c
Problem:
While session was getting canceled some other thread is trying to terminate
that session and moves session state to M0_RPC_SESSION_TERMINATING, which
lead to hit assert M0_POST(session->s_sm.sm_state == M0_RPC_SESSION_IDLE)
in rpc_session_cancel().
#5  in m0_arch_panic (c=c@entry=0x7f7276a91b40 <__pctx.14289>, ap=ap@entry=0x7f7268c05ce0) at lib/user_space/uassert.c:131
#6  in m0_panic (ctx=ctx@entry=0x7f7276a91b40 <__pctx.14289>) at lib/assert.c:52
#7  in m0_rpc_session_cancel (session=session@entry=0x56283c7c13d8) at rpc/session.c:863
#8  in m0_rpc_conn_sessions_cancel (conn=conn@entry=0x56283c7c1030) at rpc/conn.c:1333
#9  in rpc_conn__on_service_event_cb (clink=<optimized out>) at rpc/conn.c:1364
#10 in clink_signal (clink=clink@entry=0x56283c7c12c0) at lib/chan.c:135
#11 in …
=> CORTX-33564: Fixed panic in rpc_session_cancelled() due to session state

be/tool/main.c
Sometime ago I tried to use m0betool to dump the contents of BE stobs. It did not work out really well. Then, after a quick round of debugging with gdb, I realized that this is just because "m0_streq(expr) == 0" pattern was used there. This PR contains a patch that addresses it.
No testing was done, no tests were added in the patch. From what I've heard, we do not have system tests for the tool. Therefore, there is no way to test it except doing manual tests.
It looks like the corresponding code is not in-use (otherwise, the bug would have been discovered already). So that, it does not look like the patch could break anything that is in-use.
<details>
<summary>Click here to see the pull request template </summary>
-  For Feature, Post …
=> be/tool: Do not check the value of streq agains 0

rm/st/wlock_helper.c
Problem: rm_write_lock_put() releases the distributed lock, taken by
rm_write_lock_get(). It also finalises and frees "write lock
context" (struct wlock_ctx) that contains all the information necessary to
interact with resource manager. But it is possible that requests the revoke this
lock are processed concurrently (and, worse, they can arrive later).
This is a temporary fix. It adds some delay before finalising the write lock context.
Better solution is needed in future. But since this issue is in UT code, we will
use this fix now.
Similar problems in https://github.com/Seagate/cortx-motr/pull/1761
-  [ ] Coding conventions are followed and …
=> Fixing m0d-ut:cs-rconfc-fatal

lib/memory.c
Removed  M0_ENTRY and M0_LEAVE from m0_alloc
=> CORTX-33021 : [F-58E]: Avoid redundant logs, improve log relevance: Motr

cas/cas.h, cas/service.c, dtm0/fop.c, motr/ut/idx_dix.c
- Currently each DTM0 log record contains m0_cas_op as a payload, but m0_cas_op structure does not contain operation type. 
-  So that each REDO packet is treated as CAS PUT by default. In order to recover CAS DEL we need to distinguish the CAS 
-  operation type on the REDO receiver side during recovery process.
-  introduce a new structure that contains operation type (RPC opcode can be used) and m0_cas_op. This structure is serialized using XCODE and stored in DTM0 log as a payload. During recovery process this payload is sent as a part of REDO packet. The REDO receiver should de-serialize this payload
-  [ x] Coding conventions are followed and code is consistent
Checklist for …
=> CORTX-33605: Support DTM0 recovery for CAS DEL operations

cas/service.c
Problem:
Some time ago Hare was not updating devices state during
DTM0 recovery and they were still in OFFLINE state. In order
to process incoming REDO msgs and unblock working on DTM0
recovery we allowed operating on CAS OFFLINE devices, that
was a temporary workaround.
But logically it's not correct to operate with OFFLINE devices.
Solution:
Now Hare updates the state of devices that belong to the
recovering process. So that we can remove OFFLINE CAS device
state from allowed states for operating.
=> cas/service: forbid operating on sdevs in OFFLINE state

cob/cob.c, cob/cob.h, cob/ut/bytecount.c, sss/process_foms.c
Problem:
out_keys and out_recs are supposed to be freed by the caller of m0_cob_bc_entries_dump().
These were not being freed, which caused a memory leak every time bytecount was fetched.
Solution:
Changed the approach in m0_cob_bc_entries_dump() to take buffer pointers,
so the caller can just send pointer to structures in the stack and skip allocating on the heap.
=> CORTX-33701: Fix memory leak related to m0_cob_bc_entries_dump()

cob/cob.c, cob/cob.h, cob/ut/cob.c, ioservice/cob_foms.c, ioservice/io_foms.c, ioservice/ut/bulkio_ut.c, ioservice/ut/cob_foms.c, sns/cm/storage.c
Fix memory leaks for m0_cob_alloc in cob-ut,cob-foms-ut,bulk-client-ut and bulk-server-ut.
=> CORTX-33661 : Analyse and fix memory leaks for cob module using cob-ut and cob-foms-ut

scripts/provisioning/plugins/pretty_print.py
Signed-off-by: Zoheb Khan <zoheb.khan@seagate.com>
- fixing the python codacy issue of using type() instead of isinstance() for a typecheck.
- using isinstance() instead of type() for a typecheck.
=> CORTX-33681 fixing the Codacy issue of using type() instead of isinstance() for a typecheck

motr/st/utils/sns_repair_motr_quiesce.sh, net/test/demo/demo-list-nids.sh
Signed-off-by: Zoheb Khan <zoheb.khan@seagate.com>
- fixing double quote issue under file sns_repair_motr_quiesce.sh
=> CORTX-30751- fixing double quote issue under sns_repair_motr_quiesce.sh

scripts/gdb/gdb-extensions.py
Problem :
while fixing a codacy warning we made some of the method
static to overcome the warning due to which gdb
extensions was throwing error.
Solution:
Removed the self parameter, as static functions do not need them 
Gdb extension throwing error
Removed the self parameter, as static functions do not need them 
=> CORTX-33735: Gdb extensions throwing error

doc/CORTX-MOTR-ARCHITECTURE.md
Problem: 
Codacy warning during the pre merge of CORTX-33703
Solution:
Fixed the warning during the pre-merge job.
Signed-off-by: Rohan Dhodare <rohan.v.dhodare@seagate.com>
-  Warn when the spacing between a list item’s bullet and its content violates.
-----
[View rendered doc/CORTX-MOTR-ARCHITECTURE.md](https://github.com/RohanDhodare/cortx-motr/blob/CORTX-33702/doc/CORTX-MOTR-ARCHITECTURE.md)
=> CORTX-33702: Codacy Cleanup : Warn when the spacing between a list item’s bullet and its content violates.

scripts/install/usr/libexec/cortx-motr/motr-server
- Motr should support separate log device for deployment
1: In dev environment, Hare provides the LOG device and LOG device size in /etc/sysconfig/m0d-0x7200000000000001\:0x2
as below
...................XX......................
[root@ssc-vm-g4-rhev4-1201 cortx-motr-1]# cat  /etc/sysconfig/m0d-0x7200000000000001\:0x2
MOTR_M0D_EP='inet:tcp:10.230.244.166@21003'
MOTR_HA_EP='inet:tcp:10.230.244.166@22001'
MOTR_PROCESS_FID='0x7200000000000001:0x2'
MOTR_BE_SEG_PATH='/dev/loop9'
MOTR_NODE_UUID='fdc5d3d6-11dc-11ed-af73-566fcce40abf'
MOTR_LOG_PATH='/dev/loop8'
MOTR_LOG_SIZE='1073741824'
...................XX...........................
2: Motr then uses these MOTR_LOG_PATH, MOTR_LOG_SIZE in motr-server while calling mkfs, m0d commands for ios services
Ex: 
1: For confd, don't use   MOTR_LOG_PATH, …
=> CORTX-33595: Motr should support separate log device for deployment

scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
warning fixed : "subprocess call with shell=True identified, security
issue.
- We are getting a critical codacy warning, "subprocess call with shell=True identified, security
issue."
-  We have set shell=False, however after doing that we are able to solve the critical error but we get another warning 
of low severity which needs to be manually verified and ignored. The reason of getting this new new warning is explained 
in the pr.
=> CORTX-33346: Codacy Code cleanup

doc/HLD-Data-Block-Allocator.md, doc/HLD-OF-Motr-LNet-Transport.md, doc/HLD-Version-Numbers.md, doc/HLD-of-FDMI.md, doc/HLD-of-FOL.md, doc/HLD-of-Metadata-Backend.md, doc/HLD-of-Motr-Caching.md, doc/HLD-of-Motr-HA-nterface.md, doc/HLD-of-Motr-Lostore.md, doc/HLD-of-Motr-Network-Benchmark.md, doc/HLD-of-Motr-Object-Index.md, doc/HLD-of-Motr-Spiel-API.md, doc/HLD-of-SNS-Repair.md, doc/HLD-of-SNS-client.md, doc/HLD-of-distributed-indexing.md, doc/ISC-Service-User-Guide, doc/ISC-Service-User-Guide.md, doc/Motr-Epochs-HLD.md, doc/Motr-Lnet-Transport.md
Signed-off-by: Swatid <swati.dhotarkar@seagate.com>
-This PR uploades markdown files to motr/doc folder.
-----
[View rendered doc/HLD-OF-Motr-LNet-Transport.md](https://github.com/swatid-seagate/cortx-motr/blob/New-markdownfile-upload/doc/HLD-OF-Motr-LNet-Transport.md)
[View rendered doc/HLD-Version-Numbers.md](https://github.com/swatid-seagate/cortx-motr/blob/New-markdownfile-upload/doc/HLD-Version-Numbers.md)
[View rendered doc/HLD-of-FDMI.md](https://github.com/swatid-seagate/cortx-motr/blob/New-markdownfile-upload/doc/HLD-of-FDMI.md)
[View rendered doc/HLD-of-FOL.md](https://github.com/swatid-seagate/cortx-motr/blob/New-markdownfile-upload/doc/HLD-of-FOL.md)
[View rendered doc/HLD-of-Metadata-Backend.md](https://github.com/swatid-seagate/cortx-motr/blob/New-markdownfile-upload/doc/HLD- …
=> Uploading markdown files to doc folder

scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
- with cortx-k8s 0.9 version, data nodes string is changed
due to which update of config parameters in mini provisioner
failed.
- Updated the data nodes array append condition
=> CORTX-33774: Observed multiple core dumps and m0_panic with small load

scripts/install/usr/libexec/cortx-motr/motr-cleanup, scripts/jenkins/motr-hare-1node-cluster.groovy
Since Motr-Hare-Single-Node-Cluster-Deployment-On-Rocky-Linux
will be used as a pre merge job we need to remove the parameters
that it accepts and run the job on dedicated machines.
Cannot give parameters to pre merge job Motr-Hare-Single-Node-Cluster-Deployment-On-Rocky-Linux.
Modified the job to run on dedicated machines.
=> CORTX-32897: Support default parameters for pre-merge job

be/btree.c, doc/sm/index.rst
- Add tree type in node header and add check for h_tree_type in invariant of btree
- Assign tree type to `h_tree_type` variable while initializing a new node.
- Added check in node invariant to ensure this field is populated.
- Fixed one typo error in doc/sm/index.rst file.
=> CORTX-33505: Add tree type in node header of btree node.

scripts/jenkins/dtm-integration.groovy
This script will compile the code with dtm-enable flag
and then run dtm integration test.
Enabled DTM integration test for pre-merge job.
The script compiles the code with dtm-enable flag and runs dtm integration test.
=> CORTX-29985: DTM integration test

rpc/conn.c
Problem :
When a RPC connection is found to be dead all RPC session's part of this connection are put to failed state.
The memory allocated to these failed sessions is freed only after shutdown.
Solution :
Once failed session is finalized and removed from connection memory allocated to it should be freed.
Signed-off-by: Jugal Patil <jugal.patil@seagate.com>
=> CORTX-33739 : Fix Memory leaks observed in rpc_session_establish

balloc/ut/balloc.c, be/extmap.c, motr/m0d.c, stob/ad.c
Analyze and fix memory leaks for emap module.
Fix memory leaks for root node of btree for balloc-ut.
=> CORTX-33741 : Analyze and fix memory leaks for emap module using s3 IOs with valgrind.

doc/HLD-of-SNS-Repair.md
Signed-off-by: Prasanna Kulkarni <prasanna.kulkarni@seagate.com>
- Codacy warning in  doc/HLD-of-SNS-Repair.md file
- [no-heading-content-indent] 
- [heading-style]
- [no-heading-content-indent] -> Removed extra space in a header.
- [heading-style] -> used atx closed formatting for headers.
-----
[View rendered doc/HLD-of-SNS-Repair.md](https://github.com/prasanna46dk/cortx-motr-prasanna/blob/CORTX-33852/doc/HLD-of-SNS-Repair.md)
=> CORTX-33852: Fix codecy issues

motr/io_req_fop.c
rbulk buffer was not protected under lock in ioreq_fop_dgmode_read().
Added lock which was missing earlier.
rbulk buffer was not protected under lock in ioreq_fop_dgmode_read() due to which panic was observed.
Added lock which was missing earlier.
=> CORTX-33725: Add lock for m0_rpc_bulk buffer(rbulk)

scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
- Deployment failure due to wrong traversing of consul conf store
Change the code so that only iterations of strings are valid and not any other structures like dictionary, list etc.
Tested with k8s branch https://github.com/keithpine/cortx-k8s/tree/CORTX-33054_consul-confstore-url
Status after deployment:
`[root@ssc-vm-g2-rhev4-3118 ~]# kubectl get pods -n default
NAME                            READY   STATUS    RESTARTS   AGE
cortx-client-0                  2/2     Running   0          61m
cortx-consul-client-n5m6f       1/1     Running   0          61m
cortx-consul-server-0           1/1     Running   0          61m
cortx-control-dd4d9b489-tv244   1/1     Running   0          61m
cortx-data-g0-0 …
=> CORTX-33927: Deployment failure due to wrong traversing of consul conf store

motr/io_nw_xfer.c
It might be possible that in degraded mode we may land up in a situation
where there are more than K failures and read_verify_is not true. In this
case, ideally, we should return proper error code (-EIO) instead of assert.
It might be possible that in degraded mode we may land up in a situation
where there are more than K failures and read_verify_is not true.
In this case, ideally, we should return proper error code (-EIO) instead of assert.
=> CORTX-33577: fix panic in degraded mode read

.xperior/testds/motr-single_tests.yaml, ioservice/io_foms.c, m0t1fs/linux_kernel/st/m0t1fs_common_inc.sh, m0t1fs/linux_kernel/st/m0t1fs_server_inc.sh, motr/st/utils/copy.c, motr/st/utils/motr_io_small_disks.sh, motr/st/utils/sns_repair_common_inc.sh, scripts/st.d/73motr-io-small-disks
Handling 'short write' in some cases, e.g. disk full.
In cases, e.g. disk full, the write request may return
with 'short write': the written count is less than requested count.
The assertion of requested write count equal to returned count is removed.
In this case, the rc value of this request is still 0. And next write
request may return -ENOSPC because of disk full.
This can be triggered with small disks and writing a lot of data into
the system.
Sometimes, the write request may return short write result, especially
in case of disk full. Please see: https://github.com/Seagate/cortx-motr/issues/1868
We don't require the I/O request to write/read all data in the request.
-  [ ] Coding conventions are followed and code …
=> Handling 'short' write in some cases, e.g. disk full.

doc/FOPFOM-Programming-Guide.md, doc/HLD-OF-Motr-LNet-Transport.md, doc/HLD-of-Catalogue-Service.md, doc/Motr-Epochs-HLD.md, doc/Motr-Lnet-Transport.md, doc/Seagate-FDMI-HLD.md, doc/motr-kv-app.md, doc/motr-object-app.md, scripts/provisioning/README.md
Signed-off-by: Rohan Dhodare <rohan.v.dhodare@seagate.com>
- Codacy warnings in below given files:
- [fenced-code-flag]
- doc/FOPFOM-Programming-Guide.md
- doc/HLD-OF-Motr-LNet-Transport.md
- doc/HLD-of-Catalogue-Service.md
- doc/Motr-Epochs-HLD.md
- doc/Motr-Lnet-Transport.md
- doc/motr-kv-app.md
- doc/motr-object-app.md
- [emphasis-marker]
- scripts/provisioning/README.md
- [code-block-style]
- doc/Running_Motr_Across_a_Cluster.md
- scripts/provisioning/README.md
- [heading-style]
- doc/Seagate-FDMI-HLD.md
- [fenced-code-flag] -> added name of programming language after  3 backquotes ```
- [emphasis-marker] -> added * before and after the word to be emphasised
- [code-block-style] -> added 3 backquote ```
- [heading-style] -> used atx-closed formatting for headings …
=> CORTX-33702: Codacy cleanup of markdown files

scripts/gdb/gdb-extensions.py
- Unable to load gdb-extensions.py. Failing with syntax errors
-  Introduce parenthesis for "print" function. Replace "long" with "int". Removed macro definition as gdb.execute() is throwing errors. User need to manually define macros at gdb command prompt. Added comments for the same inside the file. 
=> cortx-29342 - Port gdb-extensions.py to python3

fdmi/st/fdmi_test.sh, m0t1fs/linux_kernel/st/common_service_fids_inc.sh, m0t1fs/linux_kernel/st/m0t1fs_client_inc.sh, m0t1fs/linux_kernel/st/m0t1fs_common_inc.sh, m0t1fs/linux_kernel/st/m0t1fs_dix_common_inc.sh, m0t1fs/linux_kernel/st/m0t1fs_io_config_params.sh, m0t1fs/linux_kernel/st/m0t1fs_server_inc.sh, m0t1fs/linux_kernel/st/m0t1fs_sns_common_inc.sh, motr/st/utils/motr_fs.sh, motr/st/utils/sns_repair_common_inc.sh, net/test/run.sh, scripts/provisioning/roles/motr-build/files/sclo-git212.sh
Fix is added for pattern "shellcheck: Tips depend on target shell and
yours is unknown. Add a shebang or a 'shell' directive"
Shellcheck warning, "shellcheck: Tips depend on target shell and yours is unknown"
Add a shebang or a 'shell' directive"
=> CORTX-30953: [Codacy] fix shell directive problems

scripts/install/opt/seagate/cortx/motr/sanity/cortx_lnet_sanity.sh
This patch fixes some of the Codacy warnings.
warning fixed: "Double quote to prevent globing and words splitting and issues like $(...)".
Co-authored-by: Venkatesh Balagani venkatesh.balagani@seagate.com
Signed-off-by: Gaurav Gaur gaurav.gaur@seagate.com
- We see 1688 occurrences of the pattern, "Double quote to prevent globing and word splitting".
- And issues like  Use $(...) notation instead of legacy backticked `...`.
-  We are putting the variable references in double-quotes.
-  Also fixed issues like  Use $(...) notation instead of legacy backticked `...`.
=> CORTX-30751: This patch fixes some of the codacy warnings.

doc/FOPFOM-Programming-Guide.md, doc/HLD-of-Catalogue-Service.md, doc/Running_Motr_Across_a_Cluster.md, doc/motr-object-app.md
Signed-off-by: Pratik Patil <pratik.k.patil@seagate.com>
- Codacy warnings in below given files:
- [fenced-code-flag]
- doc/Running_Motr_Across_a_Cluster.md
- doc/FOPFOM-Programming-Guide.md
- doc/HLD-of-Catalogue-Service.md
- doc/motr-object-app.md
- [fenced-code-flag] -> added name of programming language after  3 backquotes ```
-----
[View rendered doc/FOPFOM-Programming-Guide.md](https://github.com/Garuda5611/cortx-motr/blob/CORTX-33978/doc/FOPFOM-Programming-Guide.md)
[View rendered doc/HLD-of-Catalogue-Service.md](https://github.com/Garuda5611/cortx-motr/blob/CORTX-33978/doc/HLD-of-Catalogue-Service. …
```
=> CORTX-33978- codacy cleanup: Fixed codacy formatting issues

motr/client_init.c
Signed-off-by: Rahul Kumar <rahul.kumar@seagate.com>
The addb client logs in rgw container is generating in wrong directory (rgw_debug). This "rgw_debug" directories meant for rgw crash files only. Our expectation, addb client logs should be resides in "addb_files-0x7200000000000001:0x13" directory.
-  It's required to set an environment for `M0_CLIENT_ADDB_DIR` on cortx-rgw-integration repository in `src/rgw/setup/rgw.py` at config stage.
-  In cortx-motr, `motr>client_init.c` will make use of `M0_CLIENT_ADDB_DIR` environment variable to store addb client log. 
=> CORTX-32172: Fixes ADDB client logs to bundled it in rgw support bundle

scripts/jenkins/code-coverage.groovy
Problem:
With the previous job if one of the test failed then
rest of the jobs were not executed.
Solution:
Running tests individually instead of a group.
Ignoring any failures that occur.
If one of the test failed then rest of the jobs are not executed.
Running tests individually instead of a group.
Ignoring any failures that occur.
=> CORTX-33964: Improvement in code coverage job

scripts/install/opt/seagate/cortx/motr/common/m0_utils_common.sh
- m0_ha_sim fails to locate m0hagen command while running
-  Correct the location/path pointing to m0hagen in motr/common/m0_utils_common.sh 
=> cortx-34068: Fix m0_utils_common to point to correct path of m0hagen

motr/st/utils/motr_rpc_cancel_test.sh, scripts/m0
Problem:
RPC cancel ST is failing due to m0ham utility is failing to send
the HA message to client(m0touch).
Solution:
Currently wait of 3 seconds is there between start of m0touch with
n create operations and m0ham message to do the cancel operation.
Reduced it to 1 second so that m0touch will be there when m0ham is
started.
=> st: fix failure of rpc cancel ST

sns/cm/dtrebalance/trigger_fop.c, sns/cm/trigger_fom.c, sns/cm/trigger_fop_common.c, spiel/cmd.c, spiel/ut/spiel_ci_ut.c, utils/m0confgen
This commit fixes the failures and crash seen while running spiel UTs
for sns direct rebalance.
- Fix the UTs for the new direct rebalance code
=> CORTX-32895: Fix spiel UTs for sns direct rebalance

motr/setup.c
motr/setup.c: M0_ASSERT(rctx->rc_mdstore.md_dom != NULL);
This Assert was changed to check for NULL md_dom and return -ENOENT
if check failed instead of raising a panic.
=> CORTX-33057: Error handing for asserts.

net/test/st/run-1x1.sh, net/test/st/st-bulk.sh
- Fixing Codacy issues under net/test dir
Codacy error "Double quote to prevent globing and words splitting".
We are putting the variable references in double quotes.
=> CORTX-30083: Fix Codacy issues under "net" directory

be/btree.c
- Set btree watermarks logging level to M0_ALWAYS
=> CORTX-34044: Set btree watermarks logging level to M0_ALWAYS

cas/service.c, cas/ut/client_ut.c, dtm0/fop.c, dtm0/recovery.c, layout/ut/plan.c, motr/client_init.c, motr/idx.c, motr/st/mt/mt_fom.c, motr/ut/idx_dix.c
- Some existing UTs and STs fail when DTM0 is enabled.
* The fix is to check if DTM is properly initialized. If not, let's print warning messages
and continue the operations. This is used to have UT and ST pass when DTM is enabled
when building Motr. In future, when DTM is ready to be enabled by default, these
temporary workaround should be removed.
* A REDO message (maybe along with an EOL flag) may be re-sent to participants. 
The REDO message replay must be idempotent. So checking if the eolq is ended or not
before putting the item to the queue. 
=> CORTX-29983: UT and ST fixed with DTM0

rpc/conn.c
Problem: Prior to this patch, m0_rpc_conn_ha_timer_start() was responsible for initializing
and finalizing the timer m0_rpc_conn::c_ha_timer. The old timer would be finalized
and freed and then the new timer would be allocated and initialized. This led to a memory leak because
one instance of c_ha_timer was always left.
Solution: m0_rpc_conn_ha_timer_stop() now finalizes the RPC timer c_ha_timer and
m0_rpc_conn_ha_timer_start() is modified to finalize only the timer which is not already finalized.
Checklist for …
=> CORTX-33834: Fixed rpc/conn.c m0_rpc_conn_ha_timer_start() memory leak

scripts/install/opt/seagate/cortx/motr/common/m0_spiel_sns_utils_common.sh, scripts/install/opt/seagate/cortx/motr/libexec/m0_ha_sim, utils/spiel/m0spiel
This commit adds changes in m0_ha_sim to invoke sns direct rebalance
using m0spiel utility.
- Add support to m0_ha_sim utility for executing sns direct rebalance using m0spiel utility
-  There was no need to redesign anything. This change plugs in support for sns direct rebalance to existing m0_ha_sim utility.
Tested direct rebalance with m0_ha_sim and spiel using following steps:
1) Mark device as failed.
/opt/seagate/cortx/motr/libexec/m0_ha_sim -t drive -i 12 -s failed -u m0spiel
2) Check status of device is displayed correctly as failed.
/opt/seagate/cortx/motr/libexec/m0_ha_sim -t drive -i 12 -u m0spiel
3) run dtrebalance operation using m0_ha_sim …
=> CORTX-30074: Add support to m0_ha_sim for sns direct rebalance

.xperior/testds/motr-single_tests.yaml
Since UT's are being run as a group when one of the UT fails
the regression Job in motr does not run the rest of the UT's.
Hence we want to run the UT's individually.
If one of the UT fails the rest are not executed.
Run the UT's individually instead of running them as a group.
=> CORTX-33803: Run UT's Individually

balloc/balloc.c, balloc/balloc.h
CORTX-34042 - Fix load_extents logic in balloc module.
- In exiting code, decision about group is loaded vs not loaded is taken based on
grp->bgi_extents pointer value. 
On restart if free fragment count = 0 then bgi_extents will remain NULL. 
Later when any fragment is freed up then corresponding entry in extent list 
and extent btree will be added by creating new extent using lext_create() 
api i.e le_is_alloc = true. 
The subsequent call to m0_balloc_load_extents() will find bgi_extents == NULL 
and try to load extent allocated using M0_ALLOC_ARR where le_is_alloc = false, 
but with same start/end values. 
This ends up in having overlapping entry in extent list and mismatch in fragment 
count in group info vs actual total …
=> CORTX-34042 - Fix load_extents logic in balloc module.

cas/cas.c, cas/service.c
Signed-off-by: Yeshpal Jain <yeshpal.jain@seagate.com>
- With build#935, it was observed that the memory was consumed higher than previous build and after 40+ hours of long run IO,OOM was observed,
one of the suspect for this was dtm log pruner initial changes which was recently added, to narrow down the issue, the log pruner is enabled only if DTM is enabled.
-  Enabled log pruner only if there if dtm is enabled.
=> CORTX-34151 dtm0: add redo log only if dtm is enabled

utils/m0reportbug
- Support bundle was not collecting the motr logs correctly.
- Earlier the logs were collected in tar format(The logs were compressed using tar utility)
Example: 
[root@cortx-data-g0-0 motr]# ls
motr_SBag9s2g08_7ba8990a85d38508ca9bac4ff516d3ea_motr.tar.gz
- The issue was caused due to EOS-24059.
Modified the m0reportbug script to correctly print the size of disk usage of the specified directory
-  [Y ] Coding conventions are followed and code is consistent
- [ Y] JIRA number/GitHub Issue added to PR
=> CORTX-34154: motr logs are not in compressed format

ut/m0ut.c
Disable libfab-ut if libfabric is not present.
- libfab-ut was getting executed even if the default transport was defined as lnet.
-  Disable libfab-ut when libfabric is not present. Only enable libfab-ut when libfabric is the default network transport.
=> CORTX-34165 : Disable libfab-ut if libfabric is not present.

motr/client_init.c
Issue: During startup, if data PODs are delayed, then server PODs are
restarting with error "Couldn't init storage provider"
Root Cause: During startup, radosgw calling m0_client_init() api to
initialize motr client. This api initializes different components in
order, one of which is IL_IDX_SERVICE. Initialization of this service is
failing with -EIO OR -EPROTO, as data PODs are not yet up.
Solution: During startup, if PODs are started in out of order, then
server POD should not crash. Added a retry mechanism in initialization
of IL_IDX_SERVICE.
-  [ ] Coding conventions are followed and code is …
=> CORTX-33899 : Delayed Motr service start makes cortx-rgw container restart

doc/motr-developer-guide.md
Signed-off-by: Pratik Patil <pratik.k.patil@seagate.com>
- CORTX-23733 - Please add additional links for easy navigation (motr-developer-guide.md)
-  Added links to other sections in the same document for easy navigation.
-----
[View rendered doc/motr-developer-guide.md](https://github.com/Garuda5611/cortx-motr/blob/CORTX-23733/doc/motr-developer-guide.md)
=> CORTX-23733 - Improved links in developers guide (motr-developer-guide.md)

net/libfab/libfab.c
Fix Codacy errors for net/libfab/libfab.c
-  Fix Codacy errors for net/libfab/libfab.c
=> CORTX-26613 : Fix Codacy errors for net/libfab/libfab.c

motr/st/utils/cat.c, motr/st/utils/client.c, motr/st/utils/helper.c, motr/st/utils/helper.h, motr/st/utils/motr_pver_assign_st.sh, motr/st/utils/motr_st_inc.sh, scripts/st.d/10pver-assign, utils/functions
Enable 10pver-assign ST by removing kernal level depndancies
Signed-off-by: Parikshit Dharmale <parikshit.dharmale@seagate.com>
- 10pver-assign ST was disabled for libfabric 
- Enable 10pver-assign ST in user space 
- Created new file motr/st/utils/motr_pver_assign_st.sh
- System Test is Passed
=> CORTX-34094 Enable 10pver-assign ST

motr/st/utils/motr_rmw_st.sh
- Modify 45motr-rmw ST to run with and without -G(Generate DI) option.
-  Modified RMW ST to run with and without -G option.
-  Made changes in 45motr-rmw ST to test all scenarios with and without generating DI.
=> CORTX-33051 : DI:Modify RMW ST to run with and without -G(Generate DI) option

ioservice/io_foms.c, motr/io_req_fop.c
-  convert logs from WARN to DEBUG related to DI, during degraded read these warning logs flooding on terminal.
-  Converted logs from WARN to DEBUG.
=> CORTX-34311 : convert logs from WARN to DEBUG related to DI

be/log.c, configure.ac, debian/control, debian/cortx-motr-dev.install, debian/cortx-motr.install, lib/misc.c, stob/ut/domain.c, stob/ut/stob.c, xcode/xcode.c, xcode/xcode.h
Fix some minor build issues on Ubuntu 22.04 (Jammy).
Note: when building .deb packages, use
`export DEB_BUILD_MAINT_OPTIONS=optimize=-lto` to avoid `internal compiler error: in get_constructor, at varpool.c:311`.
Signed-off-by: Andriy Tkachuk <andriy.tkachuk@seagate.com>
Co-authored-by: Kefu Chai <tchaikov@gmail.com>
Signed-off-by: Kefu Chai <tchaikov@gmail.com>
This PR is based on https://github.com/Seagate/cortx-motr/pull/2074.
Tested `make deb` on both: Ubuntu 22.04 and 20.04.
=> Fix build on Ubuntu 22.04
