SUPPORT.md
Added SUPPORT.md to keep in line with GitHub Health Check guidelines.
Signed-off-by: Saumya Sunder <saumya.sunder@seagate.com>
=> Added SUPPORT.md

.xperior/testds/motr-single_tests.yaml, doc/data-flow/Makefile, doc/data-flow/conf.py
=> More Renaming Mero to Motr 

doc/reading-list.md
=> Add client.h to reading list

be/tool/beck.c
=> EOS-13825 be/tool/beck: Update FLOG to print status of last operation

scripts/install/opt/seagate/cortx/motr/libexec/motr_data_recovery.sh
Issue:
Test performs power cycle while data recovery is running.
After power up, the data recovery script finds that /var/motr
directory was not mounted. And hence it can't find gen_id.
Fix:
Always mount /var/motr directory irrespective of motr recovery state.
Signed-off-by: Rakesh Vaghasiya <rakesh.vaghasiya@seagate.com>
=> EOS-13877: fix missing gen_id file after power cycle during data recovery

doc/reading-list.md
Added links to examples for how to use the client API
=> Links to cp, cat, and kv client examples

doc/reading-list.md
Added a useful link to an existing document.
=> Info for using m0cp, m0cat, m0kv

spiel/cmd.c
Also m0_fop_put() a fop after m0_rpc_post()
=> EOS-14165 Only finalize rpc link when its fops are done

utils/m0reportbug
Compressed(to .xz format) and collected addb-files of server(m0d) and client(s3server) to motr support bundle.
=> EOS-14279 m0reportbug:  add addb files to support bundle

utils/m0reportbug
* collected  /var/log/motr-rpm-conf-update.log into support bundle.
* Collect journal logs in case --list-boots doesn't list anything.(i.e. server
is not rebooted since installed)
=> EOS-14777: Fixed error from m0reportbug 

Makefile.am, README.rst, doc/motr-developer-guide.md, motr/client.h, motr/examples/.gitignore, motr/examples/Makefile.sub, motr/examples/example1.c, motr/examples/setup_a_running_motr_system.sh
=> EOS-14766 A developer guide document.

addb2/addb2.c
=> EOS-15117: fix a bug in EOS-2040 fix.

doc/Quick-Start-Guide.rst
Signed-off-by: Venkataraman Padmanabhan <venkataraman.padmanabhan@seagate.com>
=> Motr updates - Added the Tested by section

doc/Quick-Start-Guide.rst
Tested and verified again.
* Some more explanation for EPEL (needed by ansible)
* run-ut -l and run-ut -t
=> Quick Start Guide Update

doc/Quick-Start-Guide.rst
Signed-off-by: Venkataraman Padmanabhan <venkataraman.padmanabhan@seagate.com>
=> Updating Quick-Start-Guide with formatting changes. rst

net/libfab/libfab.c
Signed-off-by: Jaydeep Mohite <jaydeep.mohite@seagate.com>
=> EOS-14941:Added changes for domain_fini

README.rst
=> Linking to provisioning guide

scripts/provisioning/README.md
Add a note about `m0vg rsync` command and when it is useful.
=> provisioning/README: add note about m0vg rsync cmd

Makefile.am, doc/motr-developer-guide.md, motr/client.h, motr/examples/.gitignore, motr/examples/Makefile.sub, motr/examples/example2.c, utils/.gitignore
This example shows how to do:
* index create
* index put
* index get
* index delete
/doc/motr-developer-guide.md is updated with the guide.
=> index operation example for Motr

net/libfab/libfab.c
Signed-off-by: Jaydeep Mohite <jaydeep.mohite@seagate.com>
=> EOS-15860, EOS-15861 Libfabric: Added buffer event notify and buffer, segment size related API's

net/libfab/libfab.c
=> EOS-14948 Libfabric : Implement transfer machine start and stop using libfabric APIs

configure.ac
=> build: bump version number to 1.0.1

bindings/go/mio/mio.go
Add [io.WriterAt](https://golang.org/pkg/io/#WriterAt) / [io.ReaderAt](https://golang.org/pkg/io/#ReaderAt) interfaces implementations.
=> go/mio: add io.ReadAt() / io.WriteAt() implementations

motr/init.c, net/libfab/libfab.c
- API to decode node and port number from given ep_name
=> [EOS-15552] Implement API for endpoint address decode

hsm/m0hsm_api.c
Fix error handling at m0hsm_create().
=> hsm: fix error handling at m0hsm_create()

motr/magic.h, net/libfab/libfab.c, net/libfab/libfab_internal.h
=> EOS-16638 Libfabric : Fix network-bulk ut using libfabric

addb2/dump.c
During analysis of large ADDB file user may be interested in
particular, but not all, ADDB records, e.g. between start
and end time of a test.
This patch introduces two parameters '-s', start time,
and '-e', end time, in nanoseconds since the Unix epoch time.
It reduces conversion time and the size of resulting dump file.
Usage:
$ m0addb2dump -f -s 1608826868000000000 -e 1608826893000000000 -- "$ios_addb_stob" > dumps_${pid}.txt
=> Added time-window parameters for m0addb2dump utility.

be/dtm0_log.h
Have tried to cover following things as a part of DLD of DTM0 log.
1. Defined TXR log format
2. Added Initial list of interface API
3. Added Initial list of operation API
4. Possible use cases has been described.
=> EOS-16458 [DTM0] DTM0 LOG DLD

dtm0/doc/dtx.txt
The patch introduces a document that describes the changes
that are needed to be done on the client side
(Motr client, DIX, CAS) in order to enable DTM there.
=> EOS-16421: [DTM0] Add client SM DLD.

Makefile.am, configure.ac, sns/parity_math.c, sns/parity_math.h
- Added check for Intel ISA library during Motr code compilation
=> EOS-16625 ISA-L : Add check for library during compilation

dix/cm/cm.c, dix/req.c
=> Removing unused code.

scripts/install/opt/seagate/cortx/motr/conf/setup.yaml
- JIRA: EOS-16010
- edited setup.yaml as per LDRr2 requirement
=> provisioner: setup.yaml updated with new provisioner format

doc/Quick-Start-Guide.rst
Signed-off-by: Venkataraman Padmanabhan <venkataraman.padmanabhan@seagate.com>
=> Update the Tested By section in the Quick-Start-Guide.rst

doc/Quick-Start-Guide.rst
Signed-off-by: Patrick Hession <patrick.hession@seagate.com>
=> Update Quick-Start-Guide.rst added Patrick Hession

Makefile.am
- provisioner_cluster.json confstore example added 
=> provisioner: provisioner_cluster.json added in rpm install

scripts/addb-py/chronometry/md_req.py
Support index operations where actions are done on meta
indices only.
=> EOS-17032: support meta operations in MD timelines scripts

configure.ac
=> build: bump rpm version number to 2.0.0

motr/iem.c, motr/iem.h, motr/ut/cs_ut_main.c
One review comment change fix while merging the code in cortx-1.0 is captured in this PR for merging this code in main branch.
=> Fix IEM alert formatting.

net/libfab/libfab.c, net/libfab/libfab_internal.h, net/module.c, net/test/ut/commands.c
=> EOS-17311 Libfabric : Add support for iovec (buffers with scatter gather list) read, write and msg

format/format.c, motr/iem.c
IEM message description is modified in case of BE error.
=> IEM: changes to message for BE error. (#434)

configure.ac, cortx-motr.spec.in, lib/trace.h, lib/user_space/user_x86_64_atomic.h, m0t1fs/linux_kernel/dir.c, m0t1fs/linux_kernel/inode.c, motr/linux_kernel/m0tr_main.c, net/lnet/ut/lnet_ut.c, ut/linux_kernel/m0ut_main.c
* Define PAGE_SIZE, PAGE_SHIFT
* Change arch from x86_64 to aarch64
* temporarily added MODULE_LICENSE()
=> [ARM porting] Required code changes to fix build issues

sns/parity_math.c, sns/parity_math.h
- Implemented isal_recover() function
- Created another function to generate decoding codes tables for
recovery.
=> EOS-18136: ISA-L - Implement recover function

ioservice/ut/bulkio_common.h, net/libfab/libfab.c, net/libfab/libfab_internal.h
=> EOS-18056 : Fix bulk-server-ut and bulk-client-ut.

Makefile.am, scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py, scripts/install/opt/seagate/cortx/motr/bin/motr_setup, scripts/install/opt/seagate/cortx/motr/bin/motr_setup.py
=> EOS-18067 : Mini-provisionor changes in cortex-motr repo

be/dtm0_log.c, be/dtm0_log.h, be/ut/dtm0_log_ut.c
Code changes for EOS-16473 and EOS-17618.
=> EOS-16473,EOS-17618: [DTM0] Implement persistent log

net/libfab/libfab.c, rpc/rpc.c, sns/cm/repair/ut/net.c
=> EOS 18061 - Fix spiel ut failures for libfabric transport

net/libfab/libfab.c, net/libfab/libfab_internal.h
=> EOS-18762 : Use two local endpoints for two way connection establishment in libfabric transport

scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py, scripts/install/opt/seagate/cortx/motr/bin/motr_setup, scripts/install/opt/seagate/cortx/motr/conf/examples/provisioner_cluster.json
…a logical disk group from confstore and configure using motr_setup
=> EOS-18144: Modified motr mini provisioner according to new conf store keys

be/dtm0_log.c, be/dtm0_log.h, dtm0/dtx.c, dtm0/dtx.h, dtm0/fop.c, motr/idx.c
The patch adds finalization of DTX after the client finished
working with it.
Also, the patch addresses CR comments for the previous patch
in the series.
=> [DTM0] EOS-18811: Finalize DTX when it enters DONE state.

addb2/dump.c, addb2/identifier.h, cas/service.c, dtm0/Makefile.sub, dtm0/addb2.h, dtm0/dtx.c, dtm0/fop.c, dtm0/fop.h, dtm0/service.c, motr/idx.c
=> [DTM0] EOS-18958: Add ADDB2 instrumentation

Makefile.am, scripts/install/opt/seagate/cortx/motr/conf/motr.post_install.tmpl, scripts/install/opt/seagate/cortx/motr/conf/motr.prepare.tmpl
- Add all provisioner templates in rpm
- templates should have all the keys that are been used in that particular stage.
=> EOS-18144 : Add templates in rpm

doc/Quick-Start-Guide.rst
Signed-off-by: christina-00 <christina.ku@seagate.com>
=> Reference $HOME instead of root

be/dtm0_log.c, be/dtm0_log.h, be/ut/dtm0_log_ut.c, cas/client.c, dix/req.c, dix/req_internal.h, dtm0/dtx.c, dtm0/dtx.h, dtm0/fop.c, dtm0/helper.c, dtm0/helper.h, dtm0/it/all2all/all2all, dtm0/service.c, dtm0/service.h, dtm0/tx_desc.c, dtm0/ut/main.c, motr/client_init.c, motr/idx.c, motr/idx.h, motr/magic.h, motr/motr-pub.api, motr/ut/idx.c, motr/ut/idx_dix.c
A PR for overall review of the DTM0 (the happy-path part). 
The branch (`dtm0-main2main`) will be the place to submit the corresponding fixes (coding style issues and so on).
The PR should remain in the draft state. Later on we will submit a separate PR to be reviewed by the upstream gatekeepers.
UPDATE: As per discussions with @just-now , we are merging this PR into dtm0-main. After that, a separate "official" `dtm0-main -> main` PR will be open for review.
=> [DTM0] DTM0 patch for main (review board)

scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py, scripts/install/opt/seagate/cortx/motr/bin/motr_setup
WIP: Some more fixes to mini provisioner tkt EOS-18144
=> EOS-18144 provisioner:  Added support for prepare phase

scripts/install/opt/seagate/cortx/motr/conf/motr.post_install.tmpl, scripts/install/opt/seagate/cortx/motr/conf/motr.prepare.tmpl
=> EOS-18144 scripts: Added 'TMPL_POOL_TYPE' in template files

motr/m0crate/Makefile.sub, motr/m0crate/btree_without_tx_seg.c
=> EOS-19208: remove tx and segment dependency from btree code for benchmark.

dtm0/it/all2all/README.md
Signed-off-by: Vaibhav Paratwar <vaibhav.paratwar@seagate.com>
-----
[View rendered dtm0/it/all2all/README.md](https://github.com/vaibhavparatwar/cortx-motr/blob/patch-4/dtm0/it/all2all/README.md)
=> Added Troubleshooting section

dtm0/it/all2all/README.md, dtm0/service.c, motr/st/utils/ha_msg_send.sh, motr/ut/idx_dix.c
-----
[View rendered dtm0/it/all2all/README.md](https://github.com/Seagate/cortx-motr/blob/devel/EOS-20516/dtm0/it/all2all/README.md)
=> EOS-20516: fix meaningful Codacy warnings for PR-561

doc/Quick-Start-Guide.rst
Signed-off-by: christina-00 <christina.ku@seagate.com>
=> Add tested by

be/dtm0_log.c, be/dtm0_log.h, be/ut/dtm0_log_ut.c, cas/service.c, dtm0/fop.c, dtm0/fop.h, dtm0/service.c, dtm0/ut/main.c
There is a change in the checkin branch for dtm0 post merge. This PR is opened in continuation and to apply the changes and review comments from https://github.com/Seagate/cortx-motr/pull/632
=> EOS-18924 Code changes and code review comment fixes for handling persistent messages in dtm0

dtm0/it/all2all/README.md
Known issues added in all2all README.
-----
[View rendered dtm0/it/all2all/README.md](https://github.com/rajatpatil98/cortx-motr/blob/patch-1/dtm0/it/all2all/README.md)
=> [DTM0] Document known issues for a2a

doc/sm/index.rst
Fix sm/index.rst rendering issues, minor wording issues and list formatting issues.
=> doc: fix sm/index.rst rendering issues

motr/client.h, motr/st/utils/cat.c, motr/st/utils/copy.c, motr/st/utils/helper.c
Fix errors handling and coding style issues.
=> st/utils: fix err handling & coding style issues

btree/btree.c, btree/btree.h, btree/internal.h
Hi Everyone,
I am raising this draft PR for the first part i.e. tree-create.
=> [WIP] EOS-20302: Part 1. Implement btree operations tree-create

.xperior/testds/motr-single_tests.yaml
=> Fix timeout for 17sss-st-test

btree/btree.h
=> Added btree operation return codes.

btree/btree.c
=> EOS-20302: Implement btree_destroy

btree/btree.c
=> EOS-20306: Btree KV get implementation.

doc/motr-in-prose.md
-----
[View rendered doc/motr-in-prose.md](https://github.com/Seagate/cortx-motr/blob/andriytk-patch-2/doc/motr-in-prose.md)
=> doc: clarify examples of pools at motr-in-prose.md

Makefile.am, configure.ac, cortx-motr.spec.in, motr/client.c, motr/client.h, motr/client_internal.h, motr/ut/Makefile.sub, motr/ut/protection_info_checks.c, scripts/provisioning/roles/motr-build/vars/RedHat.yml, scripts/provisioning/roles/motr-runtime/vars/RedHat.yml, ut/m0ut.c
EOS-20758: Implementation of API using current S3 implementation
as reference includes MD5 - client side
Problem:
Do the implemnetation for motr client api,
implementation include calculations for MD5 checksums and digest
and the test code.
Do changes rquired for code compilation.
Solution:
Done the implementation for calculating MD5checksums and digest
Written code for UT.
Integrated motr code with openssl MD5 library
so that newly added code for data protection
can compile.
Please refer following PR for review comments
https://github.com/gshipra/cortx-motr/pull/2/
Testing
Code compiled and newly written UT passed.
./scripts/m0  run-ut -t pi_ut
----- run_ut -t pi_ut -----
START Iteration: 1 out of 1
pi_ut
m0_pi_checks_case_one_two                       0.00 sec    0 B …
=> EOS-20758: Implementation of API using current S3 implementation as reference includes MD5 - client side

scripts/install/etc/motr/genders, scripts/install/usr/libexec/cortx-motr/motr-service.functions, utils/m0setup
Added imeta_spare_units in genders to support
spare=0 in meta pool version.
=> EOS-20923: Meta pool version changes for 1+2+0

.github/stale.yml
Updated stale-bot notification as per codeowners
=> Updated stale-bot notification as per codeowners

cas/service.c
**FOL record details**
fol record contains a list of all FOL record fragments in a record.
```
struct m0_fol_rec {
...
struct m0_tl  fr_frags;
....
} 
```
Each fol frag contains pointer to the data (fol record fragment for a fop).
```
struct m0_fol_frag {
...
void  *rp_data;
...
}	
```
fol record fragment for a fop (struct m0_fop_fol_frag) contains fop opcode and fop data pointer,
In KVS data case fop data pointer == m0_cas_op  pointer, so we could access kv records(struct m0_cas_rec). 
While exploring the fol record content stdout one issue noticed as,
**What is the issue?**
In CAS_DONE phase kv record buffers are finalized and no longer accessible after this phase, because of kv buffer finalization we could not access buffers in  M0_FOPH_FOL_REC_ADD phase. In M0_FOPH_FOL_REC_ADD phase …
=> EOS-20820 cas/service: add kv pairs to FOL

btree/btree.c, btree/btree.h
=> EOS-20309: add m0_btree_iter() function.

btree/btree.c, btree/internal.h
Added ut which will perform put, get, iterate and delete operations on the same
btree but across multiple threads to trigger corner-case scenarios.
=> Eos-20308 Added multi-threaded ut for KV operations.

btree/btree.c
Changes in put operation and generic_move function
-Handling some corner cases
=> Handle corner cases in put operation and generic_move 

btree/btree.c, btree/btree.h
This is a draft pull request.
Please suggest additional changes or modifications.
=> Transaction support in node functions

btree/btree.c, btree/btree.h
Implemented state machine for delete operation of btree.
- tested btree del operation by inserting 1million key-values in sequential and random manner and deleted it using implemented delete operation.
=> Eos 20317: Implement btree key-value operations kv-del

scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py, scripts/install/opt/seagate/cortx/motr/bin/motr_setup
transport type check in motr_config in mini prov
=> EOS-18057: Verification of cortext Porvisionor changes done for Libfabric transport

btree/btree.c, btree/btree.h, sm/op.c, sm/sm.c, sm/sm.h, ut/m0ut.c
The following changes include the implementation for m0_btree_open().
=> EOS-20305: Implement code for m0_btree_open()

btree/btree.c
The code will run tree operations in parallel in multiple threads. Also the ut code will run KV operations in parallel on multiple threads over multiple trees.
In addition the support for slant in the ut is also added.
=> Eos 20314: Add ut to test KV operations over multiple threads on multiple trees.

btree/btree.c, motr/magic.h
=> EOS-21218: Added active and lru node descriptor lists.

bindings/go/mio/mio.go
m0_layout_find_by_objsz() was introduced recently at commit 56d4b36, so use it directly instead of custom getOptimalUnitSz().
=> go/mio: use new m0_layout_find_by_objsz() API

btree/btree.c, btree/btree.h
Added a few lines of documentation to describe the operation of the routines present in btree.h
=> Added description to the btree function prototypes in btree.h

btree/btree.c, btree/btree.h
=> Reduced parameter count for macro M0_BTREE_OP_SYNC_WITH_RC.

btree/btree.c
Implemented function definition for some empty functions:
- node_header_verify()
- node_footer_verify()
- node_fix()
Updated function definition of :
- node_put()
- node_free()
=> EOS-21217: Implementation of node_*() functions

btree/btree.c
Changes related to memory free for struct m0_btree_oimpl *oi during each operation :
-added one more phase : P_FINI
Changes related to locks:
-added flag in oi as, oi structure will exist during entire operation
due to above changes.
-the flag will determine if thread has acquired the lock or not.
fixed bug in P_CHECK.
=> Eos 21219 : Changes related to LOCKS

btree/btree.c, btree/btree.h
=> EOS-21218: Node descriptor management

ioservice/io_foms.c, layout/layout.c, motr/client.h, motr/idx.c, motr/idx_dix.c, scripts/install/etc/sysconfig/motr
PR to merge commits from main to stable branch.
=> Merge to stable branch

btree/btree.c
Adding lock unlock node mechanism in kv operations  for accessing nodes while traversing the tree.
=> Node lock mechanism

scripts/install/opt/seagate/cortx/motr/bin/motr_setup, scripts/install/opt/seagate/cortx/motr/libexec/motr_cfg.sh
=> EOS-22162: config script changes for lvm names.

motr/client.h, motr/client_internal.h, motr/cob.c, motr/io_nw_xfer.c, motr/io_req_fop.c, motr/obj.c, motr/st/utils/cat.c, motr/st/utils/client.c, motr/st/utils/helper.c, motr/st/utils/helper.h, motr/st/utils/motr_dgmode_io_st.sh, motr/st/utils/motr_st_inc.sh, pool/pool.c, pool/pool_machine.c, scripts/install/opt/seagate/cortx/motr/bin/motr_setup, scripts/install/opt/seagate/cortx/motr/libexec/motr_cfg.sh
merge from Motr main to stable.
=> Merge from Motr main to stable

btree/btree.c
Add randomizer for every run of the ut based on current time.
=> Add code for different seed to be used in RBG for every run of btree ut.

btree/btree.c
This PR is dependent on https://github.com/Seagate/cortx-motr/pull/814
Checking node_count_rec ==0 before working on node to check if node is still valid.
=> Node count check

btree/btree.c
=> EOS-21926 - Initial commit for remove node descriptor from ff_*()

.github/auto_assign.yml, .github/stale.yml, CODEOWNERS
=> Adding new Motr gatekeeper.

be/tx_credit.h, btree/btree.c
=> EOS-22548: Credit calculation for btree callbacks

btree/btree.c
- Updated definition of invariant
- Added expensive invariant which will validate if keys are in ascending order
=> Eos 21225: invariant update

btree/btree.c
=> Changed ut to support random thread and tree count for btree testing.

btree/btree.c
- Added structure which will store information about nodes which needs to get captured in transaction
- Renamed i_callback to i_capture
=> changes related to array which stores node which needs to be captured

be/tx.c, be/tx.h, be/tx_credit.c
=> EOS-22551: Build callback list in transaction.

.xperior/testds/motr-single_tests.yaml
=> jenkins: increase timeout value for 51kems ST

btree/btree.c
- Added P_CAPTURE phase will capture nodes in transaction.
=> Eos 22542 : Btree code changes for capturing transactions for KV Insert operation.

be/tx.h, btree/btree.c
=> EOS-22553: Capture nodes to the callback list in the transaction.

btree/btree.c
- Added l_alloc_in_used flag to determined if l_alloc has been used by put operation of not 
- According to l_alloc_in_used flag performing node_put() or node_free() operation foe l_alloc in level_cleanup
=> Changes related to node_put after P_CAPTURE phase

btree/btree.c
renamed n_delayed_free to n_be_node_valid
=> n_delayed flag changes

be/tx.c
=> EOS-22556: Release allocated memory for holding the callbacks.

btree/btree.c
=> Updated Transition states in btree-conf

btree/btree.c
=> Removing node_refcnt_update function

btree/btree.c
=> Fix trees_loaded variable's memory corruption.

be/log.c, be/log.h, be/tx.c, be/tx.h, be/tx_group.c, be/tx_group_format.c, be/tx_group_format.h, conf/obj.h, conf/objs/fdmi_filter.c, conf/onwire.h, dtm0/conf.cg, fdmi/fdmi.c, fdmi/filter.h, fdmi/flt_eval.c, fdmi/flt_eval.h, fdmi/fol_fdmi_src.c, fdmi/fol_fdmi_src.h, fdmi/source_dock_fom.c, fdmi/source_dock_internal.h, fdmi/ut/conf.cg, fdmi/ut/filter_eval.c, fdmi/ut/fol_ut.c, fdmi/ut/sd_send_not.c, fol/fol.h, ut/conf.cg, ut/diter.cg, utils/m0confgen
The following PRs:
#736 
#737 
#774 
#777
=> Merge FDMI patches to fdmi_int

btree/btree.c
Added ut changes to test KV update operation. The code is currently commented and needs to be uncommented when the code for update KV is written.
=> Initial code in ut for testing update key operation.

be/tx.c, be/ut/main.c, be/ut/tx.c
- Also includes UT for tx callback feature.
=> EOS-22555: Callback invokation on transaction commit.

btree/btree.c, btree/btree.h
=> EOS-23246: Min/Max key get implementation.

btree/btree.c
- Adding credit calculation for Update Operation
=> Eos 23143 : Credit calculation for KV UPDATE

scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py, scripts/install/opt/seagate/cortx/motr/bin/motr_setup
=> EOS-20759: Reset (Data and logs) phase of motr mini provisioner

lib/user_space/ugetopts.c, motr/m0kv/cmd_main.c
Reverts Seagate/cortx-motr#887
=> Revert "[EOS-22988] m0kv -help throwing ERROR in normal run"

btree/btree.c
Currently the btree ut multi_thread_tree_op takes a long time to complete. To
get around this the loop count for which the routine runs is decremented down to
make the loop count finish faster.
=> Decremented the loop count for ut multi_thread_tree_op

btree/btree.c
=> Return error codes instead of record's error flags in get and iter tick.

btree/btree.c
Changes in put and del routine: Returning error code in case of failure instead of calling callback
=> Return code changes

scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
Fixed motr main deployment failure
=> Eos 19064 command without exception

net/sock/sock.c
- Released ma mutex using ma_unlock() in ma__fini() after setting t_shutdown flag
- Later in ma__fini(), acquired the ma mutex again with ma_lock() and continued
the finalization of ma.
- Checked t_shutdown flag in poller() thread repeatedly in its loop.
Co-authored-by: Hua Huang <hua.huang@seagate.com>
=> EOS-6616 net/sock: Nicely shutdown poller() thread in net/sock

btree/btree.c
=> EOS-22533 : Credits for delete operation

motr/st/utils/helper.c, utils/m0reportbug
=> EOS-21983: m0reportbug binaries archive is missing on Jenkins

fdmi/plugins/fdmi_plugin_st.sh, fdmi/plugins/fdmi_sample_plugin.c, m0t1fs/linux_kernel/st/m0t1fs_common_inc.sh
* Start a Motr cluster, with defined FDMI filter and strings to match.
* Start the fdmi plugin app and wait for FDMI events.
* Do some KV operations. This will trigger FDMI events.
=> FDMI plugin ST

btree/btree.c
I have added the design documentation and psuedo codes in btree.c file.
=> EOS-22698: Design for variable sized key and value

btree/btree.c
=> Adding node interfaces for credit calculation for kv_operation

layout/plan.c
Fix and update a few comments at m0_layout_plan_build().
=> layout: fix comments at m0_layout_plan_build()

btree/btree.c
Extra validation for delete Record operation. Here after the deletes complete 
the code will try to GET and also DELETE the already deleted Key to make sure 
correct error code is returned to the caller.
=> Ut changes to test del rec validity

scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
This is the fix for main deployment failure
Added delays and retries while fetching lvm data from other nodes
=> EOS-23505_Added delay and retry in lvm fetch

motr/cob.c, motr/m0crate/crate_io.c, motr/m0crate/parser.c
Fixed below two issues with m0crate.
1)EXEC_TIME setting is not being honored
2)Memory leak in COB request object.
=> EOS-10319 - Out of memory for m0crate

.github/auto_assign.yml
Updated auto assign list for the gatekeepers
=> Update auto assign for the gatekeepers

lib/bitmap.c, lib/bitmap.h, lib/ut/bitmap.c
Add "find fist bit set" function to lib/bitmap.
=> lib: add m0_bitmap_ffs()

scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py, scripts/install/opt/seagate/cortx/motr/bin/motr_setup
=> EOS-20759: Motr Mini Provisioner Cleanup implementation

btree/btree.c
=> Add global lock in tx commit callback

btree/btree.c
=> Fix for btree ut crash.

btree/btree.c
=> UT for Variable Key size, Variable Value size.

btree/btree.c
=> UTs for Fixed Key size, Variable Value size node format.

btree/btree.c, btree/btree.h
=> Changes to m0_btree_create() to deermine node type from m0_btree_type data

btree/btree.c, btree/btree.h
=> Updated btree.h with prototype of m0_btree_update() routine.

btree/btree.c
=> Fixes for resolving compile errors.

btree/btree.c
=> EOS-23373: Support node type which has Fix Key size, Variable Value size (Implementation)

conf/st, console/st/console-st.sh, m0t1fs/linux_kernel/st/common.sh.in, m0t1fs/linux_kernel/st/m0t1fs_common_inc.sh, net/lnet/st/linux_kernel/m0lnetping.sh, net/test/demo/demo-test-run.sh, net/test/m0nettest.sh.in, net/test/m0nettestd.sh.in, net/test/st/st.sh, net/test/test-user.sh.in, net/test/test.sh, scripts/addb-py/chronometry/io_workload, scripts/addb-py/chronometry/run_corruption_task, scripts/addb-py/chronometry/run_s3_corruption, scripts/addb-py/chronometry/run_s3_task, scripts/addb-py/chronometry/run_task, scripts/addb-py/chronometry/s3_corruption_workload, scripts/addb-py/chronometry/s3_workload, scripts/install/usr/libexec/cortx-motr/motr-service.functions, sns/cm/st/repair_test.sh, spiel/st/m0t1fs_spiel_st.sh, ut/m0kut, utils/functions, utils/m0mount, utils/m0reportbug, utils/m0run, utils/modload-all.sh.in
- Removed loading and unloading of galois kernel module.
=> EOS-22444: Remove use of galois kernel module

scripts/install/opt/seagate/cortx/motr/conf/support.yaml
=> EOS-20508: Validate support bundle for Motr components

balloc/ut/balloc.c
Signed-off-by: Nihar Nayak <nihar.nayak@seagate.com>
=> "EOS-21909: unit test updates for balloc tunables."

net/bulk_emulation/mem_xprt_bulk.c, net/bulk_emulation/mem_xprt_ep.c
=> Fix "possible uninitialised" warnings.

be/alloc.h, btree/btree.c, btree/internal.h
=> Miscellaneous changes.

btree/btree.c
=> UT for btree cursor verification.

btree/btree.c
=> calling delete calllback before deleting record

btree/btree.c, lib/linux_kernel/memory.c, lib/memory.h, lib/user_space/memory.c
Currently for this PR, only single threaded UTs are working without any errors.
The Following UTs work :
multi_stream_kv_op, 
single_thread_single_tree_kv_op, 
single_thread_tree_op, 
multi_thread_tree_op, 
btree_persistence
=> Eos 22699 Variable Key Variable Value Implementation

btree/btree.c, btree/btree.h, btree/internal.h, conf/db.c
This commit captures the changes which will make the conf database use new
BTree.
=> Integrating New Btree with Conf database of Motr.

CODEOWNERS
Codeowners updated for Motr as per changes & request EOS-24265
=> Update CODEOWNERS for Motr

btree/btree.c
=> bug fix for credit calculation for delete kv operation

btree/btree.c, btree/btree.h, cob/cob.c, sm/sm.c, sm/sm.h
Changes in the code to build Motr rpms. Most of the changes are related to 
the function prototypes.
=> Code fixes to build Motr rpms.

btree/btree.c, btree/btree.h, cob/cob.c, conf/db.c
=> Changes in create and destroy credit functions to accept nr parameter

balloc/balloc.c, balloc/balloc.h, be/tool/main.c
=> EOS-24150: Integrate new btree with balloc code.

balloc/balloc.c, cob/cob.c
=> Fix btree fid to use new btree type enum.

btree/btree.c
=> EOS-23641: Add CRC support for btree.

motr/cob.c
Reverts Seagate/cortx-motr#1047
=> Revert "EOS-24831: Object deletion gives return code as ENOENT"

.github/stale.yml
Members modified for community support for Motr
=> Members modified for community support for Motr

be/io.c
The violation was detected during EOS-25005 patch testing with
> sudo utils/m0run -dvalgrind-helgrind m0ut -- -t be-ut:io_sched
Root cause: m0_chan was being locked from under be/io_sched lock in one
place and be/io_sched lock was taken from under m0_chan lock in another
place.
The bug is resolved by avoiding locking m0_chan under be/io_sched lock.
The message that shows the lock order violation:
Thread #38: lock order "0x5703A80 before 0x26B56F78" violated
Observed (incorrect) order is: acquisition of lock at 0x26B56F78
at 0x4C2DCE0: mutex_lock_WRK (hg_intercepts.c:909)
by 0x4C31B3D: pthread_mutex_lock (hg_intercepts.c:925)
by 0x102843A6: m0_arch_mutex_lock (umutex.c:56)
by 0x1026FCF5: m0_mutex_lock (mutex.c:55)
by 0x10265F56: m0_chan_lock (chan.c:70)
by 0x10266474: …
=> EOS-25076 be/io_sched: avoid si_wait/bis_lock lock order violation

balloc/balloc.c
Changes are done in balloc to:
1) Write the entire m0_balloc structure before initialize the GD and GE btrees
contained in this structure.
2) The sb_update only writes the data in m0_balloc which is between the magic
header and footer only.
- Bootup of cluster having Motr with new BTree would crash.
-  Writing of the SuperBlock would persist unwanted data thus causing 
issues during next cluster boot.
-  Coding conventions are followed and code is consistent
- Testing was performed with RPM
None
=> Change to fix cluster boot-up issues.

doc/Quick-Start-Guide.rst, doc/motr-developer-guide.md, doc/motr-kv-app.md, doc/motr-object-app.md, fdmi/plugins/motr-fdmi-app.md
Update Tested by section on Quick Start Guide
Separate Object, Key-value and FDMI sample apps in different files
Update Developer Guide
-----
[View rendered doc/motr-developer-guide.md](https://github.com/lia54/cortx-motr/blob/main/doc/motr-developer-guide.md)
[View rendered doc/motr-kv-app.md](https://github.com/lia54/cortx-motr/blob/main/doc/motr-kv-app.md)
[View rendered doc/motr-object-app.md](https://github.com/lia54/cortx-motr/blob/main/doc/motr-object-app.md)
[View rendered fdmi/plugins/motr-fdmi-app.md](https://github.com/lia54/cortx-motr/blob/main/fdmi/plugins/motr-fdmi-app.md)
=> Updating documentation for creating object, key-value and FDMI apps

.xperior/testds/motr-single_tests.yaml, conf/objs/fdmi_filter.c, fdmi/plugins/fdmi_plugin_st.sh, fdmi/plugins/fdmi_sample_plugin.c, m0t1fs/linux_kernel/st/m0t1fs_common_inc.sh, scripts/st.d/67fdmi-plugin-multi-filters
Reverts #1084
Accidentally merged! Sorry!
=> Revert "EOS-24863: FDMI Test scripts modified to have multiple FDMI filters"

scripts/install/usr/libexec/cortx-motr/motr-mkfs, scripts/install/usr/libexec/cortx-motr/motr-server, scripts/install/usr/libexec/cortx-motr/motr-service.functions
- updated mkfs and server file to fetch data from
$local key which is updated in motr mini prov
- add conf option to mkfs to fetch confd.xc file
=> EOS- 24574

btree/btree.c, btree/btree.h, btree/internal.h
=> EOS-24148: Add btree truncate functionality support.

scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py, scripts/install/opt/seagate/cortx/motr/bin/motr_setup
=> Motr hare keys

.xperior/testds/motr-single_tests.yaml, scripts/st.d/04initscripts, scripts/st.d/05confgen, scripts/st.d/06hagen, scripts/st.d/07mount-multiple, scripts/st.d/24motr-dix-repair-lookup-insert, scripts/st.d/28sys-kvs, scripts/st.d/28sys-kvs-kernel, scripts/st.d/35m0singlenode, scripts/st.d/36spare-reservation, scripts/st.d/37protocol, scripts/st.d/43motr-sync-replication, scripts/st.d/44motr-sns-repair, scripts/st.d/45motr-sns-repair-N-1, scripts/st.d/48motr-raid0-io, scripts/st.d/49motr-rpc-cancel
=> EOS-25115: Update xperior yaml to invoke all tests using scripts/m0 and update the mapping of STs to match with scripts/m0.

btree/btree.c, btree/btree.h
=> Changes in btree.c for integration purpose

balloc/balloc.c, btree/btree.c, btree/btree.h
- Removal of unused timer code in m0_btree_close()
=> EOS-24987 : Removal of temporary code

be/log_discard.c
m0_be_log_discard_flush() may finish waiting after io is done, but
before lds_discard_ast() is posted. It would lead to
be_log_discard_wait() to not to wait for the ast to be finished, which
leads to an assertion failure [1]. In this case traces look like [2] and
stack backtrace looks like [3].
This patch moves flush op to DONE at the end of the ast, which makes
flush() wait until the ast is actually executed.
The bug was discovered during EOS-25005 patch testing.
[1]
motr[24531]:  a3b0  FATAL  [lib/assert.c:50:m0_panic]  panic: (!ld->lds_sync_in_progress) at m0_be_log_discard_fini() (be/log_discard.c:143)  [git: 2.0.0-307-72-g0e307f7b-dirty] /w/var/m0ut/m0trace.24531
Motr panic: (!ld->lds_sync_in_progress) at m0_be_log_discard_fini() be/log_discard.c:143 (errno: 4) (last failed: none) …
=> EOS-25111 be/log_discard: avoid race between wait() and flush op

scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py, scripts/install/opt/seagate/cortx/motr/bin/motr_setup
- Problem statement: Make MOTR_M0D_CONF_XC({local_path}/motr/sysconfig/{machine_id}/confd.xc) entries in MOTR_SYS_CFG(/etc/sysconfig/motr)
=> Integration fixes remaining

.xperior/testds/motr-single_tests.yaml
=> EOS-25145 : Fix m0reportbug directory for jenkins xperior run

scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py, scripts/install/opt/seagate/cortx/motr/bin/motr_setup
Fetch metadata disks only for storage nodes.
Fetch metadata disks only for storage nodes. 
=> Mini prov fix to fetch proper cvg in fetching metadata disk

scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
=> Use machine_id in motr-hare keys

scripts/install/usr/libexec/cortx-motr/motr-free-space-monitor
=> Kubernetes:  Noop for fsm

be/ut/alloc.c, be/ut/main.c
- Write/Modify UT's to test and debug BE allocator changes
=> Eos 25484: UT for be allocator changes

utils/m0reportbug
- Improve m0reportbug to collect latest live core.
while collecting live core m0reportbug fails if the directory
size is huge due to stale data. This improvement avoids such
situation by collecting only the latest live cores created.
Checklist for Author 
=> EOS-24273: improve m0reportbug to collect latest live core

be/extmap.c, be/extmap.h, cas/ctg_store.c, cas/ctg_store.h, cas/ut/service_ut.c, stob/ad.c, stob/domain.c, stob/domain.h, stob/type.h, stob/ut/ad.c
- Fixing the ctg code bug and extmap ut
=> Ctg extmap bug fixing

net/ip.c, net/ip.h, net/libfab/libfab.c, net/libfab/libfab_internal.h
- Implementation of m0_net_ip_print() and m0_net_ip_to_hostname()
=> EOS-24240: implementation of m0_net_ip_print() and m0_net_ip_to_hostname()

conf/rconfc.c
Signed-off-by: Yeshpal Jain <yeshpal.jain@seagate.com>
=> rconfc: increase rconfc retry to support larger node cluster

fol/fol.h
Signed-off-by: Yeshpal Jain <yeshpal.jain@seagate.com>
=> FOL: set FOL_REC_MAXSIZE  to support multiple node setup

cob/cob.c
Resolve issues in generating rpms
=> Added static to cob_domain_truncate()

bindings/go/README.md
Information about go/mkv utility is missing in the README page.
Add it.
-----
[View rendered bindings/go/README.md](https://github.com/Seagate/cortx-motr/blob/andriytk-patch-1/bindings/go/README.md)
=> go/mio/README: add info about mkv

net/libfab/libfab.c
- hclt bootstrap got stuck in phase 1 stage
-  ep format is not updated properly for NATIVE IP FORMAT
-  [yes ] Coding conventions are followed and code is consistent
[root@ssc-vm-g2-rhev4-2221 cortx-motr]# hctl shutdown;hctl bootstrap --mkfs ../CDF.yaml
Making sure that RC leader can be re-elected next time
Stopping hare-consul-agent at ssc-vm-g2-rhev4-2221.colo.seagate.com...
Stopped hare-consul-agent at ssc-vm-g2-rhev4-2221.colo.seagate.com
Shutting down RC Leader at ssc-vm-g2-rhev4-2221.colo.seagate.com...
2021-11-22 12:22:21: Generating cluster configuration... OK
2021-11-22 12:22:23: Starting Consul server on this node......... OK
2021-11-22 12:22:33: Importing configuration into the KV store... OK
2021-11-22 12:22:34: Starting Consul on other nodes...Consul …
=> EOS 26216 : Hctl boot strap is stuck in kubernetes branch

motr/ut/idx_dix.c
=> dtm0: Fix build failure in ut/idx_dix.c

fdmi/plugins/fdmi_app, fdmi/plugins/fdmi_plugin_st.sh, fdmi/plugins/fdmi_sample_plugin.c
- Decoding from bytes to string with UTF-8 codec.
- Adding UTF-8 chars in ST.
fdmi_app terminated and replication failed when object name contains UTF-8 character.
UTF-8 encoded char should be treated as unsigned char.
=> EOS-25659 print UTF-8 encoded as unsigned char

console/console_it.c, xcode/string.c, xcode/ut/xcode.c, xcode/xcode.c, xcode/xcode.h
- Added support for U16 data type in xcode.
=> Changes to support U16 type in xcode.

btree/btree.c
Implement UTs to test the BE allocator/LRU nodes changes
=> Eos 26176: UT to test LRU changes

be/alloc.c, be/alloc_internal.h, be/ut/alloc.c, be/ut/main.c, btree/btree.c
- Aligned Chunk header implementation and btree integration.
=> EOS-25149: Aligned Chunk header implementation and btree integration.

balloc/balloc.c, be/extmap.c, be/tool/beck.c, btree/btree.c, btree/btree.h, cas/ctg_store.c, cob/cob.c, conf/db.c
=> Eos 26172 : Implementation of write path functions for CRC where CRC is encoded by user

stob/Makefile.sub, stob/addb2.h, stob/partition.c, stob/partition.h
Basic framework to support partition stob functionality.
-  https://seagate-systems.atlassian.net/wiki/spaces/~91827731/pages/712966428/Partition+Stob+Domain
-  [x ] Coding conventions are followed and code is consistent
Note: Testing will be performed once part domain EOS-24532 and integration code EOS-26301 is available.
=> Framework to support partition stob

scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py, scripts/install/opt/seagate/cortx/motr/bin/motr_setup
- Remove share path from cluster config file due to glusterfs removal
=> EOS-26579:Remove share path from cluster config file due to glusterfs removal

scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
kubeget logs <pod_name> -c <container_name> does not show any logs
-  Print the log messages to console and file to be read from kubeget logs <pod_name> -c <container_name> command
=> EOS-26717: print logs to console to be read from kubectl logs command

doc/Quick-Start-Guide.rst
=> Verified Motr QSG

be/domain.c, be/domain.h, be/partition_table.c, be/partition_table.h, stob/partition.c
Some of the pending fixme labels are addressed using this patch
Signed-off-by: Rinku Kothiya <rkothiya@redhat.com>
Some of the pending fixme labels are addressed using this patch
=> EOS-24532: Basic framework support for partition stob domain

doc/AR_RPC_Layer.md
Signed-off-by: Swati Dhotarkar <swati.dhotarkar@seagate.com>
-----
[View rendered doc/AR_RPC_Layer.md](https://github.com/swatid-seagate/cortx-motr/blob/AR_RPC_Layer/doc/AR_RPC_Layer.md)
=> AR_RPC_Layer.md file uploaded.

doc/Castor.md
-----
[View rendered doc/Castor.md](https://github.com/swatid-seagate/cortx-motr/blob/Castor/doc/Castor.md)
=> Castor.md file uploaded.

doc/CORTX-MOTR-ARCHITECTURE.md
-----
[View rendered doc/CORTX-MOTR-ARCHITECTURE.md](https://github.com/swatid-seagate/cortx-motr/blob/Cortx-Motr-Architecture/doc/CORTX-MOTR-ARCHITECTURE.md)
=> CORTX-MOTR-ARCHITECTURE.md file uploaded.

doc/Data-Organization.md
-----
[View rendered doc/Data-Organization.md](https://github.com/swatid-seagate/cortx-motr/blob/Data-Organization/doc/Data-Organization.md)
=> Data-Organization.md file uploaded.

doc/DMT.md
-----
[View rendered doc/DMT.md](https://github.com/swatid-seagate/cortx-motr/blob/DMT/doc/DMT.md)
=> DMT.md file uploaded.

ha/ut/note.c
Changes:
Update "ha-state-ut" to run with transport specific address format.
=> EOS-26715 : update ut files to use the transport specific address format

be/log_store.c, be/partition_table.c, be/partition_table.h, ioservice/storage_dev.c, ioservice/storage_dev.h, stob/ioq.c, stob/partition.c, stob/partition.h
Co-authored-by: Vidyadhar Pinglikar <vidyadhar.pinglikar@seagate.com>
- basic balloc/data support with partition stob.
-  [x ] Coding conventions are followed and code is consistent
- [ x] Tested basic motr+hare cluster operations in LR env, with limited io's.
- [x ] JIRA number/GitHub Issue added to PR
- [x ] PR is self reviewed
- [x ] Jira and state/status is updated and JIRA is updated with PR link
=> EOS-26224- basic balloc/data support with partition stob.

lib/coroutine.c, lib/coroutine.h
Removed log messages which were spamming trace log file.
Signed-off-by: Swapnil Chaudhary <swapnil.chaudhary@seagate.com>
- log messages were spamming trace log file. Hence we need to optimize the log messages.
-  Removed the unnecessary logs, which were spamming trace file.
-  [ Y] Coding conventions are followed and code is consistent
Performed compilation of code, to make sure there are no compile time errors.
- [Y ] JIRA number/GitHub Issue added to PR
=> EOS-25901: M0_CALL log level is incorporated in M0_LOG

sm/sm.c
Commented the debug logs, which were spaming m0 trace log file.
Signed-off-by: Swapnil Chaudhary <swapnil.chaudhary@seagate.com>
- Some log messages were spamming trace log file. Hence we need to optimize the log messages in trace log file.
-  Commented the logs, which are no longer required for debugging.
-  [Y ] Coding conventions are followed and code is consistent
- [Y ] JIRA number/GitHub Issue added to PR
=> EOS-26190:m0_sm_asts_run_function_spams_trace_log_file

rpc/formation2.c
Moved the debug log, to stop spamming spamming in log trace file.
Signed-off-by: Swapnil Chaudhary <swapnil.chaudhary@seagate.com>
-  [ Y] Coding conventions are followed and code is consistent
- [Y] JIRA number/GitHub Issue added to PR
=> EOS-26193:frm_fill_packet_from_item_sources_function_spams_trace_log

btree/btree.c
=> Fixing rpm failure

btree/btree.c, btree/btree.h
-  Implementation of BTREE ENCODED CRC for fixed format node
=> EOS-26326: Implementation of BTREE ENCODED CRC for fixed format node

scripts/install/opt/seagate/cortx/motr/bin/motr_setup
=> EOS-26908: Use setup_size to set some parameters in deployment phases

motr/client.h, motr/client_internal.h, motr/io.c, motr/io_nw_xfer.c, motr/io_req.c, motr/io_req_fop.c
Closes #1166.
- Make Motr side changes to Enable DI in main using the s3 flag
=> EOS-26312: enable di flag s3 api motr side changes

btree/btree.c, btree/btree.h
=> EOS-26987: Implement used space for nodes between low and high watermark

btree/btree.c
=> EOS-23901: CRC design for variable sized key and value node format

doc/FDMI-High-Level-Decomposition.md
-----
[View rendered doc/FDMI-High-Level-Decomposition.md](https://github.com/swatid-seagate/cortx-motr/blob/FDMI-Decomposition/doc/FDMI-High-Level-Decomposition.md)
=> FDMI-High-Level-Decomposition.md file uploaded

doc/Quick-Start-Guide.rst
Currently, it's not quite clearly documented how to build Motr for performance evaluations.
Extend QSG (Quick Start Guide) document on the subject.
=> doc/qsg: clarify build steps for perf evaluations

btree/btree.c
=> Btree bug fixes : making opaque pointer NULL after node put operation

btree/btree.c
Removed '#if 0' code from the btree codebase
=> Removed #if 0 code from btree.c

btree/btree.c
=> Eos 26174 : Implementation of btree embedded CRC support in fixed key, variable value node type

m0t1fs/linux_kernel/st/m0t1fs_sns_common_inc.sh, motr/st/utils/motr_conf_update_st.sh, motr/st/utils/motr_rpc_cancel_test.sh, motr/st/utils/motr_st_inc.sh
Following ST's are updated:
41motr-conf-update
42motr-utils
43m0crate
44motr-rm-lock-cc-io
44motr-sns-repair
45motr-sns-repair-N-1
48motr-raid0-io
49motr-rpc-cancel
=> EOS-27676 : Update ST 40-50 to use the transport specific address format.

btree/btree.c
=> Increased MAX_KEY_SIZE to 128 bytes

doc/Quick-Start-Guide.rst
=> Checked the Quick Start Guide steps with CentOS-7.9

cas/ctg_store.c, cas/ctg_store.h, cas/m0ctgdump.c
Also tidy up the code.
Signed-off-by: Sining Wu <sining.wu@seagate.com>
=> m0ctgdump: add an option to print records in hex

btree/btree.c
=> EOS-28494: Fix the MAX_KEY_SIZE issue for vkvv format

doc/Running_Motr_Across_a_Cluster.md
Created Running_Motr_Across_a_Cluster.md under
cortx-motr/doc path and updated it with the info given in
the wiki page for "Build Motr from Source in a Cluster".
-----
[View rendered doc/Running_Motr_Across_a_Cluster.md](https://github.com/bdekvadiya/cortx-motr/blob/build_motr_from_source_cluster/doc/Running_Motr_Across_a_Cluster.md)
=> EOS-28441 : Convert a Wiki Page into a .rst or .md document

fdmi/plugin_dock.c, fdmi/ut/fol_ut.c, fdmi/ut/pd_ut.c
=> EOS-28789: fix memleak in FDMI and its UT

scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
- Currently motr client apps can't be run in kubernetes cluster
-  A separate client pod is added so that user can run motr application in it.
motr_client service is introduced by checking it in entrypoint motr_setup 
script will keep running so that any motr client applications can be executed
inside this pod.
=> Motr client changes

scripts/install-motr-service, utils/spiel/m0_bytecount_stats, utils/spiel/m0spiel
- Degraded capacity byte count : stand alone spiel utility for bytecount stats.
-  call m0_spiel_proc_counters_fetch() using m0spiel python framework .
=> CORTX-28625 : added spiel utility for bytecount stats

.gitignore, .xperior/testds/motr-single_tests.yaml, motr/st/utils/sns_repair_motr_quiesce.sh, motr/st/utils/sns_repair_motr_shutdown.sh, motr/st/utils/sns_repair_shutdown.sh, scripts/st.d/68sns-repair-motr-shutdown, scripts/st.d/68sns-repair-shutdown, scripts/st.d/69sns-repair-motr-quiesce, scripts/st.d/69sns-repair-quiesce, utils/functions
* This commit fixes the following STs:
- 68sns_repair_shutdown
=> CORTX-25679: Fix SNS Repair STs

balloc/balloc.c, balloc/balloc.h, be/extmap_internal.h, btree/btree.c, btree/btree.h
- Addressed PR comments in the Btree and related code.
=> Addressed PR comments.

btree/btree.c
- Fixed comments for readability.
=> Fixed description in code to resolve PR comments.

btree/btree.c
=> Removal of stale member variables in struct node_op.

console/st/console-st.sh, scripts/m0, utils/functions, utils/spiel/cleanup-on-quit.txt
This patch fixes the following:
- ST execution exits after encountering the first SKIPPED test.
- 03console test terminates the running ST execution after test
completion.
=> CORTX-29039:Fix Motr STs.

be/tool/beck.c, cas/ctg_store.c, cas/ctg_store.h
=> CORTX-29220: Changes in cas module to use ff node format

scripts/jenkins/code-coverage.groovy
This script is used in a jenkins job to do the code
coverage of the motr code.
Create a new job to run code coverage for cortx-motr
This script will run the code coverage on motr code.
=> CORTX-29207: Script to run code coverage via Jenkins

be/domain.c, motr/motr-pub.api, scripts/coverage/gcov-gen-html
This patch fixes the compilation errors that we get
on Rocky Linux 8.4 while we enable code coverage.
To enable code coverage on Rocky Linux.
Fixed some compiler warnings.
=> CORTX-29450: Fix compilation errors for code coverage

cob/cob.c, cob/cob.h
Added new version field in all keys of cob data structure.
=> CORTX-28221: Changes in cob to support upgrade by adding version field

pool/pool.c
One year ago DTM team tried to make the very first version of DTM0 transport (it was not even called "transport" at that time) which was based on Motr RPC links and reqh_service_ctx. The reqh_service_ctx-based connections helped us to ensure that DTM0 services have RPC connections. Later on, we developed our own transport based on "connect-on-demand" idea, so that those reqh_service_ctx became completely obsolete. They were not removed, and that causes some problems. For example, it leads to the situation where m0_client gets blocked waiting for another client to start (if there are more than one client in the configuration). The solution here is simple -- remove the obsolete code.
I manually tested the patch using dtm0-dynamic-fids-disable branch (Hare) and devel/EOS-26205-for-all2all …
=> CORTX-29143: Disable all-to-all reqh_service_ctx connections for DTM0 services

doc/ADDB.md
-----
[View rendered Motr-Terminology-Guide.md](https://github.com/swatid-seagate/cortx-motr/blob/swatid-patch-ADDB/Motr-Terminology-Guide.md)
[View rendered doc/ADDB.md](https://github.com/swatid-seagate/cortx-motr/blob/swatid-patch-ADDB/doc/ADDB.md)
[View rendered doc/motr-in-prose.md](https://github.com/swatid-seagate/cortx-motr/blob/swatid-patch-ADDB/doc/motr-in-prose.md)
=> Swatid patch addb

Makefile.am, conf/st, cortx-motr.spec.in, scripts/install-motr-service, scripts/install/opt/seagate/cortx/motr/sanity/motr_sanity.sh, scripts/provisioning/roles/base-os/tasks/main.yml, spiel/st/m0t1fs_spiel_dix_common_inc.sh, spiel/st/m0t1fs_spiel_sns_common_inc.sh, spiel/st/m0t1fs_spiel_st.sh, spiel/st/spiel_multiple_confd.sh, st/m0d-device-detach-test.sh, utils/functions, utils/spiel/README, utils/spiel/m0_bytecount_stats, utils/spiel/m0_filesystem_stats, utils/spiel/m0spiel, utils/spiel/motr.c
Python2 is EOL, port m0spiel to python3
Unit and System Tests are working
Testing was performed with RPM
JIRA - https://jts.seagate.com/browse/CORTX-6081
=> CORTX-6081 - Port m0spiel utilities and ST to python3

scripts/workload/m0workload
- Motr m0workload for k8s
m0workload script is used by motr internally to run motr utils like m0cp, m0crate etc. In k8s, we are planning to use it in client pods.
Tested it on client pod cortx-hax container where we can get cluster status using 'hctl status --json' which helps us to build cluster values like client, ha endpoints etc. These scripts also  require some python modules like pandas , xlrd.
In testing,
1: We created workload yaml file from .xls file using command '/opt/seagate/cortx/motr/workload/m0workload/create_workload_from_excel -t ./sample_workload_excel_test.xls'
`[root@cortx-client-headless-svc-ssc-vm-g4-rhev4-0710 workload]# …
=> CORTX-30135: m0worklad script changes for k8s

motr/io.c, motr/ut/client.c
=> Change user-visible name of motr/ut/client.c UT suite.

motr/client.h
Fix wrong and misleading descriptions of some index operations, especially M0_IC_LIST.
=> motr/client: fix some index ops api documentation

ut/stob.c
=> m0_ut_stob_fini(): finalise the domain properly.

net/test/node_bulk.c
Network transports that do not support synchronous completion event delivery
(like libfabric), need synchronisation between asynchronous call-backs and the
main thread in nettest.
A special mutex (ctx->nbc_bulk_mutex) was added for this, but it only protected
ring-buffer manipulations in server_process_unused_ping(). But both ring-buffer
and buffer state should be updated atomically. Expand the critical sections to
cover buffer state changes.
Without this change
$ ./utils/m0run m0ut -- -n4000 -tnet-test:client-server-bulk
fails after a few dozen iterations:
START Iteration: 18 out of 10000
net-test
client-server-bulk  motr[1077012]:  ba20  FATAL  [lib/assert.c:50:m0_panic]  panic: (can_change) at node_bulk_state_change() (net/test/node_bulk.c:384)  [git: 2.0.0-670-45-g87fc0d31-dirty]... …
=> net/test/node_bulk.c: fix a race with asynchronous completion call-back

doc/Quick-Start-Guide.rst
Done validation of the following sections from Quick Start Guide
steps with Rocky Linux version 8.4
Get the Sources
Build
Running Tests
Build the documentation
=> CORTX-30802: PI6 motr QSG Verification

net/libfab/libfab.c
See https://github.com/Seagate/cortx-motr/issues/1688:
libfab_poller()->libfab_txep_event_check(xep,
...)->libfab_buf_done()->libfab_buf_complete()->m0_net_buffer_event_post()->user-call-back.
The call-back frees the buffer and releases the last reference on the
end-point. The end-point is freed. On the return to libfab_txep_event_check()
the next iteration of m0_tl_teardown(fab_sndbuf, &txep->fep_sndbuf, fbp) loop
crashes.
Solution: acquire and release an additional reference to the end-point while it
is being processed by poller.
=> libfab_poller(): make sure the end-point is not freed while being used.

utils/m0reportbug
Motr support bundle does not conation sns/dix config info
=> CORTX-30109: Motr Support bundle should contain sns/dix config params.

scripts/beck/st/error_injection.py
Signed-off-by: Gaurav Gaur <gaurav.gaur@seagate.com>
- Fixed Codacy issues related to security and optimized the code.
=> Fixed codacy issue related to security and duplication

be/dtm0_log.h, motr/client.h
Clarify that the list of indices are fetched via keys array argument of m0_idx_op().
=> motr/client: improve M0_IC_LIST op API doc

btree/btree.c
=> CORTX-30550: Resolve btree pr review comments

motr/io_nw_xfer.c, motr/io_req.c
The redundancy of the user data will be degraded in this case,
but we accept that risk for now. The redundancy will be restored
during SNS repair later.
Relates to https://github.com/Seagate/cortx-motr/issues/1598.
=> client: return write success on <= K failures

utils/m0run
=> utils/m0run: add "user" debugger.

dtm0/fop.c
=> m0_dtm0_fop_fini(): finalise fop addb instrumentation

scripts/jenkins/build, scripts/jenkins/code-coverage-with-xperior-and-doxygen.groovy
This patch helps set different options while creating build
using xperior frame work.
Enable code coverage while creating builds in xperior.
We can pass different build options via environment variable.
=> CORTX-29629: Enable options setting for creating builds

lib/user_space/ugetopts.c
=> m0_getopts(): check for duplicate options

.alexrc
Signed-off-by: Venkatesh K <venkatesh.k@seagate.com>
Alex report false positive 
Added the words into exception list. 
=> CORTX-30766: Adding Alex's exception list

fop/Kbuild.sub
=> adding fop/wire_xc.c to the kernel build.

scripts/provisioning/README.md
-----
[View rendered scripts/provisioning/README.md](https://github.com/vimleshsgt/cortx-motr/blob/esiwace2-dkrz/scripts/provisioning/README.md)
=> Modifying README

dix/ut/client_ut.c
Problem:
Currently we have a UTs for degraded GET and NEXT in case
of PERMANENT failures (FAILED devices). Since we are going
to support degraded mode in case of TRANSIENT failures
(OFFLINE devices) then we need to implement corresponding
UTs to check correctness of DIX GET/NEXT operations in
case of offline devices in a system.
Solution:
Implement a UTs for degraded DIX GET and NEXT in case of
presence of OFFLINE devices.
NOTE: UT for DIX NEXT is incomplete since currently we do not
check number of offline devices against max allowed number of
TRANSIENT failures, there is a corresponding comment in a code.
=> CORTX-31605 dix/ut: add UTs for degraded GET and NEXT (OFFLINE devs)

m0t1fs/linux_kernel/st/m0t1fs_cc_io_with_sns_repair.sh
warning fixed : "Double quote to prevent globing and words splitting".
We see 1688 occurrence of pattern, "Double quote to prevent globing and word splitting".
We are putting the variable references in double quotes.
=> CORTX-30751: Codacy code cleanup (#1606)

dix/cm/ut/iter_ut.c
- Codacy reported lot of duplications in dix/cm/ut/iter_ut.c file. 
-  Here common code is moved to functions to reduce duplications for repair tests.
=> Cortx 31436 fix duplications iter ut

bindings/go/README.md
-----
[View rendered bindings/go/README.md](https://github.com/Seagate/cortx-motr/blob/andriytk-patch-1/bindings/go/README.md)
=> go/README: add links for Reader/Writer interface

.alexrc
Added non-mandatory words to the exception list from Alex report.
=> CORTX-31960 : [Alex]Add set of words to exception list

doc/data-flow/conf.py, doc/dev/conf.py, scripts/addb-py/chronometry/fom_req.py, scripts/addb-py/chronometry/hist.py, scripts/addb-py/chronometry/io_req.py, scripts/addb-py/chronometry/md_req.py, scripts/addb-py/chronometry/queues.py, scripts/addb-py/chronometry/s3server_integration/s3_overrides.py, scripts/addb-py/chronometry/task_queue/config.py, scripts/addb-py/filter.py, scripts/addb2/addb2grammar.py
warning fixed : "Unused-imports"
Codacy warnings, "Unused-imports"
Removed the unused imports
=> Codacy code cleanup

README.md
Signed-off-by: Yanqing Fu <yanqing.f.fu@seagate.com>
-----
[View rendered README.md](https://github.com/yanqingfu/cortx-motr/blob/patch-3/README.md)
=> update contributors number related with cortx-motr

motr/st/utils/be_log_resize.sh, scripts/addb-py/chronometry/corruption_workload, scripts/addb-py/chronometry/io_workload, scripts/addb-py/chronometry/p0, scripts/addb-py/chronometry/p0_hare, scripts/addb-py/chronometry/s3_corruption_workload, scripts/addb-py/chronometry/s3_workload, scripts/install/etc/sysconfig/motr, scripts/install/opt/seagate/cortx/motr/libexec/m0addb_logrotate.sh, scripts/install/opt/seagate/cortx/motr/libexec/motr_data_recovery.sh, scripts/install/usr/lib/systemd/system/m0d@.service, scripts/install/usr/lib/systemd/system/motr-mkfs.service, scripts/install/usr/lib/systemd/system/motr-mkfs@.service, scripts/install/usr/lib/systemd/system/motr-server-confd.service, scripts/install/usr/lib/systemd/system/motr-server-ha.service, scripts/install/usr/lib/systemd/system/motr-server@.service, scripts/install/usr/lib/systemd/system/motr-trace@.service, scripts/install/usr/lib/systemd/system/motr.service, scripts/install/usr/libexec/cortx-motr/motr-service.functions, scripts/install/usr/libexec/cortx-motr/motr-trace
and directory movement to user home directory.
Signed-off-by: Vimlesh Kumar <vimlesh.kumar@seagate.com>
=> First phase changes adding support for usermode systemctl

CODEOWNERS
Signed-off-by: Mukul Malhotra <mukul.malhotra@seagate.com>
- Codeowner Added for Motr
=> CORTX-32080: Codeowner Added

scripts/addb-py/record.py, scripts/gdb/gdb-extensions.py
Warning fixed: "no-self-use"
Warnings seen, "no-self-use"
Since the class method is not using the object this can either be a static function or a normal function 
which is not a member of the class. So here we have made the function static.
=> Cortx-32012: Codacy warning/issues fixes cleanup (#1852)

doc/data-flow/conf.py, doc/dev/conf.py, scripts/addb-py/chronometry/addb2db.py, scripts/addb-py/chronometry/hist.py, scripts/addb-py/chronometry/req_utils.py
warning fixed : "redefined-builtin"
Codacy warning "redefined-builtin"
Suppressed the error. 
=> CORTX-31984: Codacy warning/issue fixes (#1606)

motr/ut/io_req.c
This is a follow-up change to the commit c03c93467.
io-req-ut:device_check() UT fails since the commit c03c93467.
Update the UT code.
=> ut: update io-req-ut:device_check() test

be/dtm0_log.c
* Update be_dtm0_log_iter_invariant() to use ergo() in condition.
=> dtm/recovery: Address code review comments (part 4).

btree/btree.c
=> Add seg header validation in bnode_get()

.alexrc, doc/HLD-Capability-Motr.md
Addressed reported words in Alex report, by replacing or adding
them in exception list.
-----
[View rendered doc/HLD-Capability-Motr.md](https://github.com/bdekvadiya/cortx-motr/blob/CORTX-30091_alex_issues/doc/HLD-Capability-Motr.md)
=> CORTX-30091 : Address inconsiderate words in Alex report

motr/st/utils/spiel_sns_motr_repair.sh
Problem: Currently, rebalance abort testcase is throwing Panic and hence this testcase is failing.
As a workaround, I have commented the rebalance abort testcase, till the time panic is resolved.
-  [ Y] Coding conventions are followed and code is consistent
- [ Y] JIRA number/GitHub Issue added to PR
=> CORTX-30750_Comment_Rebalance_abort_test_in_71spiel-sns-motr-repair

motr/io_req_fop.c
Problem: when writting a 200MB object using rgw and one of m0ds is
killed, there exists a case where degraded write fails if posting
COB CREATION fops fails.
(0) motr cluster settings: 5 ioservices each has 2 disks
parity group settings: 6 + 2 + 0, unit size = 4MB
(1) When writing the last 8MB of the 200MB object (48MB * 4 + 8MB),
as 8MB doesn't cover the whole parity group, for those units
it doesn't span, motr tries to send COB CREATION to ioservice,
see the code around line 1618 in io_nw_xfer.c
(2) when dispatching the fops in nw_xfer_req_dispatch(), it calls
m0_rpc_post() (around line 1870 in io_nw_xfer.c) for those
COB CREATION fops, if the target ioservice happens to crash
and rpc connection is broken, m0_rpc_post() returns -125 error
code, but this error code is not handled in …
=> client: fix degraded write on cob create

rpc/at.c, rpc/formation2.c, rpc/it/linux_kernel/load.sh, rpc/it/linux_kernel/rpcload.sh, rpc/it/linux_kernel/unload.sh, rpc/it/rpc_ping.c, rpc/ub/plot.sh, rpc/ub/ub.c, rpc/ut/link_ut.c
Codacy issues resolved for following files  
1. rpc/formation2.c
2. rpc/it/rpc_ping.c
3. rpc/at.c
4. rpc/ut/link_ut.c
5. rpc/ub/ub.c
6. rpc/it/linux_kernel/load.sh
7. rpc/it/linux_kernel/rpcload.sh
8. rpc/it/linux_kernel/unload.sh
9. rpc/ub/plot.sh
For details on changes please refer https://jts.seagate.com/browse/CORTX-30079
=> CORTX-30079 - Fix Codacy issue in rpc directory

btree/btree.c
- Change segaddr_header_isvalid() as a generic function
=> CORTX-30543 : Change segaddr_header_isvalid() as a generic function

doc/HLD_NewBtree.md
- BTree documentation in github
-----
[View rendered doc/HLD_NewBtree.md](https://github.com/ydb242/cortx-motr/blob/CORTX-30619/doc/HLD_NewBtree.md)
=> CORTX-30619: BTree documentation in github

btree/btree.c
=> Add btree_seg_header_validate while searching for sibling

scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py, scripts/install/opt/seagate/cortx/motr/bin/motr_setup
- Support in motr_mini_prov.py to set BTree watermark values
=> Support in motr_mini_prov.py to set BTree watermark values

cas/service.c
Currently there is no validation of the target SDEV in the received CAS request. This makes it difficult to discover bugs if there are any in the originator/participant code.
The code in this PR will make this validation and since the code is quite light-weight it does not hurt the performance either.
=> CORTX-31180: Validate the sdev id in the received CAS request.

scripts/install/usr/lib/systemd/system/m0d@.service, scripts/install/usr/lib/systemd/system/m0t1fs@.service, scripts/install/usr/lib/systemd/system/motr-cleanup.service, scripts/install/usr/lib/systemd/system/motr-client.service, scripts/install/usr/lib/systemd/system/motr-kernel.service, scripts/install/usr/lib/systemd/system/motr-mkfs.service, scripts/install/usr/lib/systemd/system/motr-mkfs@.service, scripts/install/usr/lib/systemd/system/motr-server-confd.service, scripts/install/usr/lib/systemd/system/motr-server-ha.service, scripts/install/usr/lib/systemd/system/motr-server@.service, scripts/install/usr/lib/systemd/system/motr-trace@.service, scripts/install/usr/lib/systemd/system/motr.service, scripts/install/usr/libexec/cortx-motr/motr-kernel, scripts/install/usr/libexec/cortx-motr/motr-mkfs, scripts/install/usr/libexec/cortx-motr/motr-server, scripts/install/usr/libexec/cortx-motr/motr-service.functions, scripts/install/usr/libexec/cortx-motr/motr-trace
Signed-off-by: Vimlesh Kumar <vimlesh.kumar@seagate.com>
=> Moving cortx-motr completely in user space hence user home directory.

.xperior/testds/motr-single_tests.yaml, motr/st/utils/motr_di_corruption_detection_st.sh, scripts/st.d/73motr-di-corruption-detection
…rruption.
- Add ST to corrupt and detect data corruption.
-  Added 73motr-di-corruption-detection ST to corrupt and detect data corruption.
-  Epic-F23E
=> CORTX-27768 : ST to corrupt and detect data corruption

btree/btree.c
Optimize the node Capture for FF node format
=> CORTX-31893 : Optimize the node Capture for FF node format

scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
- updating motr conf parameters based on resource limits
in motr mini provisioner config stage
MOTR_M0D_MAX_RPC_MSG_SIZE
MOTR_M0D_MIN_RPC_RECVQ_LEN
MOTR_M0D_IOS_BUFFER_POOL_SIZE
MOTR_M0D_SNS_BUFFER_POOL_SIZE
=> CORTX-29958: Tuning motr conf parameters based on resource limits

scripts/install/usr/libexec/cortx-motr/motr-mkfs, scripts/install/usr/libexec/cortx-motr/motr-server
Signed-off-by: Vimlesh Kumar <vimlesh.kumar@seagate.com>
=> Adding path to take libisal from user home directory

autogen.sh, hsm/m0hsm_api.c
-Fix Codacy critical errors/warnings
-  Added shebang directive in autogen shell script
-  Added width  specifier in sscanf.
=> CORTX-26909 : Added shebang directive in autogen shell script.

scripts/addb-py/filter.py, scripts/addb-py/main.py, scripts/addb-py/record.py
Signed-off-by: Gaurav Gaur <gaurav.gaur@seagate.com>
- There are Codacy issues in scripts/addb-py/record.py,filter.py,main.py. 
Errors & solution:
1. local variable 'tr' is assigned to but never used
- Comment out for the future purpose
2. undefined name 'node'
- Change it 
3. Using variable 'node' before assignment
- Assigned at the right place
4. local variable 'time' is assigned to but never used
-  Change the position at right place
5. Unused variable 'args'
- It got solve automatically
6. invalid syntax 
- Fixed the print statement
7. Redefining built-in 'str'
- changed str to word
8. No value for argument 'str' in static method call
- Can not use str as variable
9. undefined name 'string'
- defined it
10. Trailing whitespace
- removed white space
-  Used new pylint rules to fix …
=> CORTX-33667 Fixed codacy issues under addb-py files

.alexignore
Exclude CODE_OF_CONDUCT file from Alex Scan
Signed-off-by: subhalaxmisa <subhalaxmi.sahoo@seagate.com>
- Exclude CODE_OF_CONDUCT file from Alex Scan
=> CORTX-31595 - Exclude CODE_OF_CONDUCT file from Alex Scan

doc/FOPFOM-Programming-Guide.md, doc/HLD-OF-Motr-LNet-Transport.md, doc/HLD-of-Catalogue-Service.md, doc/Motr-Lnet-Transport.md, doc/Running_Motr_Across_a_Cluster.md, doc/motr-object-app.md
Signed-off-by: Pratik Patil <pratik.k.patil@seagate.com>
- Codacy warnings in below given files:
- [fenced-code-flag]
- doc/Motr-Lnet-Transport.md
- doc/Running_Motr_Across_a_Cluster.md
- doc/FOPFOM-Programming-Guide.md
- doc/HLD-OF-Motr-LNet-Transport.md
- doc/HLD-of-Catalogue-Service.md
- doc/motr-object-app.md
- [fenced-code-flag] -> added name of programming language after  3 backquotes ```
-----
[View rendered doc/FOPFOM-Programming-Guide.md](https://github.com/Garuda5611/cortx-motr/blob/CORTX33978/doc/FOPFOM-Programming-Guide.md)
[View rendered …
```
=> CORTX-33978- codacy cleanup: Fixed codacy formatting issues

mdservice/ut/mdstore.c
- Fix mdservice-ut failure in 00userspace-tests for Motr PR jenkins
-  Set struct fom::fo_local_update variable to 'true' while creating fom in mdservice-ut.
=> CORTX-32492: Fix mdservice-ut failure in 00userspace-tests for Motr PR jenkins

cas/client.c
=> CORTX-26280 : Replace M0_ERR with M0_RC in case of ENOENT.

cm/cm.h, sns/cm/cm.c, sns/cm/cm.h, sns/cm/dtrebalance/cm.c, sns/cm/rebalance/cm.c, sns/cm/repair/cm.c
- Add new accumulator buffer pool for SNS Direct Rebalance
-  Introduced new buffer pool for           
accumulators for incoming copy packets. Added cm specific       
functions for buffer pool allocation, pruning, and finalization
=> Cortx 27973
